using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Abstraction.SourceGenerator;

/// <summary>
/// Source generator: detects service classes marked with AutoInjectAttribute in the current project and
/// generates assembly initializer + registration metadata code.
/// </summary>
[Generator]
public class AutoInjectGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sourceClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) =>
                {
                    if (ctx.Node is not ClassDeclarationSyntax cds)
                    {
                        return null;
                    }
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(cds);
                    if (symbol is { IsAbstract: false, DeclaredAccessibility: Accessibility.Public } &&
                        HasAutoInjectAttribute(symbol))
                    {
                        return symbol;
                    }
                    return null;
                })
            .Where(static s => s is not null);

        var allTypesWithAssembly = context.CompilationProvider
            .Combine(sourceClasses.Collect())
            .Select(static (data, _) =>
            {
                var (compilation, fromSource) = data;
                var set = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
                foreach (var t in Enumerable.OfType<INamedTypeSymbol>(fromSource))
                {
                    set.Add(t);
                }
                var assemblyName = compilation.AssemblyName ?? "Unknown";
                return (AssemblyName: assemblyName, Types: set.ToImmutableArray());
            });

        context.RegisterSourceOutput(allTypesWithAssembly, static (spc, data) =>
        {
            if (data.Types.IsEmpty)
            {
                return;
            }

            var source = GenerateServiceRegistrationExtension(data.AssemblyName, data.Types);
            spc.AddSource("AutoInjectAssemblyInitializer.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private const string AutoInjectAttributeFullName = "Microsoft.Extensions.DependencyInjection.AutoInjectAttribute";

    private static bool HasAutoInjectAttribute(ISymbol symbol)
        => symbol.GetAttributes().Any(IsAutoInjectAttribute);

    private static bool IsAutoInjectAttribute(AttributeData attribute)
        => attribute.AttributeClass?.ToDisplayString() == AutoInjectAttributeFullName;

    private static string GenerateServiceRegistrationExtension(string assemblyName, ImmutableArray<INamedTypeSymbol> serviceClasses)
    {
        var sanitizedName = assemblyName.Replace(".", "");
        var initializerTypeName = $"__{sanitizedName}AutoInjectAssemblyInitializer";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("[assembly: global::NOF.Abstraction.AssemblyInitializeAttribute<global::" + assemblyName + "." + initializerTypeName + ">]");
        sb.AppendLine();

        sb.AppendLine($"namespace {assemblyName}");
        sb.AppendLine("{");

        sb.AppendLine($"    internal sealed class {initializerTypeName} : global::NOF.Abstraction.IAssemblyInitializer");
        sb.AppendLine("    {");
        sb.AppendLine("        public static void Initialize(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (!services.InitializedTypes.Add(typeof({initializerTypeName})))");
        sb.AppendLine("            {");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine();

        foreach (var serviceClass in serviceClasses)
        {
            GenerateRegistryRegistration(sb, serviceClass);
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateRegistryRegistration(StringBuilder sb, INamedTypeSymbol serviceClass)
    {
        var attribute = serviceClass.GetAttributes().FirstOrDefault(IsAutoInjectAttribute);

        if (attribute is null)
        {
            return;
        }

        if (attribute.ConstructorArguments.Length <= 0 || attribute.ConstructorArguments[0].Value is not int intValue)
        {
            return;
        }

        var lifetime = intValue switch
        {
            0 => "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton",
            1 => "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped",
            2 => "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient",
            _ => throw new ArgumentOutOfRangeException()
        };

        var typeFormat = SymbolDisplayFormat.FullyQualifiedFormat
            .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

        var implementationTypeName = serviceClass.ToDisplayString(typeFormat);

        var registerTypesArg = attribute.NamedArguments.FirstOrDefault(kvp => kvp.Key == "RegisterTypes").Value;
        var hasExplicitRegisterTypes = !registerTypesArg.IsNull;

        var explicitAllTypes = new List<string>();
        var explicitNonSelfTypes = new List<string>();
        if (registerTypesArg.Kind == TypedConstantKind.Array)
        {
            foreach (var typedConstant in registerTypesArg.Values)
            {
                if (typedConstant.Value is not ITypeSymbol regType)
                {
                    continue;
                }

                var typeName = regType.ToDisplayString(typeFormat);
                explicitAllTypes.Add(typeName);
                if (typeName != implementationTypeName)
                {
                    explicitNonSelfTypes.Add(typeName);
                }
            }
        }

        var defaultInterfaceTypes = serviceClass.AllInterfaces
            .Select(i => i.ToDisplayString(typeFormat))
            .ToList();

        void Emit(string serviceTypeName, bool useFactory)
        {
            var descriptor = useFactory
                ? $"global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(typeof({serviceTypeName}), sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(sp, typeof({implementationTypeName})), {lifetime})"
                : $"global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(typeof({serviceTypeName}), typeof({implementationTypeName}), {lifetime})";

            sb.AppendLine($"            services.Add({descriptor});");
        }

        if (intValue is 0 or 1)
        {
            var typesToRegister = hasExplicitRegisterTypes ? explicitNonSelfTypes : defaultInterfaceTypes;
            if (typesToRegister.Count == 1)
            {
                Emit(typesToRegister[0], useFactory: false);
            }
            else
            {
                Emit(implementationTypeName, useFactory: false);
                foreach (var serviceType in typesToRegister)
                {
                    Emit(serviceType, useFactory: true);
                }
            }
        }
        else
        {
            if (hasExplicitRegisterTypes)
            {
                foreach (var serviceType in explicitAllTypes)
                {
                    Emit(serviceType, useFactory: false);
                }
            }
            else if (defaultInterfaceTypes.Count > 0)
            {
                foreach (var serviceType in defaultInterfaceTypes)
                {
                    Emit(serviceType, useFactory: false);
                }
            }
            else
            {
                Emit(implementationTypeName, useFactory: false);
            }
        }
    }
}
