using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Abstraction.SourceGenerator;

/// <summary>
/// Source generator: detects handler classes inheriting InMemoryEventHandler in the current project
/// and generates assembly initializer metadata for the event handler registry.
/// </summary>
[Generator]
public sealed class EventHandlerRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sourceClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, ct) =>
                {
                    if (ctx.Node is not ClassDeclarationSyntax cds)
                    {
                        return null;
                    }

                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(cds) as INamedTypeSymbol;
                    if (symbol is { IsAbstract: false, IsGenericType: false } && IsEventHandlerType(symbol))
                    {
                        return symbol;
                    }

                    return null;
                })
            .Where(static s => s is not null);

        var allTypesWithAssembly = context.CompilationProvider
            .Combine(sourceClasses.Collect())
            .Select(static (data, _) =>
            {
                var (compilation, fromSource) = data;
                var set = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
                foreach (var type in Enumerable.OfType<INamedTypeSymbol>(fromSource))
                {
                    set.Add(type);
                }

                return (AssemblyName: compilation.AssemblyName ?? "Unknown", Types: set.ToImmutableArray());
            });

        context.RegisterSourceOutput(allTypesWithAssembly, static (spc, data) =>
        {
            var source = GenerateAssemblyInitializer(data.AssemblyName, data.Types);
            if (!string.IsNullOrWhiteSpace(source))
            {
                spc.AddSource("EventHandlerAssemblyInitializer.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private static bool IsEventHandlerType(INamedTypeSymbol symbol)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            if (current.IsGenericType
                && current.OriginalDefinition.ToDisplayString() == "NOF.Abstraction.InMemoryEventHandler<TEvent>")
            {
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }

    private static string GenerateAssemblyInitializer(string assemblyName, ImmutableArray<INamedTypeSymbol> handlerClasses)
    {
        if (handlerClasses.IsEmpty)
        {
            return string.Empty;
        }

        var typeFormat = SymbolDisplayFormat.FullyQualifiedFormat
            .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Included);
        var registrations = new List<string>();

        foreach (var handlerClass in handlerClasses)
        {
            var handlerTypeName = handlerClass.ToDisplayString(typeFormat);
            var current = handlerClass.BaseType;
            while (current is not null)
            {
                if (current.IsGenericType && current.OriginalDefinition.ToDisplayString() == "NOF.Abstraction.InMemoryEventHandler<TEvent>")
                {
                    var eventTypeName = current.TypeArguments[0].ToDisplayString(typeFormat);
                    registrations.Add($"new global::NOF.Abstraction.EventHandlerRegistration(typeof({handlerTypeName}), typeof({eventTypeName}))");
                    break;
                }

                current = current.BaseType;
            }
        }

        if (registrations.Count == 0)
        {
            return string.Empty;
        }

        var sanitizedName = assemblyName.Replace(".", "");
        var initializerTypeName = $"__{sanitizedName}EventHandlerAssemblyInitializer";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("[assembly: global::NOF.Annotation.AssemblyInitializeAttribute<global::" + assemblyName + "." + initializerTypeName + ">]");
        sb.AppendLine();
        sb.AppendLine($"namespace {assemblyName}");
        sb.AppendLine("{");
        sb.AppendLine($"    internal sealed class {initializerTypeName} : global::NOF.Annotation.IAssemblyInitializer");
        sb.AppendLine("    {");
        sb.AppendLine("        private static int _initialized;");
        sb.AppendLine();
        sb.AppendLine("        public static void Initialize()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (global::System.Threading.Interlocked.Exchange(ref _initialized, 1) == 1)");
        sb.AppendLine("            {");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine();

        foreach (var registration in registrations)
        {
            sb.AppendLine($"            global::NOF.Abstraction.Registry.EventHandlerRegistrations.Add({registration});");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
