using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Hosting.SourceGenerator;

[Generator]
public class RpcServiceClientGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol classSymbol)
                    {
                        return null;
                    }

                    return TryGetRpcClientInterfaceFromHttpRpcClientAttribute(classSymbol, out var _, out var _) ? classSymbol : null;
                })
            .Where(static m => m is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(classProvider.Collect());
        context.RegisterSourceOutput(compilationAndClasses, Generate);
    }

    private static void Generate(SourceProductionContext context, (Compilation Compilation, ImmutableArray<INamedTypeSymbol?> Classes) source)
    {
        if (source.Classes.IsDefaultOrEmpty)
        {
            return;
        }

        foreach (var targetClass in source.Classes.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            GenerateForTargetClass(context, targetClass);
        }
    }

    private static void GenerateForTargetClass(SourceProductionContext context, INamedTypeSymbol targetClass)
    {
        if (!TryGetRpcClientInterfaceFromHttpRpcClientAttribute(targetClass, out var clientInterface, out var iface)
            || clientInterface is null
            || iface is null)
        {
            return;
        }

        if (!RpcServiceHelpers.IsRpcServiceInterface(iface))
        {
            return;
        }

        var methods = GetServiceMethods(iface);
        if (methods.Count == 0)
        {
            return;
        }

        var targetNamespace = RpcServiceHelpers.GetFullNamespace(targetClass.ContainingNamespace);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using NOF.Abstraction;");
        sb.AppendLine("using NOF.Contract;");
        sb.AppendLine();
        sb.AppendLine($"namespace {targetNamespace}");
        sb.AppendLine("{");

        var clientInterfaceName = clientInterface.Name;
        var clientInterfaceNamespace = RpcServiceHelpers.GetFullNamespace(clientInterface.ContainingNamespace);
        var fullyQualifiedClientInterfaceName = string.IsNullOrWhiteSpace(clientInterfaceNamespace)
            ? clientInterfaceName
            : $"{clientInterfaceNamespace}.{clientInterfaceName}";

        // No accessibility modifier here; the user-authored partial declaration decides visibility.
        sb.AppendLine($"    partial class {targetClass.Name} : global::{fullyQualifiedClientInterfaceName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::System.Net.Http.HttpClient _httpClient;");
        sb.AppendLine("        private readonly global::NOF.Hosting.IRequestOutboundPipelineExecutor _outboundPipeline;");
        sb.AppendLine("        private readonly global::System.IServiceProvider _serviceProvider;");
        sb.AppendLine("        private static readonly global::System.Text.Json.JsonSerializerOptions _jsonOptions = global::System.Text.Json.JsonSerializerOptions.NOF;");
        sb.AppendLine();
        sb.AppendLine($"        public {targetClass.Name}(global::System.Net.Http.HttpClient httpClient, global::NOF.Hosting.IRequestOutboundPipelineExecutor outboundPipeline, global::System.IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(httpClient);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(outboundPipeline);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(serviceProvider);");
        sb.AppendLine("            _httpClient = httpClient;");
        sb.AppendLine("            _outboundPipeline = outboundPipeline;");
        sb.AppendLine("            _serviceProvider = serviceProvider;");
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach (var method in methods)
        {
            var endpointInfo = RpcServiceHelpers.ExtractEndpointInfo(method);
            EmitHttpMethodBody(sb, method, endpointInfo);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{targetClass.ToDisplayString().Replace('.', '_')}.HttpServiceClient.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool TryGetRpcClientInterfaceFromHttpRpcClientAttribute(
        INamedTypeSymbol classSymbol,
        out INamedTypeSymbol? clientInterface,
        out INamedTypeSymbol? serviceInterface)
    {
        serviceInterface = null;
        if (!RpcServiceHelpers.TryGetRpcClientFromHttpRpcClientAttribute(classSymbol, out clientInterface)
            || clientInterface is null)
        {
            return false;
        }

        return RpcServiceHelpers.TryGetRpcServiceFromClientInterface(clientInterface, out serviceInterface);
    }

    private static List<ServiceMethodInfo> GetServiceMethods(INamedTypeSymbol iface)
    {
        var methods = new List<ServiceMethodInfo>();

        foreach (var member in iface.GetMembers())
        {
            if (member is not IMethodSymbol { MethodKind: MethodKind.Ordinary } method || method.IsImplicitlyDeclared)
            {
                continue;
            }

            if (!RpcServiceHelpers.TryGetRequestParameter(method, out var requestParam))
            {
                continue;
            }

            INamedTypeSymbol? requestType = null;
            if (requestParam != null)
            {
                if (requestParam.Type is not INamedTypeSymbol type)
                {
                    continue;
                }
                requestType = type;
            }

            if (!RpcServiceHelpers.TryGetServiceReturnInfo(method, out var returnInfo))
            {
                continue;
            }

            var operationName = method.Name;

            methods.Add(new ServiceMethodInfo
            {
                Method = method,
                RequestType = requestType,
                ReturnInfo = returnInfo,
                OperationName = operationName
            });
        }

        return methods;
    }

    private static void EmitHttpMethodBody(StringBuilder sb, ServiceMethodInfo method, EndpointInfo endpoint)
    {
        var responseType = endpoint.ReturnInfo.NormalizedResultTypeDisplay;
        var returnType = endpoint.ReturnInfo.ClientTaskReturnTypeDisplay;
        var methodName = method.Method.Name + "Async";
        var httpMethod = GetHttpMethod(endpoint.Method);
        var isBodyMethod = IsBodyMethod(endpoint.Method);
        var fqnHttpMethod = $"global::System.Net.Http.{httpMethod}";

        List<IPropertySymbol> allProperties = [];
        var routeParams = RpcServiceHelpers.ExtractRouteParameters(endpoint.Route);
        var routeParamProperties = new List<(string ParamName, IPropertySymbol Property)>();
        var nonRouteProperties = new List<IPropertySymbol>();

        if (endpoint.RequestType != null)
        {
            allProperties = RpcServiceHelpers.GetAllPublicProperties(endpoint.RequestType);
            foreach (var prop in allProperties)
            {
                var matchedParam = routeParams.FirstOrDefault(rp =>
                    string.Equals(rp, prop.Name, StringComparison.OrdinalIgnoreCase));
                if (matchedParam != null)
                {
                    routeParamProperties.Add((matchedParam, prop));
                }
                else
                {
                    nonRouteProperties.Add(prop);
                }
            }
        }

        var hasRouteParams = routeParamProperties.Count > 0;
        var hasRequestParam = endpoint.RequestType != null;

        if (hasRequestParam)
        {
            var requestType = endpoint.RequestType!.ToDisplayString();
            sb.AppendLine($"        public virtual async {returnType} {methodName}({requestType} request, global::System.Threading.CancellationToken cancellationToken = default)");
        }
        else
        {
            sb.AppendLine($"        public virtual async {returnType} {methodName}(global::System.Threading.CancellationToken cancellationToken = default)");
        }
        sb.AppendLine("        {");

        sb.AppendLine("            var context = new global::NOF.Hosting.RequestOutboundContext");
        sb.AppendLine("            {");
        if (hasRequestParam)
        {
            sb.AppendLine("                Message = request,");
        }
        else
        {
            sb.AppendLine("                Message = null,");
        }
        sb.AppendLine("                Services = _serviceProvider,");
        sb.AppendLine($"                ServiceType = typeof(global::{method.Method.ContainingType!.ToDisplayString()}),");
        sb.AppendLine($"                MethodName = \"{method.OperationName}\"");
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine($"            {responseType}? result = default;");
        sb.AppendLine();
        sb.AppendLine("            await _outboundPipeline.ExecuteAsync(context, async (ct) =>");
        sb.AppendLine("            {");

        if (hasRouteParams)
        {
            if (endpoint.RequestType != null)
            {
                var routeExpression = BuildRouteInterpolation(sb, endpoint.Route, routeParamProperties);
                sb.AppendLine($"                var endpoint = {routeExpression};");
            }
            else
            {
                sb.AppendLine($"                var endpoint = \"{endpoint.Route}\";");
            }
        }
        else
        {
            sb.AppendLine($"                var endpoint = \"{endpoint.Route}\";");
        }

        if (endpoint.RequestType != null)
        {
            var requestType = endpoint.RequestType.ToDisplayString();
            if (isBodyMethod)
            {
                if (hasRouteParams && nonRouteProperties.Count > 0)
                {
                    sb.AppendLine($"                var body = new global::System.Collections.Generic.Dictionary<string, object?>({nonRouteProperties.Count});");
                    foreach (var prop in nonRouteProperties)
                    {
                        sb.AppendLine($"                body[\"{prop.Name}\"] = request.{prop.Name};");
                    }
                    sb.AppendLine("                using var httpRequest = new global::System.Net.Http.HttpRequestMessage(" + fqnHttpMethod + ", endpoint);");
                    sb.AppendLine("                httpRequest.Content = global::System.Net.Http.Json.JsonContent.Create(body, options: _jsonOptions);");
                }
                else if (hasRouteParams && nonRouteProperties.Count == 0)
                {
                    sb.AppendLine("                using var httpRequest = new global::System.Net.Http.HttpRequestMessage(" + fqnHttpMethod + ", endpoint);");
                }
                else
                {
                    sb.AppendLine("                using var httpRequest = new global::System.Net.Http.HttpRequestMessage(" + fqnHttpMethod + ", endpoint);");
                    sb.AppendLine($"                httpRequest.Content = global::System.Net.Http.Json.JsonContent.Create(request, typeof({requestType}), options: _jsonOptions);");
                }
            }
            else
            {
                if (nonRouteProperties.Count > 0)
                {
                    sb.AppendLine("                var queryParts = new global::System.Collections.Generic.List<string>();");
                    foreach (var prop in nonRouteProperties)
                    {
                        EmitQueryParamAppend(sb, prop, indent: "                ");
                    }
                    sb.AppendLine("                if (queryParts.Count > 0)");
                    sb.AppendLine("                {");
                    sb.AppendLine("                    endpoint = endpoint + \"?\" + string.Join(\"&\", queryParts);");
                    sb.AppendLine("                }");
                }

                sb.AppendLine("                using var httpRequest = new global::System.Net.Http.HttpRequestMessage(" + fqnHttpMethod + ", endpoint);");
            }
        }
        else
        {
            sb.AppendLine("                using var httpRequest = new global::System.Net.Http.HttpRequestMessage(" + fqnHttpMethod + ", endpoint);");
        }

        sb.AppendLine();
        sb.AppendLine("                foreach (var kvp in context.Headers)");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (kvp.Value != null)");
        sb.AppendLine("                    {");
        sb.AppendLine("                        httpRequest.Headers.Remove(kvp.Key);");
        sb.AppendLine("                        httpRequest.Headers.TryAddWithoutValidation(kvp.Key, kvp.Value);");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.AppendLine($"                using var response = await _httpClient.SendAsync(httpRequest, ct).ConfigureAwait(false);");
        sb.AppendLine("                response.EnsureSuccessStatusCode();");
        sb.AppendLine();

        sb.AppendLine($"                var apiResponse = await global::System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync<{responseType}>(response.Content, _jsonOptions, ct);");
        sb.AppendLine("                result = apiResponse!;");
        sb.AppendLine("                context.Response = result;");

        sb.AppendLine("            }, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine();
        sb.AppendLine("            return result!;");

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitQueryParamAppend(StringBuilder sb, IPropertySymbol prop, string indent = "            ")
    {
        var indent1 = indent;
        var indent2 = indent + "    ";
        var propName = prop.Name;
        var isNullable = prop.Type.NullableAnnotation == NullableAnnotation.Annotated
                         || prop.Type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;

        if (isNullable)
        {
            sb.AppendLine($"{indent1}if (request.{propName} is not null)");
            sb.AppendLine($"{indent1}{{");
            sb.AppendLine($"{indent2}queryParts.Add(global::System.Uri.EscapeDataString(\"{propName}\") + \"=\" + global::System.Uri.EscapeDataString({FormatValueExpression($"request.{propName}", prop.Type, true)}));");
            sb.AppendLine($"{indent1}}}");
        }
        else
        {
            sb.AppendLine($"{indent1}queryParts.Add(global::System.Uri.EscapeDataString(\"{propName}\") + \"=\" + global::System.Uri.EscapeDataString({FormatValueExpression($"request.{propName}", prop.Type, false)}));");
        }
    }

    internal static string FormatValueExpression(string accessor, ITypeSymbol type, bool isNullable)
    {
        var underlying = type;
        var isNullableValueType = false;
        if (isNullable && type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } namedType)
        {
            underlying = namedType.TypeArguments[0];
            isNullableValueType = true;
        }

        var display = underlying.ToDisplayString();
        var valueAccessor = isNullableValueType ? $"{accessor}.Value" : accessor;

        return display switch
        {
            "System.DateTime" => $"{valueAccessor}.ToString(\"O\", global::System.Globalization.CultureInfo.InvariantCulture)",
            "System.DateTimeOffset" => $"{valueAccessor}.ToString(\"O\", global::System.Globalization.CultureInfo.InvariantCulture)",
            "System.DateOnly" => $"{valueAccessor}.ToString(\"yyyy-MM-dd\", global::System.Globalization.CultureInfo.InvariantCulture)",
            "System.TimeOnly" => $"{valueAccessor}.ToString(\"HH:mm:ss.FFFFFFF\", global::System.Globalization.CultureInfo.InvariantCulture)",
            "string" => isNullable ? $"{accessor}!" : accessor,
            _ => $"{accessor}.ToString()!"
        };
    }

    private static string BuildRouteInterpolation(StringBuilder sb, string route, List<(string ParamName, IPropertySymbol Property)> routeParamProperties)
    {
        var result = route;
        foreach (var (paramName, prop) in routeParamProperties)
        {
            var localVarName = $"__route_{paramName}__";
            var valueExpr = FormatValueExpression($"request.{prop.Name}", prop.Type, false);
            sb.AppendLine($"            var {localVarName} = global::System.Uri.EscapeDataString({valueExpr});");

            var pattern = "{" + paramName + "}";
            var replacement = $"{{{localVarName}}}";
            var idx = result.IndexOf(pattern, StringComparison.OrdinalIgnoreCase);
            if (idx >= 0)
            {
                result = result.Substring(0, idx) + replacement + result.Substring(idx + pattern.Length);
            }
        }

        return "$\"" + result + "\"";
    }

    private static string GetHttpMethod(HttpVerb verb) => verb switch
    {
        HttpVerb.Get => "HttpMethod.Get",
        HttpVerb.Post => "HttpMethod.Post",
        HttpVerb.Put => "HttpMethod.Put",
        HttpVerb.Delete => "HttpMethod.Delete",
        HttpVerb.Patch => "HttpMethod.Patch",
        _ => throw new ArgumentOutOfRangeException(nameof(verb), verb, null)
    };

    private static bool IsBodyMethod(HttpVerb verb)
        => verb == HttpVerb.Post || verb == HttpVerb.Put || verb == HttpVerb.Patch;
}
