name: Bug Report
description: Report a bug in the NOF framework.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below so we can reproduce and fix the issue.

  - type: input
    id: package
    attributes:
      label: Affected Package(s)
      description: Which NOF NuGet package(s) are affected?
      placeholder: "e.g. NOF.Infrastructure.Core, NOF.Hosting.AspNetCore"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: The version of the affected package(s).
      placeholder: "e.g. 6.5.2"
    validations:
      required: true

  - type: input
    id: dotnet-version
    attributes:
      label: .NET Version
      description: The target .NET version of your project.
      placeholder: "e.g. net10.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: Minimal steps or code snippet to reproduce the issue.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include stack traces or error messages if applicable.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or log output.
    validations:
      required: false
