name: Feature Request
description: Suggest a new feature or enhancement for the NOF framework.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe the feature you'd like to see.

  - type: input
    id: package
    attributes:
      label: Related Package(s)
      description: Which NOF package(s) would this feature apply to? Leave blank if it's a new package or cross-cutting.
      placeholder: "e.g. NOF.Application, NOF.Infrastructure.Core"
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration with the current API?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the API or behavior you'd like. Include code snippets if possible.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches you've considered.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, diagrams, or references.
    validations:
      required: false
