// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NOF.Sample;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NOF.Sample.Migrations.Tenant
{
    [DbContext(typeof(ConfigurationDbContext))]
    [Migration("20260208072058_RefactorEfCoreMultiTenant")]
    partial class RefactorEfCoreMultiTenant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NOF.EFCoreInboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("EFCoreInboxMessage");
                });

            modelBuilder.Entity("NOF.EFCoreOutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ClaimExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationEndpointName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpanId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimedBy");

                    b.HasIndex("TraceId");

                    b.HasIndex("Status", "ClaimExpiresAt");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("EFCoreOutboxMessage");
                });

            modelBuilder.Entity("NOF.EFCoreStateMachineContext", b =>
                {
                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<string>("DefinitionType")
                        .HasColumnType("text");

                    b.Property<string>("ContextData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextType")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("CorrelationId", "DefinitionType");

                    b.ToTable("EFCoreStateMachineContext");
                });

            modelBuilder.Entity("NOF.EFCoreTenant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EFCoreTenant");
                });

            modelBuilder.Entity("NOF.Sample.Application.Entities.ConfigNodeChildren", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<long>>("ChildrenIds")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.HasKey("NodeId");

                    b.ToTable("ConfigNodeChildren", (string)null);
                });

            modelBuilder.Entity("NOF.Sample.ConfigNode", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ActiveFileName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ConfigNode", (string)null);
                });

            modelBuilder.Entity("NOF.Sample.ConfigNode", b =>
                {
                    b.OwnsMany("NOF.Sample.ConfigFile", "_configFiles", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<long>("NodeId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("NodeId");

                            b1.ToTable("ConfigFile", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("NodeId");
                        });

                    b.Navigation("_configFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
