// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NOF.Sample;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NOF.Sample.Migrations
{
    [DbContext(typeof(ConfigurationDbContext))]
    [Migration("20260504122750_NOFv10.3.0")]
    partial class NOFv1030
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NOF.Application.NOFStateMachineContext", b =>
                {
                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<string>("DefinitionTypeName")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("CorrelationId", "DefinitionTypeName");

                    b.ToTable("NOFStateMachineContext", (string)null);

                    b.HasAnnotation("NOF:HostOnly", true);
                });

            modelBuilder.Entity("NOF.Infrastructure.Extension.Authorization.Jwt.PersistedSigningKey", b =>
                {
                    b.Property<string>("Kid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedPrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InvalidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Kid");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.HasIndex("Status", "InvalidatedAtUtc");

                    b.ToTable("PersistedSigningKey", (string)null);

                    b.HasAnnotation("NOF:HostOnly", true);
                });

            modelBuilder.Entity("NOF.Infrastructure.Extension.Authorization.Jwt.RevokedRefreshToken", b =>
                {
                    b.Property<string>("TokenId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TokenId");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("RevokedRefreshToken", (string)null);

                    b.HasAnnotation("NOF:HostOnly", true);
                });

            modelBuilder.Entity("NOF.Infrastructure.NOFInboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("HandlerType")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("ClaimExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id", "HandlerType");

                    b.HasIndex("ClaimedBy");

                    b.HasIndex("Status", "ClaimExpiresAtUtc");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("NOFInboxMessage", (string)null);

                    b.HasAnnotation("NOF:HostOnly", true);
                });

            modelBuilder.Entity("NOF.Infrastructure.NOFOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClaimExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DispatchTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClaimedBy");

                    b.HasIndex("Status", "ClaimExpiresAtUtc");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("NOFOutboxMessage", (string)null);

                    b.HasAnnotation("NOF:HostOnly", true);
                });

            modelBuilder.Entity("NOF.Infrastructure.NOFTenant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NOFTenant", (string)null);

                    b.HasAnnotation("NOF:HostOnly", true);
                });

            modelBuilder.Entity("NOF.Sample.Application.Entities.ConfigNodeChildren", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<long>>("ChildrenIds")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.HasKey("NodeId");

                    b.ToTable("ConfigNodeChildren", (string)null);
                });

            modelBuilder.Entity("NOF.Sample.ConfigNode", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ActiveFileName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ConfigNode", (string)null);
                });

            modelBuilder.Entity("NOF.Infrastructure.NOFOutboxMessage", b =>
                {
                    b.OwnsOne("NOF.Infrastructure.TracingInfo", "ParentTracingInfo", b1 =>
                        {
                            b1.Property<Guid>("NOFOutboxMessageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SpanId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("SpanId");

                            b1.Property<string>("TraceId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("TraceId");

                            b1.HasKey("NOFOutboxMessageId");

                            b1.HasIndex("TraceId");

                            b1.ToTable("NOFOutboxMessage");

                            b1.WithOwner()
                                .HasForeignKey("NOFOutboxMessageId");
                        });

                    b.Navigation("ParentTracingInfo");
                });

            modelBuilder.Entity("NOF.Sample.ConfigNode", b =>
                {
                    b.OwnsMany("NOF.Sample.ConfigFile", "ConfigFiles", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<long>("NodeId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("NodeId");

                            b1.ToTable("ConfigFile", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("NodeId");
                        });

                    b.Navigation("ConfigFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
