using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF;

/// <summary>
/// 源生成器：检测标记了PermissionAttribute的常量字段，并生成PermissionInfo注册代码
/// </summary>
[Generator]
public class PermissionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 获取所有带有PermissionAttribute的字段
        var fieldDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        // 注册输出生成
        context.RegisterSourceOutput(fieldDeclarations.Collect(), static (spc, source) => Execute(source, spc));
    }

    /// <summary>
    /// 判断语法节点是否是生成目标
    /// </summary>
    private static bool IsSyntaxTargetForGeneration(SyntaxNode node) =>
        node is FieldDeclarationSyntax { AttributeLists.Count: > 0 };

    /// <summary>
    /// 获取语义模型目标
    /// </summary>
    private static FieldInfo GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        // 获取字段声明
        var fieldDeclaration = (FieldDeclarationSyntax)context.Node;

        // 检查字段是否有PermissionAttribute
        foreach (var fieldSymbol in fieldDeclaration.Declaration.Variables
                     .Select(variable => context.SemanticModel.GetDeclaredSymbol(variable) as IFieldSymbol))
        {
            if (fieldSymbol is null)
            {
                return null!;
            }

            // 检查是否有PermissionAttribute
            var permissionAttribute = fieldSymbol.GetAttributes()
                .FirstOrDefault(attr => attr.AttributeClass?.ToDisplayString() == "NOF.PermissionAttribute");

            if (permissionAttribute is null)
            {
                continue;
            }

            var description = string.Empty;
            if (permissionAttribute.ConstructorArguments.Length > 0)
            {
                description = permissionAttribute.ConstructorArguments[0].Value?.ToString() ?? string.Empty;
            }

            var containingType = fieldSymbol.ContainingType;
            var containingNamespace = containingType.ContainingNamespace.ToDisplayString();

            return new FieldInfo
            {
                FieldName = fieldSymbol.Name,
                Description = description,
                ContainingTypeName = containingType.Name,
                ContainingNamespace = containingNamespace,
                IsStatic = fieldSymbol.IsStatic,
                IsConst = fieldSymbol.IsConst
            };
        }

        return null!;
    }

    /// <summary>
    /// 执行代码生成
    /// </summary>
    private static void Execute(ImmutableArray<FieldInfo> fields, SourceProductionContext context)
    {
        if (fields.IsDefaultOrEmpty)
        {
            return;
        }

        // 过滤出静态或常量字段
        var validFields = fields
            .Where(f => f.IsStatic || f.IsConst)
            .ToList();

        if (validFields.Count == 0)
        {
            return;
        }

        // 生成统一的权限信息类
        var source = GenerateUnifiedPermissionInfoClass(validFields);
        context.AddSource("GeneratedPermissions.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    /// <summary>
    /// 生成统一的权限信息类
    /// </summary>
    private static string GenerateUnifiedPermissionInfoClass(List<FieldInfo> fields)
    {
        var ns = fields.First().ContainingNamespace;
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using NOF;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 自动生成的统一权限信息类");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class GeneratedPermissions");
        sb.AppendLine("    {");

        // 生成单个权限信息属性
        foreach (var field in fields)
        {
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// {field.Description}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public static PermissionInfo {field.FieldName}Info {{ get; }} = new PermissionInfo({field.ContainingTypeName}.{field.FieldName}, \"{field.Description}\");");
            sb.AppendLine();
        }

        // 生成获取所有权限信息的方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取所有权限信息");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static List<PermissionInfo> GetAllPermissions()");
        sb.AppendLine("        {");
        sb.AppendLine("            return new List<PermissionInfo>");
        sb.AppendLine("            {");

        foreach (var field in fields)
        {
            sb.AppendLine($"                {field.FieldName}Info,");
        }

        sb.AppendLine("            };");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// 字段信息
    /// </summary>
    private class FieldInfo
    {
        public string FieldName { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string ContainingTypeName { get; set; } = string.Empty;
        public string ContainingNamespace { get; set; } = string.Empty;
        public bool IsStatic { get; set; }
        public bool IsConst { get; set; }
    }
}
