using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF;

/// <summary>
/// 源生成器：检测标记了QueryParameterAttribute的类，并生成ToQueryString扩展方法
/// </summary>
[Generator]
public class QueryParameterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 获取所有带有QueryParameterAttribute的类
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        // 将语法和语义模型组合起来
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        // 注册源代码输出
        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    /// <summary>
    /// 判断语法节点是否是我们要处理的目标
    /// </summary>
    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        // 处理类、记录和结构体声明
        return node is TypeDeclarationSyntax typeDeclaration
            // 确保类型有特性列表
            && typeDeclaration.AttributeLists.Count > 0;
    }

    /// <summary>
    /// 获取语义模型中的目标类型
    /// </summary>
    private static TypeDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        // 获取类型声明语法节点（类、记录或结构体）
        var typeDeclaration = (TypeDeclarationSyntax)context.Node;

        // 获取类型的符号信息
        var typeSymbol = context.SemanticModel.GetDeclaredSymbol(typeDeclaration);
        if (typeSymbol is null)
            return null;

        // 检查类型是否标记了QueryParameterAttribute
        var hasAttribute = typeSymbol.GetAttributes()
            .Any(attr => attr.AttributeClass?.ToDisplayString() == "NOF.QueryParameterAttribute");

        return hasAttribute ? typeDeclaration : null;
    }

    /// <summary>
    /// 生成源代码
    /// </summary>
    private static void Execute(Compilation compilation, ImmutableArray<TypeDeclarationSyntax?> types, SourceProductionContext context)
    {
        if (types.IsDefaultOrEmpty)
        {
            return;
        }

        foreach (var typeDeclaration in types)
        {
            if (typeDeclaration is null)
            {
                continue;
            }
            var semanticModel = compilation.GetSemanticModel(typeDeclaration.SyntaxTree);
            var typeSymbol = semanticModel.GetDeclaredSymbol(typeDeclaration);
            if (typeSymbol is null)
                continue;

            var typeName = typeSymbol.Name;
            var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();

            // 确定类型关键字
            var typeKeyword = GetTypeKeyword(typeDeclaration);

            // 获取所有公共属性，包括继承的属性
            var properties = GetAllProperties(typeSymbol)
                .Where(p => p.DeclaredAccessibility == Accessibility.Public)
                .ToList();

            var source = GenerateExtensionMethod(namespaceName, typeName, typeKeyword, properties);

            context.AddSource($"{typeName}.QueryParameter.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    /// <summary>
    /// 获取类型关键字
    /// </summary>
    private static string GetTypeKeyword(TypeDeclarationSyntax typeDeclaration)
    {
        return typeDeclaration switch
        {
            RecordDeclarationSyntax record => record.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword) ? "record struct" : "record",
            StructDeclarationSyntax => "struct",
            ClassDeclarationSyntax => "class",
            _ => "class"
        };
    }

    /// <summary>
    /// 生成实例方法代码
    /// </summary>
    private static string GenerateExtensionMethod(string namespaceName, string typeName, string typeKeyword, List<IPropertySymbol> properties)
    {
        var sb = new StringBuilder();

        // 添加必要的命名空间引用
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using NOF;");
        sb.AppendLine();

        // 生成命名空间
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// {typeName}的查询参数部分类型");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public partial {typeKeyword} {typeName} : IQueryParameter");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 将对象转换为URL查询字符串");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <returns>URL查询字符串，如果有参数则以?开头</returns>");
        sb.AppendLine("        public string ToQueryString(JsonSerializerOptions? jsonOptions = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            jsonOptions ??= DefaultJsonSerializerOptions.Options;");
        sb.AppendLine("            var queryParams = new Dictionary<string, string>();");
        sb.AppendLine();

        // 为每个属性生成查询参数代码
        foreach (var property in properties)
        {
            GeneratePropertyQueryCode(sb, property);
        }

        // 调用 ConfigureQueryString 方法
        sb.AppendLine();
        sb.AppendLine("            IQueryParameter instance = this;");
        sb.AppendLine("            instance.ConfigureQueryString(queryParams);");
        sb.AppendLine();
        sb.AppendLine("            var queryStringParts = new List<string>();");
        sb.AppendLine("            foreach (var param in queryParams)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (string.IsNullOrEmpty(param.Value))");
        sb.AppendLine("                {");
        sb.AppendLine("                    continue;");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.AppendLine("                var escapedKey = Uri.EscapeDataString(param.Key);");
        sb.AppendLine("                var escapedValue = Uri.EscapeDataString(param.Value);");
        sb.AppendLine("                queryStringParts.Add($\"{escapedKey}={escapedValue}\");");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return queryStringParts.Count > 0 ? \"?\" + string.Join(\"&\", queryStringParts) : \"\";");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// 为属性生成查询参数代码
    /// </summary>
    private static void GeneratePropertyQueryCode(StringBuilder sb, IPropertySymbol property)
    {
        var propertyName = property.Name;
        var propertyType = property.Type;

        sb.AppendLine();

        // 可空值类型
        if (IsNullableValueType(propertyType))
        {
            sb.AppendLine($"            if ({propertyName}.HasValue)");
            sb.AppendLine("            {");
            sb.AppendLine($"                queryParams[\"{propertyName}\"] = JsonSerializer.Serialize({propertyName}.Value, jsonOptions).Trim('\"');");
            sb.AppendLine("            }");
        }
        // 字符串
        else if (IsStringType(propertyType))
        {
            sb.AppendLine($"            if (!string.IsNullOrEmpty({propertyName}))");
            sb.AppendLine("            {");
            sb.AppendLine($"                queryParams[\"{propertyName}\"] = {propertyName}; // 字符串不需要序列化");
            sb.AppendLine("            }");
        }
        // 集合
        else if (IsCollectionType(propertyType))
        {
            sb.AppendLine($"            if ({propertyName} is not null && {propertyName}.Any())");
            sb.AppendLine("            {");
            sb.AppendLine($"                queryParams[\"{propertyName}\"] = JsonSerializer.Serialize({propertyName}, jsonOptions); // 集合序列化为 [1,2,3]");
            sb.AppendLine("            }");
        }
        // 布尔值
        else if (IsBooleanType(propertyType))
        {
            sb.AppendLine($"            queryParams[\"{propertyName}\"] = {propertyName}.ToString().ToLower();");
        }
        // 引用类型（对象、类等）
        else if (IsReferenceTypeOrNullable(propertyType))
        {
            sb.AppendLine($"            if ({propertyName} is not null)");
            sb.AppendLine("            {");
            sb.AppendLine($"                queryParams[\"{propertyName}\"] = JsonSerializer.Serialize({propertyName}, jsonOptions).Trim('\"');");
            sb.AppendLine("            }");
        }
        // 其他值类型（int, enum, DateTime 等）
        else
        {
            sb.AppendLine($"            queryParams[\"{propertyName}\"] = JsonSerializer.Serialize({propertyName}, jsonOptions).Trim('\"');");
        }
    }

    /// <summary>
    /// 判断是否为可空值类型（如 int?）
    /// </summary>
    private static bool IsNullableValueType(ITypeSymbol type)
        => type is INamedTypeSymbol { IsGenericType: true } namedType &&
           namedType.ConstructedFrom.ToDisplayString() == "System.Nullable<T>";

    /// <summary>
    /// 判断是否为引用类型或带有可空注释的引用类型
    /// </summary>
    private static bool IsReferenceTypeOrNullable(ITypeSymbol type)
        => (type is { IsReferenceType: true } && !IsStringType(type)) ||
           (type is { IsReferenceType: true, NullableAnnotation: NullableAnnotation.Annotated } && !IsStringType(type));

    /// <summary>
    /// 判断是否为字符串类型
    /// </summary>
    private static bool IsStringType(ITypeSymbol type)
        => type.SpecialType == SpecialType.System_String;

    /// <summary>
    /// 判断是否为集合类型
    /// </summary>
    private static bool IsCollectionType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType)
        {
            return namedType.AllInterfaces.Any(i =>
                i.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.IEnumerable<T>" &&
                i.TypeArguments.Length == 1);
        }
        return false;
    }

    /// <summary>
    /// 判断是否为布尔类型
    /// </summary>
    private static bool IsBooleanType(ITypeSymbol type)
        => type.SpecialType == SpecialType.System_Boolean;

    /// <summary>
    /// 获取类型的所有属性，包括继承的属性
    /// </summary>
    private static IEnumerable<IPropertySymbol> GetAllProperties(ISymbol classSymbol)
    {
        if (classSymbol is not INamedTypeSymbol currentType)
        {
            yield break;
        }

        var allProperties = new Dictionary<string, IPropertySymbol>();

        var baseTypes = new List<INamedTypeSymbol>();
        var type = currentType;

        while (type is not null && type.SpecialType != SpecialType.System_Object)
        {
            baseTypes.Add(type);
            type = type.BaseType;
        }

        baseTypes.Reverse();
        foreach (var member in baseTypes.SelectMany(namedType => namedType.GetMembers().Where(m => m.Kind == SymbolKind.Property)))
        {
            if (member is IPropertySymbol property)
            {
                allProperties[property.Name] = property;
            }
        }

        foreach (var property in allProperties.Values)
        {
            yield return property;
        }
    }
}
