using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Application.SourceGenerator;

/// <summary>
/// Source generator: detects handler classes implementing ICommandHandler, IEventHandler,
/// INotificationHandler in the current project and generates assembly initializer metadata.
/// </summary>
[Generator]
public class HandlerRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sourceClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) =>
                {
                    if (ctx.Node is not ClassDeclarationSyntax cds)
                    {
                        return null;
                    }
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(cds) as INamedTypeSymbol;
                    if (symbol is { IsAbstract: false, IsGenericType: false } && !IsStateMachineHandler(symbol) && IsHandlerType(symbol))
                    {
                        return symbol;
                    }
                    return null;
                })
            .Where(static s => s is not null);

        var allTypesWithAssembly = context.CompilationProvider
            .Combine(sourceClasses.Collect())
            .Select(static (data, _) =>
            {
                var (compilation, fromSource) = data;
                var set = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
                foreach (var t in Enumerable.OfType<INamedTypeSymbol>(fromSource))
                {
                    set.Add(t);
                }
                var assemblyName = compilation.AssemblyName ?? "Unknown";
                return (AssemblyName: assemblyName, Types: set.ToImmutableArray());
            });

        context.RegisterSourceOutput(allTypesWithAssembly, static (spc, data) =>
        {
            if (data.Types.IsEmpty)
            {
                return;
            }

            var source = GenerateHandlerAssemblyInitializer(data.AssemblyName, data.Types);
            if (string.IsNullOrWhiteSpace(source))
            {
                return;
            }
            spc.AddSource("HandlerAssemblyInitializer.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static bool IsStateMachineHandler(INamedTypeSymbol symbol)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            if (current.IsGenericType &&
                current.OriginalDefinition.ToDisplayString() == "NOF.Application.StateMachineNotificationHandler<TStateMachineDefinition, TState, TNotification>")
            {
                return true;
            }
            current = current.BaseType;
        }
        return false;
    }

    private static bool IsHandlerType(INamedTypeSymbol symbol)
    {
        foreach (var iface in symbol.AllInterfaces)
        {
            if (!iface.IsGenericType)
            {
                continue;
            }
            var display = iface.OriginalDefinition.ToDisplayString();
            if (display == "NOF.Application.ICommandHandler<TCommand>" ||
                display == "NOF.Application.IEventHandler<TEvent>" ||
                display == "NOF.Application.INotificationHandler<TNotification>")
            {
                return true;
            }
        }
        return false;
    }

    private static string GenerateHandlerAssemblyInitializer(string assemblyName, ImmutableArray<INamedTypeSymbol> handlerClasses)
    {
        var sanitizedName = assemblyName.Replace(".", "");
        var initializerTypeName = $"__{sanitizedName}HandlerAssemblyInitializer";
        var typeFormat = SymbolDisplayFormat.FullyQualifiedFormat
            .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Included);

        var registrations = new List<string>();
        foreach (var handlerClass in handlerClasses)
        {
            CollectHandlerRegistrations(registrations, handlerClass, typeFormat);
        }

        if (registrations.Count == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("[assembly: global::NOF.Annotation.AssemblyInitializeAttribute<global::" + assemblyName + "." + initializerTypeName + ">]");
        sb.AppendLine();
        sb.AppendLine($"namespace {assemblyName}");
        sb.AppendLine("{");
        sb.AppendLine($"    internal sealed class {initializerTypeName} : global::NOF.Annotation.IAssemblyInitializer");
        sb.AppendLine("    {");
        sb.AppendLine("        private static int _initialized;");
        sb.AppendLine();
        sb.AppendLine("        public static void Initialize()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (global::System.Threading.Interlocked.Exchange(ref _initialized, 1) == 1)");
        sb.AppendLine("            {");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine();

        foreach (var registration in registrations)
        {
            sb.AppendLine($"            global::NOF.Application.HandlerRegistry.Register({registration});");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void CollectHandlerRegistrations(
        List<string> registrations,
        INamedTypeSymbol handlerClass,
        SymbolDisplayFormat typeFormat)
    {
        var handlerTypeName = handlerClass.ToDisplayString(typeFormat);

        foreach (var iface in handlerClass.AllInterfaces)
        {
            if (!iface.IsGenericType)
            {
                continue;
            }

            var display = iface.OriginalDefinition.ToDisplayString();

            if (display == "NOF.Application.ICommandHandler<TCommand>")
            {
                var messageType = iface.TypeArguments[0].ToDisplayString(typeFormat);
                registrations.Add($"new global::NOF.Application.CommandHandlerInfo(typeof({handlerTypeName}), typeof({messageType}))");
            }
            else if (display == "NOF.Application.IEventHandler<TEvent>")
            {
                var messageType = iface.TypeArguments[0].ToDisplayString(typeFormat);
                registrations.Add($"new global::NOF.Application.EventHandlerInfo(typeof({handlerTypeName}), typeof({messageType}))");
            }
            else if (display == "NOF.Application.INotificationHandler<TNotification>")
            {
                var messageType = iface.TypeArguments[0].ToDisplayString(typeFormat);
                registrations.Add($"new global::NOF.Application.NotificationHandlerInfo(typeof({handlerTypeName}), typeof({messageType}))");
            }
        }
    }
}
