using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Application.SourceGenerator;

/// <summary>
/// Source generator: detects handler classes inheriting CommandHandler
/// and NotificationHandler in the current project and generates assembly initializer metadata.
/// </summary>
[Generator]
public class HandlerRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sourceClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) =>
                {
                    if (ctx.Node is not ClassDeclarationSyntax cds)
                    {
                        return null;
                    }
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(cds) as INamedTypeSymbol;
                    if (symbol is { IsAbstract: false, IsGenericType: false } && !IsStateMachineHandler(symbol) && IsHandlerType(symbol))
                    {
                        return symbol;
                    }
                    return null;
                })
            .Where(static s => s is not null);

        var allTypesWithAssembly = context.CompilationProvider
            .Combine(sourceClasses.Collect())
            .Select(static (data, _) =>
            {
                var (compilation, fromSource) = data;
                var set = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
                foreach (var t in Enumerable.OfType<INamedTypeSymbol>(fromSource))
                {
                    set.Add(t);
                }
                var assemblyName = compilation.AssemblyName ?? "Unknown";
                return (AssemblyName: assemblyName, Types: set.ToImmutableArray());
            });

        context.RegisterSourceOutput(allTypesWithAssembly, static (spc, data) =>
        {
            if (data.Types.IsEmpty)
            {
                return;
            }

            var source = GenerateHandlerAssemblyInitializer(data.AssemblyName, data.Types);
            if (!string.IsNullOrWhiteSpace(source))
            {
                spc.AddSource("HandlerAssemblyInitializer.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private static bool IsStateMachineHandler(INamedTypeSymbol symbol)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            if (current.IsGenericType &&
                current.OriginalDefinition.ToDisplayString() == "NOF.Application.StateMachineNotificationHandler<TStateMachineDefinition, TState, TNotification>")
            {
                return true;
            }
            current = current.BaseType;
        }
        return false;
    }

    private static bool IsHandlerType(INamedTypeSymbol symbol)
    {
        return TryGetHandledMessageType(symbol, "NOF.Application.CommandHandler<TCommand>", out _)
            || TryGetHandledMessageType(symbol, "NOF.Application.NotificationHandler<TNotification>", out _);
    }

    private static string GenerateHandlerAssemblyInitializer(string assemblyName, ImmutableArray<INamedTypeSymbol> handlerClasses)
    {
        var registrations = new List<string>();
        var invokerDefinitions = new List<string>();
        var typeFormat = SymbolDisplayFormat.FullyQualifiedFormat
            .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Included);

        foreach (var handlerClass in handlerClasses)
        {
            CollectHandlerRegistrations(registrations, invokerDefinitions, handlerClass, typeFormat);
        }

        return GenerateAssemblyInitializerSource(
            assemblyName,
            $"__{assemblyName.Replace(".", "")}HandlerAssemblyInitializer",
            registrations,
            invokerDefinitions);
    }

    private static string GenerateAssemblyInitializerSource(
        string assemblyName,
        string initializerTypeName,
        List<string> registrations,
        IReadOnlyList<string> invokerDefinitions)
    {
        if (registrations.Count == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("[assembly: global::NOF.Abstraction.AssemblyInitializeAttribute<global::" + assemblyName + "." + initializerTypeName + ">]");
        sb.AppendLine();
        sb.AppendLine($"namespace {assemblyName}");
        sb.AppendLine("{");
        sb.AppendLine($"    internal sealed class {initializerTypeName} : global::NOF.Abstraction.IAssemblyInitializer");
        sb.AppendLine("    {");
        sb.AppendLine("        public static void Initialize(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (!services.InitializedTypes.Add(typeof({initializerTypeName})))");
        sb.AppendLine("            {");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine();

        foreach (var registration in registrations)
        {
            sb.AppendLine($"            {registration};");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        foreach (var invokerDefinition in invokerDefinitions)
        {
            sb.AppendLine();
            sb.Append(invokerDefinition);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void CollectHandlerRegistrations(
        List<string> registrations,
        List<string> invokerDefinitions,
        INamedTypeSymbol handlerClass,
        SymbolDisplayFormat typeFormat)
    {
        var handlerTypeName = handlerClass.ToDisplayString(typeFormat);
        registrations.Add($"services.ReplaceOrAdd(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Transient(typeof({handlerTypeName}), typeof({handlerTypeName})))");

        if (TryGetHandledMessageType(handlerClass, "NOF.Application.CommandHandler<TCommand>", out var commandType))
        {
            var messageType = commandType!.ToDisplayString(typeFormat);
            var invokerTypeName = $"__{SanitizeIdentifier(TrimGlobalAlias(handlerTypeName))}CommandInboundInvoker";
            registrations.Add($"services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(typeof({invokerTypeName}), typeof({invokerTypeName})))");
            registrations.Add($"services.GetOrAddSingleton<global::NOF.Application.CommandHandlerRegistry>().Add(new global::NOF.Application.CommandHandlerRegistration(typeof({handlerTypeName}), typeof({messageType}), typeof({invokerTypeName})))");
            invokerDefinitions.Add(GenerateCommandInvokerSource(invokerTypeName, handlerTypeName, messageType));
        }

        if (TryGetHandledMessageType(handlerClass, "NOF.Application.NotificationHandler<TNotification>", out var notificationType))
        {
            var messageType = notificationType!.ToDisplayString(typeFormat);
            var invokerTypeName = $"__{SanitizeIdentifier(TrimGlobalAlias(handlerTypeName))}NotificationInboundInvoker";
            registrations.Add($"services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(typeof({invokerTypeName}), typeof({invokerTypeName})))");
            registrations.Add($"services.GetOrAddSingleton<global::NOF.Application.NotificationHandlerRegistry>().Add(new global::NOF.Application.NotificationHandlerRegistration(typeof({handlerTypeName}), typeof({messageType}), typeof({invokerTypeName})))");
            invokerDefinitions.Add(GenerateNotificationInvokerSource(invokerTypeName, handlerTypeName, messageType));
        }
    }

    private static string TrimGlobalAlias(string typeName)
        => typeName.Replace("global::", string.Empty);

    private static string EscapeStringLiteral(string value)
        => value.Replace("\\", "\\\\")
            .Replace("\"", "\\\"");

    private static string SanitizeIdentifier(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        return sb.ToString();
    }

    private static string GenerateCommandInvokerSource(
        string invokerTypeName,
        string handlerTypeExpression,
        string messageTypeExpression)
    {
        var handlerTypeName = EscapeStringLiteral(TrimGlobalAlias(handlerTypeExpression));
        var messageTypeName = EscapeStringLiteral(TrimGlobalAlias(messageTypeExpression));
        var sb = new StringBuilder();
        sb.AppendLine($"    internal sealed class {invokerTypeName} : global::NOF.Application.ICommandInboundHandlerInvoker");
        sb.AppendLine("    {");
        sb.AppendLine($"        public string HandlerTypeName => \"{handlerTypeName}\";");
        sb.AppendLine($"        public global::System.Type HandlerType => typeof({handlerTypeExpression});");
        sb.AppendLine($"        public string MessageTypeName => \"{messageTypeName}\";");
        sb.AppendLine($"        public global::System.Type MessageType => typeof({messageTypeExpression});");
        sb.AppendLine();
        sb.AppendLine("        public object Bind(");
        sb.AppendLine("            string payloadTypeName,");
        sb.AppendLine("            global::System.ReadOnlyMemory<byte> payload,");
        sb.AppendLine("            global::System.Func<global::System.ReadOnlyMemory<byte>, global::System.Type, object?> deserialize)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentException.ThrowIfNullOrWhiteSpace(payloadTypeName);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(deserialize);");
        sb.AppendLine($"            if (!global::System.String.Equals(payloadTypeName, \"{messageTypeName}\", global::System.StringComparison.Ordinal))");
        sb.AppendLine("            {");
        sb.AppendLine($"                throw new global::System.InvalidOperationException(\"Payload type '\" + payloadTypeName + \"' does not match handler message type '{messageTypeName}'.\");");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine($"            return deserialize(payload, typeof({messageTypeExpression}))");
        sb.AppendLine($"                ?? throw new global::System.InvalidOperationException(\"Failed to deserialize message payload as '{messageTypeName}'.\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Threading.Tasks.ValueTask InvokeAsync(");
        sb.AppendLine("            global::System.IServiceProvider services,");
        sb.AppendLine("            object message,");
        sb.AppendLine("            global::NOF.Contract.Context context,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(services);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(message);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine($"            var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{handlerTypeExpression}>(services);");
        sb.AppendLine($"            return new global::System.Threading.Tasks.ValueTask(handler.HandleAsync(({messageTypeExpression})message, context, cancellationToken));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        return sb.ToString();
    }

    private static string GenerateNotificationInvokerSource(
        string invokerTypeName,
        string handlerTypeExpression,
        string messageTypeExpression)
    {
        var handlerTypeName = EscapeStringLiteral(TrimGlobalAlias(handlerTypeExpression));
        var messageTypeName = EscapeStringLiteral(TrimGlobalAlias(messageTypeExpression));
        var sb = new StringBuilder();
        sb.AppendLine($"    internal sealed class {invokerTypeName} : global::NOF.Application.INotificationInboundHandlerInvoker");
        sb.AppendLine("    {");
        sb.AppendLine($"        public string HandlerTypeName => \"{handlerTypeName}\";");
        sb.AppendLine($"        public global::System.Type HandlerType => typeof({handlerTypeExpression});");
        sb.AppendLine($"        public string MessageTypeName => \"{messageTypeName}\";");
        sb.AppendLine($"        public global::System.Type MessageType => typeof({messageTypeExpression});");
        sb.AppendLine();
        sb.AppendLine("        public object Bind(");
        sb.AppendLine("            string payloadTypeName,");
        sb.AppendLine("            global::System.ReadOnlyMemory<byte> payload,");
        sb.AppendLine("            global::System.Func<global::System.ReadOnlyMemory<byte>, global::System.Type, object?> deserialize)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentException.ThrowIfNullOrWhiteSpace(payloadTypeName);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(deserialize);");
        sb.AppendLine($"            if (!global::System.String.Equals(payloadTypeName, \"{messageTypeName}\", global::System.StringComparison.Ordinal))");
        sb.AppendLine("            {");
        sb.AppendLine($"                throw new global::System.InvalidOperationException(\"Payload type '\" + payloadTypeName + \"' does not match handler message type '{messageTypeName}'.\");");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine($"            return deserialize(payload, typeof({messageTypeExpression}))");
        sb.AppendLine($"                ?? throw new global::System.InvalidOperationException(\"Failed to deserialize message payload as '{messageTypeName}'.\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Threading.Tasks.ValueTask InvokeAsync(");
        sb.AppendLine("            global::System.IServiceProvider services,");
        sb.AppendLine("            object message,");
        sb.AppendLine("            global::NOF.Contract.Context context,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(services);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(message);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine($"            var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{handlerTypeExpression}>(services);");
        sb.AppendLine($"            return new global::System.Threading.Tasks.ValueTask(handler.HandleAsync(({messageTypeExpression})message, context, cancellationToken));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        return sb.ToString();
    }

    private static bool TryGetHandledMessageType(INamedTypeSymbol symbol, string handlerBaseType, out ITypeSymbol? messageType)
    {
        messageType = null;

        var current = symbol.BaseType;
        while (current is not null)
        {
            if (current.IsGenericType
                && current.OriginalDefinition.ToDisplayString() == handlerBaseType)
            {
                messageType = current.TypeArguments[0];
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }
}
