using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Application.SourceGenerator;

[Generator]
public sealed class RpcServerAutoInjectGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sourceClasses = context.SyntaxProvider
            .CreateSyntaxProvider<ImmutableArray<RegistrationInfo>>(
                static (node, _) => node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 },
                static (ctx, _) =>
                {
                    if (ctx.Node is not ClassDeclarationSyntax classDeclaration
                        || ctx.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol
                        || classSymbol.IsAbstract)
                    {
                        return [];
                    }

                    var registrations = CollectRegistrations(classSymbol);
                    return registrations.Count == 0 ? [] : [.. registrations];
                })
            .Where(static registrations => !registrations.IsDefaultOrEmpty);

        var allTypesWithAssembly = context.CompilationProvider
            .Combine(sourceClasses.Collect())
            .Select((data, _) =>
            {
                var (compilation, registrationGroups) = data;
                var assemblyName = compilation.AssemblyName ?? "Unknown";
                var registrations = new List<RegistrationInfo>();
                var seen = new HashSet<string>(System.StringComparer.Ordinal);

                foreach (var registration in registrationGroups.SelectMany(x => x))
                {
                    if (!seen.Add(registration.ServiceType + "|" + registration.ImplementationType))
                    {
                        continue;
                    }

                    registrations.Add(registration);
                }

                return new RegistrationCollection(assemblyName, registrations.ToImmutableArray());
            });

        context.RegisterSourceOutput(allTypesWithAssembly, (spc, data) =>
        {
            if (data.Registrations.IsDefaultOrEmpty)
            {
                return;
            }

            var source = GenerateInitializer(data.AssemblyName, data.Registrations);
            spc.AddSource("RpcServerAutoInjectAssemblyInitializer.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static List<RegistrationInfo> CollectRegistrations(INamedTypeSymbol classSymbol)
    {
        var registrations = new List<RegistrationInfo>();
        var implementationType = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        if (RpcServerSymbolHelper.TryGetRpcHandlerBase(classSymbol, out var handlerBaseType, out _)
            && handlerBaseType is not null)
        {
            registrations.Add(new RegistrationInfo(
                handlerBaseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                implementationType));
        }

        return registrations;
    }

    private static string GenerateInitializer(string assemblyName, ImmutableArray<RegistrationInfo> registrations)
    {
        var sanitizedName = assemblyName.Replace(".", "");
        var initializerTypeName = $"__{sanitizedName}RpcServerAutoInjectAssemblyInitializer";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"[assembly: global::NOF.Abstraction.AssemblyInitializeAttribute<global::{assemblyName}.{initializerTypeName}>]");
        sb.AppendLine();
        sb.AppendLine($"namespace {assemblyName}");
        sb.AppendLine("{");
        sb.AppendLine($"    internal sealed class {initializerTypeName} : global::NOF.Abstraction.IAssemblyInitializer");
        sb.AppendLine("    {");
        sb.AppendLine("        public static void Initialize(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (!services.InitializedTypes.Add(typeof({initializerTypeName})))");
        sb.AppendLine("            {");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine();

        foreach (var registration in registrations)
        {
            sb.AppendLine($"            services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Transient(typeof({registration.ServiceType}), typeof({registration.ImplementationType})));");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private sealed class RegistrationCollection
    {
        public RegistrationCollection(string assemblyName, ImmutableArray<RegistrationInfo> registrations)
        {
            AssemblyName = assemblyName;
            Registrations = registrations;
        }

        public string AssemblyName { get; }
        public ImmutableArray<RegistrationInfo> Registrations { get; }
    }

    private sealed class RegistrationInfo
    {
        public RegistrationInfo(string serviceType, string implementationType)
        {
            ServiceType = serviceType;
            ImplementationType = implementationType;
        }

        public string ServiceType { get; }
        public string ImplementationType { get; }
    }
}
