using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Application.SourceGenerator;

[Generator]
public sealed class RpcServerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) =>
                {
                    if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol classSymbol)
                    {
                        return null;
                    }

                    return RpcServerSymbolHelper.TryGetServiceInterface(classSymbol, out var _) ? classSymbol : null;
                })
            .Where(static x => x is not null);

        context.RegisterSourceOutput(candidates, static (spc, symbol) =>
        {
            GenerateForClass(spc, symbol!);
        });
    }

    private static void GenerateForClass(SourceProductionContext context, INamedTypeSymbol classSymbol)
    {
        if (!RpcServerSymbolHelper.TryGetServiceInterface(classSymbol, out var serviceInterface) || serviceInterface is null)
        {
            return;
        }

        var serviceMethods = serviceInterface.GetMembers().OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary && !m.IsImplicitlyDeclared)
            .ToList();

        if (serviceMethods.Count == 0)
        {
            return;
        }

        var ns = classSymbol.ContainingNamespace is { IsGlobalNamespace: false }
            ? classSymbol.ContainingNamespace.ToDisplayString()
            : null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"partial class {classSymbol.Name}");
        sb.AppendLine("{");

        sb.AppendLine("    private static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> __rpcHandlerMappings =");
        sb.AppendLine("        new global::System.Collections.Generic.Dictionary<string, global::System.Type>");
        sb.AppendLine("        {");

        foreach (var method in serviceMethods)
        {
            if (method.Parameters.Length != 1)
            {
                continue;
            }

            sb.AppendLine($"            [\"{method.Name}\"] = typeof({method.Name}),");
        }
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("    protected override global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> GetHandlerMappings()");
        sb.AppendLine("        => __rpcHandlerMappings;");
        sb.AppendLine();

        foreach (var method in serviceMethods)
        {
            if (method.Parameters.Length != 1
                || method.Parameters[0].Type is not INamedTypeSymbol requestType)
            {
                continue;
            }

            var responseType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var requestTypeName = requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sb.AppendLine($"    public abstract class {method.Name} : global::NOF.Application.RpcHandler<{requestTypeName}, {responseType}>");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.AppendLine("}");
        }

        context.AddSource($"{classSymbol.ToDisplayString().Replace('.', '_')}.RpcServer.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

}

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class RpcServerAnalyzer : DiagnosticAnalyzer
{
    public static readonly DiagnosticDescriptor RpcServerMustBePartial = new(
        "NOF300",
        "RPC server class must be partial",
        "Class '{0}' inheriting RpcServer<TService> must be declared partial",
        "RpcServer",
        DiagnosticSeverity.Error,
        true);

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
    [
        RpcServerMustBePartial
    ];

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();
        context.RegisterSymbolAction(AnalyzeNamedType, SymbolKind.NamedType);
    }

    private static void AnalyzeNamedType(SymbolAnalysisContext context)
    {
        var type = (INamedTypeSymbol)context.Symbol;
        if (type.TypeKind != TypeKind.Class || !RpcServerSymbolHelper.TryGetServiceInterface(type, out _))
        {
            return;
        }

        var location = type.Locations.FirstOrDefault() ?? Location.None;
        var isPartial = type.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<ClassDeclarationSyntax>()
            .Any(c => c.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)));
        if (!isPartial)
        {
            context.ReportDiagnostic(Diagnostic.Create(RpcServerMustBePartial, location, type.Name));
        }
    }
}
