using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Application.SourceGenerator;

[Generator]
public sealed class ServiceImplementationGenerator : IIncrementalGenerator
{
    private const string ServiceImplementationAttributeFqn = "NOF.Application.ServiceImplementationAttribute<TService>";
    private const string GenerateServiceAttributeFqn = "NOF.Contract.GenerateServiceAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, _) =>
                {
                    if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol classSymbol)
                    {
                        return null;
                    }

                    return TryGetServiceInterface(classSymbol, out var _) ? classSymbol : null;
                })
            .Where(static x => x is not null);

        context.RegisterSourceOutput(candidates, static (spc, symbol) =>
        {
            GenerateForClass(spc, symbol!);
        });
    }

    private static void GenerateForClass(SourceProductionContext context, INamedTypeSymbol classSymbol)
    {
        if (!TryGetServiceInterface(classSymbol, out var serviceInterface) || serviceInterface is null)
        {
            return;
        }

        var serviceMethods = serviceInterface.GetMembers().OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary && !m.IsImplicitlyDeclared)
            .ToList();

        if (serviceMethods.Count == 0)
        {
            return;
        }

        var ns = classSymbol.ContainingNamespace is { IsGlobalNamespace: false }
            ? classSymbol.ContainingNamespace.ToDisplayString()
            : null;

        var usedNames = new HashSet<string>(System.StringComparer.Ordinal);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"partial class {classSymbol.Name}");
        sb.AppendLine("{");

        foreach (var method in serviceMethods)
        {
            var requestParam = method.Parameters
                .FirstOrDefault(p => p.Type.ToDisplayString() != "System.Threading.CancellationToken");
            if (requestParam is null)
            {
                continue;
            }

            var opName = GetOperationName(method.Name);
            var interfaceName = $"I{opName}";
            if (!usedNames.Add(interfaceName))
            {
                interfaceName = $"I{opName}_{requestParam.Type.Name}";
                usedNames.Add(interfaceName);
            }

            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var requestType = requestParam.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"    public interface {interfaceName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        {returnType} {method.Name}({requestType} request, global::System.Threading.CancellationToken cancellationToken = default);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.AppendLine("}");
        }

        context.AddSource($"{classSymbol.ToDisplayString().Replace('.', '_')}.ServiceImplementation.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool TryGetServiceInterface(INamedTypeSymbol classSymbol, out INamedTypeSymbol? serviceInterface)
    {
        serviceInterface = null;
        var attr = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass is { IsGenericType: true } ac &&
                                 ac.OriginalDefinition.ToDisplayString() == ServiceImplementationAttributeFqn);
        if (attr?.AttributeClass?.TypeArguments.Length != 1)
        {
            return false;
        }

        serviceInterface = attr.AttributeClass.TypeArguments[0] as INamedTypeSymbol;
        return serviceInterface is not null;
    }

    private static string GetOperationName(string methodName)
        => methodName.EndsWith("Async", System.StringComparison.Ordinal)
            ? methodName.Substring(0, methodName.Length - 5)
            : methodName;
}

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class ServiceImplementationAnalyzer : DiagnosticAnalyzer
{
    private const string ServiceImplementationAttributeFqn = "NOF.Application.ServiceImplementationAttribute<TService>";
    private const string GenerateServiceAttributeFqn = "NOF.Contract.GenerateServiceAttribute";

    public static readonly DiagnosticDescriptor ServiceImplementationMustBePartial = new(
        "NOF300",
        "Service implementation class must be partial",
        "Class '{0}' with [ServiceImplementation<TService>] must be declared partial",
        "ServiceImplementation",
        DiagnosticSeverity.Error,
        true);

    public static readonly DiagnosticDescriptor ServiceTypeMustBeGenerateServiceInterface = new(
        "NOF301",
        "TService must be a GenerateService interface",
        "Type argument '{1}' on [ServiceImplementation<TService>] of class '{0}' must be an interface marked with [GenerateService]",
        "ServiceImplementation",
        DiagnosticSeverity.Error,
        true);

    public static readonly DiagnosticDescriptor ServiceImplementationMustImplementServiceInterface = new(
        "NOF302",
        "Service implementation must implement TService",
        "Class '{0}' with [ServiceImplementation<{1}>] must implement interface '{1}'",
        "ServiceImplementation",
        DiagnosticSeverity.Error,
        true);

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
    [
        ServiceImplementationMustBePartial,
        ServiceTypeMustBeGenerateServiceInterface,
        ServiceImplementationMustImplementServiceInterface
    ];

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();
        context.RegisterSymbolAction(AnalyzeNamedType, SymbolKind.NamedType);
    }

    private static void AnalyzeNamedType(SymbolAnalysisContext context)
    {
        var type = (INamedTypeSymbol)context.Symbol;
        if (type.TypeKind != TypeKind.Class || !TryGetServiceInterface(type, out var serviceInterface) || serviceInterface is null)
        {
            return;
        }

        var location = type.Locations.FirstOrDefault() ?? Location.None;
        var isPartial = type.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<ClassDeclarationSyntax>()
            .Any(c => c.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)));
        if (!isPartial)
        {
            context.ReportDiagnostic(Diagnostic.Create(ServiceImplementationMustBePartial, location, type.Name));
        }

        var isGenerateServiceInterface = serviceInterface.TypeKind == TypeKind.Interface &&
                                         HasAttribute(serviceInterface, GenerateServiceAttributeFqn);
        if (!isGenerateServiceInterface)
        {
            context.ReportDiagnostic(Diagnostic.Create(ServiceTypeMustBeGenerateServiceInterface, location, type.Name, serviceInterface.ToDisplayString()));
            return;
        }

        var implementsServiceInterface = type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, serviceInterface));
        if (!implementsServiceInterface)
        {
            context.ReportDiagnostic(Diagnostic.Create(ServiceImplementationMustImplementServiceInterface, location, type.Name, serviceInterface.ToDisplayString()));
        }
    }

    private static bool HasAttribute(INamedTypeSymbol symbol, string attributeFqn)
        => symbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == attributeFqn);

    private static bool TryGetServiceInterface(INamedTypeSymbol classSymbol, out INamedTypeSymbol? serviceInterface)
    {
        serviceInterface = null;
        var attr = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass is { IsGenericType: true } ac &&
                                 ac.OriginalDefinition.ToDisplayString() == ServiceImplementationAttributeFqn);
        if (attr?.AttributeClass?.TypeArguments.Length != 1)
        {
            return false;
        }

        serviceInterface = attr.AttributeClass.TypeArguments[0] as INamedTypeSymbol;
        return serviceInterface is not null;
    }
}
