using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Application.SourceGenerator;

[Generator]
public sealed class ServiceImplementationGenerator : IIncrementalGenerator
{
    private const string ServiceImplementationAttributeFqn = "NOF.Application.ServiceImplementationAttribute<TService>";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, _) =>
                {
                    if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol classSymbol)
                    {
                        return null;
                    }

                    return TryGetServiceInterface(classSymbol, out var _) ? classSymbol : null;
                })
            .Where(static x => x is not null);

        context.RegisterSourceOutput(candidates, static (spc, symbol) =>
        {
            GenerateForClass(spc, symbol!);
        });
    }

    private static void GenerateForClass(SourceProductionContext context, INamedTypeSymbol classSymbol)
    {
        if (!TryGetServiceInterface(classSymbol, out var serviceInterface) || serviceInterface is null)
        {
            return;
        }

        var serviceMethods = serviceInterface.GetMembers().OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary && !m.IsImplicitlyDeclared)
            .ToList();

        if (serviceMethods.Count == 0)
        {
            return;
        }

        var ns = classSymbol.ContainingNamespace is { IsGlobalNamespace: false }
            ? classSymbol.ContainingNamespace.ToDisplayString()
            : null;

        var serviceInterfaceFqn = serviceInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var shouldImplementServiceInterface = !classSymbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, serviceInterface));

        var usedNames = new HashSet<string>(System.StringComparer.Ordinal);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        var classDecl = $"partial class {classSymbol.Name}";
        if (shouldImplementServiceInterface)
        {
            classDecl += $" : {serviceInterfaceFqn}";
        }

        sb.AppendLine(classDecl);
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::System.IServiceProvider _serviceProvider;");
        sb.AppendLine();
        sb.AppendLine($"    public {classSymbol.Name}(global::System.IServiceProvider serviceProvider)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(serviceProvider);");
        sb.AppendLine("        _serviceProvider = serviceProvider;");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var method in serviceMethods)
        {
            var requestParam = method.Parameters.FirstOrDefault(p => p.Type.ToDisplayString() != "System.Threading.CancellationToken");
            if (requestParam is null)
            {
                continue;
            }

            var hasCancellationToken = method.Parameters.Any(p => p.Type.ToDisplayString() == "System.Threading.CancellationToken");
            var opName = GetOperationName(method.Name);
            var interfaceName = opName;
            if (!usedNames.Add(interfaceName))
            {
                interfaceName = $"{opName}_{requestParam.Type.Name}";
                usedNames.Add(interfaceName);
            }

            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var requestType = requestParam.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var nestedInterfaceFqn = $"global::{(string.IsNullOrWhiteSpace(ns) ? classSymbol.Name : ns + "." + classSymbol.Name)}.{interfaceName}";

            sb.AppendLine($"    public interface {interfaceName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        {returnType} {method.Name}({requestType} request, global::System.Threading.CancellationToken cancellationToken = default);");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine($"    public {returnType} {method.Name}({requestType} request{(hasCancellationToken ? ", global::System.Threading.CancellationToken cancellationToken = default" : string.Empty)})");
            sb.AppendLine("    {");
            sb.AppendLine($"        var operation = _serviceProvider.GetService(typeof({nestedInterfaceFqn})) as {nestedInterfaceFqn};");
            sb.AppendLine("        if (operation is null)");
            sb.AppendLine("        {");
            sb.AppendLine($"            throw new global::System.InvalidOperationException(\"RPC operation implementation is missing: {nestedInterfaceFqn}.\");");
            sb.AppendLine("        }");
            sb.AppendLine($"        return operation.{method.Name}(request, {(hasCancellationToken ? "cancellationToken" : "default")});");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.AppendLine("}");
        }

        context.AddSource($"{classSymbol.ToDisplayString().Replace('.', '_')}.ServiceImplementation.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool TryGetServiceInterface(INamedTypeSymbol classSymbol, out INamedTypeSymbol? serviceInterface)
    {
        serviceInterface = null;
        var attr = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass is { IsGenericType: true } ac &&
                                 ac.OriginalDefinition.ToDisplayString() == ServiceImplementationAttributeFqn);
        if (attr?.AttributeClass?.TypeArguments.Length != 1)
        {
            return false;
        }

        serviceInterface = attr.AttributeClass.TypeArguments[0] as INamedTypeSymbol;
        return serviceInterface is not null;
    }

    private static string GetOperationName(string methodName)
        => methodName.EndsWith("Async", System.StringComparison.Ordinal)
            ? methodName.Substring(0, methodName.Length - 5)
            : methodName;
}

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class ServiceImplementationAnalyzer : DiagnosticAnalyzer
{
    private const string ServiceImplementationAttributeFqn = "NOF.Application.ServiceImplementationAttribute<TService>";
    private const string RpcServiceInterfaceFqn = "NOF.Contract.IRpcService";

    public static readonly DiagnosticDescriptor ServiceImplementationMustBePartial = new(
        "NOF300",
        "Service implementation class must be partial",
        "Class '{0}' with [ServiceImplementation<TService>] must be declared partial",
        "ServiceImplementation",
        DiagnosticSeverity.Error,
        true);

    public static readonly DiagnosticDescriptor ServiceTypeMustBeRpcServiceInterface = new(
        "NOF301",
        "TService must be an RPC service interface",
        "Type argument '{1}' on [ServiceImplementation<TService>] of class '{0}' must be an interface implementing IRpcService",
        "ServiceImplementation",
        DiagnosticSeverity.Error,
        true);

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
    [
        ServiceImplementationMustBePartial,
        ServiceTypeMustBeRpcServiceInterface
    ];

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();
        context.RegisterSymbolAction(AnalyzeNamedType, SymbolKind.NamedType);
    }

    private static void AnalyzeNamedType(SymbolAnalysisContext context)
    {
        var type = (INamedTypeSymbol)context.Symbol;
        if (type.TypeKind != TypeKind.Class || !TryGetServiceInterface(type, out var serviceInterface) || serviceInterface is null)
        {
            return;
        }

        var location = type.Locations.FirstOrDefault() ?? Location.None;
        var isPartial = type.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<ClassDeclarationSyntax>()
            .Any(c => c.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)));
        if (!isPartial)
        {
            context.ReportDiagnostic(Diagnostic.Create(ServiceImplementationMustBePartial, location, type.Name));
        }

        var isRpcServiceInterface = serviceInterface.TypeKind == TypeKind.Interface &&
                                    (serviceInterface.ToDisplayString() == RpcServiceInterfaceFqn ||
                                     serviceInterface.AllInterfaces.Any(i => i.ToDisplayString() == RpcServiceInterfaceFqn));
        if (!isRpcServiceInterface)
        {
            context.ReportDiagnostic(Diagnostic.Create(ServiceTypeMustBeRpcServiceInterface, location, type.Name, serviceInterface.ToDisplayString()));
        }
    }

    private static bool TryGetServiceInterface(INamedTypeSymbol classSymbol, out INamedTypeSymbol? serviceInterface)
    {
        serviceInterface = null;
        var attr = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass is { IsGenericType: true } ac &&
                                 ac.OriginalDefinition.ToDisplayString() == ServiceImplementationAttributeFqn);
        if (attr?.AttributeClass?.TypeArguments.Length != 1)
        {
            return false;
        }

        serviceInterface = attr.AttributeClass.TypeArguments[0] as INamedTypeSymbol;
        return serviceInterface is not null;
    }
}
