using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Application.SourceGenerator;

[Generator]
public sealed class ServiceImplementationGenerator : IIncrementalGenerator
{
    private const string ServiceImplementationAttributeFqn = "NOF.Application.ServiceImplementationAttribute<TService>";

    private static bool TryGetServiceReturnInfo(IMethodSymbol method, out ServiceReturnInfo returnInfo)
    {
        if (method.ReturnType is INamedTypeSymbol { IsGenericType: true } generic &&
            generic.OriginalDefinition.ToDisplayString() == "System.Threading.Tasks.Task<TResult>")
        {
            var taskArgument = generic.TypeArguments[0];
            var taskArgumentDisplay = taskArgument.ToDisplayString();

            if (taskArgumentDisplay == "NOF.Contract.Result")
            {
                returnInfo = new ServiceReturnInfo(ServiceReturnKind.TaskOfResult, null);
                return true;
            }

            if (taskArgument is INamedTypeSymbol { IsGenericType: true } genericResult &&
                genericResult.OriginalDefinition.ToDisplayString() == "NOF.Contract.Result<T>")
            {
                returnInfo = new ServiceReturnInfo(ServiceReturnKind.TaskOfResultOfT, genericResult.TypeArguments[0]);
                return true;
            }
        }

        returnInfo = default;
        return false;
    }

    private enum ServiceReturnKind
    {
        TaskOfResult,
        TaskOfResultOfT
    }

    private readonly struct ServiceReturnInfo
    {
        public ServiceReturnInfo(ServiceReturnKind kind, ITypeSymbol? valueType)
        {
            Kind = kind;
            ValueType = valueType;
        }

        public ServiceReturnKind Kind { get; }
        public ITypeSymbol? ValueType { get; }
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, _) =>
                {
                    if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol classSymbol)
                    {
                        return null;
                    }

                    return TryGetServiceInterface(classSymbol, out var _) ? classSymbol : null;
                })
            .Where(static x => x is not null);

        var candidatesWithCompilation = candidates.Combine(context.CompilationProvider);
        context.RegisterSourceOutput(candidatesWithCompilation, static (spc, data) =>
        {
            var (symbol, compilation) = data;
            GenerateForClass(spc, symbol!, compilation);
        });
    }

    private static void GenerateForClass(SourceProductionContext context, INamedTypeSymbol classSymbol, Compilation compilation)
    {
        if (!TryGetServiceInterface(classSymbol, out var serviceInterface) || serviceInterface is null)
        {
            return;
        }

        var serviceMethods = serviceInterface.GetMembers().OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary && !m.IsImplicitlyDeclared)
            .ToList();

        if (serviceMethods.Count == 0)
        {
            return;
        }

        var ns = classSymbol.ContainingNamespace is { IsGlobalNamespace: false }
            ? classSymbol.ContainingNamespace.ToDisplayString()
            : null;

        var serviceInterfaceFqn = serviceInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var implementationTypeFqn = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var shouldImplementServiceInterface = !classSymbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, serviceInterface));

        var usedNames = new HashSet<string>(System.StringComparer.Ordinal);
        var operationInterfaceTypes = new List<(string InterfaceName, string InterfaceFqn)>();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");

        var sanitizedName = SanitizeIdentifier(classSymbol.ToDisplayString());
        var initializerTypeName = $"__{sanitizedName}RequestHandlerAssemblyInitializer";
        var initializerTypeFqn = string.IsNullOrWhiteSpace(ns)
            ? $"global::{initializerTypeName}"
            : $"global::{ns}.{initializerTypeName}";
        sb.AppendLine($"[assembly: global::NOF.Annotation.AssemblyInitializeAttribute<{initializerTypeFqn}>]");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        var classDecl = $"partial class {classSymbol.Name}";
        if (shouldImplementServiceInterface)
        {
            classDecl += $" : {serviceInterfaceFqn}";
        }

        sb.AppendLine(classDecl);
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::System.IServiceProvider _serviceProvider;");
        sb.AppendLine();
        sb.AppendLine($"    public {classSymbol.Name}(global::System.IServiceProvider serviceProvider)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(serviceProvider);");
        sb.AppendLine("        _serviceProvider = serviceProvider;");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var method in serviceMethods)
        {
            var requestParam = method.Parameters.FirstOrDefault(p => p.Type.ToDisplayString() != "System.Threading.CancellationToken");
            var hasRequestParam = requestParam is not null;

            if (!TryGetServiceReturnInfo(method, out var returnInfo))
            {
                continue;
            }

            var hasCancellationToken = method.Parameters.Any(p => p.Type.ToDisplayString() == "System.Threading.CancellationToken");
            var opName = GetOperationName(method.Name);
            var interfaceName = opName;
            if (!usedNames.Add(interfaceName))
            {
                interfaceName = hasRequestParam ? $"{opName}_{requestParam!.Type.Name}" : $"{opName}";
                usedNames.Add(interfaceName);
            }

            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var innerReturnType = returnInfo.Kind switch
            {
                ServiceReturnKind.TaskOfResult => "global::NOF.Contract.Result",
                ServiceReturnKind.TaskOfResultOfT => returnInfo.ValueType != null
                    ? $"global::NOF.Contract.Result<{returnInfo.ValueType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>"
                    : "global::NOF.Contract.Result",
                _ => "global::NOF.Contract.Result"
            };
            string? requestType = hasRequestParam
                ? requestParam!.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                : null;
            var nestedInterfaceFqn = $"global::{(string.IsNullOrWhiteSpace(ns) ? classSymbol.Name : ns + "." + classSymbol.Name)}.{interfaceName}";

            sb.AppendLine($"    public interface {interfaceName}");
            sb.AppendLine("    {");
            if (hasRequestParam)
            {
                sb.AppendLine($"        {returnType} {method.Name}({requestType} request, global::System.Threading.CancellationToken cancellationToken = default);");
            }
            else
            {
                sb.AppendLine($"        {returnType} {method.Name}(global::System.Threading.CancellationToken cancellationToken = default);");
            }
            sb.AppendLine("    }");
            sb.AppendLine();

            var outerTypeFqn = method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            // 为每个操作缓存 MethodInfo（静态初始化一次）；分析器已禁止重载，按名称唯一绑定
            sb.AppendLine($"    private static readonly global::System.Reflection.MethodInfo __mi_{interfaceName}_{method.Name} =");
            sb.AppendLine($"        typeof({outerTypeFqn}).GetMethod(");
            sb.AppendLine($"            nameof({method.Name}),");
            sb.AppendLine($"            global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Instance)");
            sb.AppendLine($"        ?? throw new global::System.InvalidOperationException(\"Failed to resolve method info.\");");
            sb.AppendLine();

            operationInterfaceTypes.Add((interfaceName, nestedInterfaceFqn));

            if (hasRequestParam)
            {
                sb.AppendLine($"    public async {returnType} {method.Name}({requestType} request{(hasCancellationToken ? ", global::System.Threading.CancellationToken cancellationToken = default" : string.Empty)})");
            }
            else
            {
                sb.AppendLine($"    public async {returnType} {method.Name}({(hasCancellationToken ? "global::System.Threading.CancellationToken cancellationToken = default" : string.Empty)})");
            }
            sb.AppendLine("    {");
            sb.AppendLine($"        var isService = _serviceProvider.GetService<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>();");
            sb.AppendLine($"        if (isService is null || !isService.IsService(typeof({nestedInterfaceFqn})))");
            sb.AppendLine("        {");
            sb.AppendLine($"            throw new global::System.InvalidOperationException(\"RPC operation implementation is missing: {nestedInterfaceFqn}.\");");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        var outboundPipeline = _serviceProvider.GetRequiredService<global::NOF.Contract.IOutboundPipelineExecutor>();");
            sb.AppendLine("        var outboundExecutionContext = _serviceProvider.GetRequiredService<global::NOF.Contract.IExecutionContext>();");
            sb.AppendLine();
            sb.AppendLine("        var outboundContext = new global::NOF.Contract.OutboundContext");
            sb.AppendLine("        {");
            sb.AppendLine(hasRequestParam
                ? "            Message = request,"
                : "            Message = null,");
            sb.AppendLine("            Services = _serviceProvider");
            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine($"        {innerReturnType} result = default!;");
            sb.AppendLine();
            var outerInterfaceType = method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine("        await outboundPipeline.ExecuteAsync(outboundContext, async (ct) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            await global::NOF.Application.InboundHandlerInvoker.ExecuteRpcAsync(");
            sb.AppendLine("                _serviceProvider,");
            sb.AppendLine(hasRequestParam ? "                request," : "                null,");
            sb.AppendLine($"                __mi_{interfaceName}_{method.Name},");
            sb.AppendLine("                outboundExecutionContext,");
            sb.AppendLine("                context =>");
            sb.AppendLine("                {");
            sb.AppendLine($"                    context.Metadatas[\"HandlerType\"] = typeof({nestedInterfaceFqn});");
            sb.AppendLine($"                    context.Metadatas[\"HandlerName\"] = typeof({nestedInterfaceFqn}).FullName;");
            sb.AppendLine("                },");
            sb.AppendLine("                async (sp2, ct2) =>");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var operation = sp2.GetRequiredService<{nestedInterfaceFqn}>();");
            sb.AppendLine(hasRequestParam
                ? $"                    result = await operation.{method.Name}(request, {(hasCancellationToken ? "ct2" : "default")});"
                : $"                    result = await operation.{method.Name}({(hasCancellationToken ? "ct2" : "default")});");
            sb.AppendLine("                },");
            sb.AppendLine("                ct).ConfigureAwait(false);");
            var cancellationTokenArg = hasCancellationToken ? "cancellationToken" : "default";
            sb.AppendLine($"        }}, {cancellationTokenArg}).ConfigureAwait(false);");
            sb.AppendLine();
            sb.AppendLine("        return result;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        sb.AppendLine();
        var registrations = DiscoverRequestHandlerRegistrations(compilation, classSymbol, operationInterfaceTypes);

        sb.AppendLine($"internal sealed class {initializerTypeName} : global::NOF.Annotation.IAssemblyInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    private static int _initialized;");
        sb.AppendLine();
        sb.AppendLine("    public static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (global::System.Threading.Interlocked.Exchange(ref _initialized, 1) == 1)");
        sb.AppendLine("        {");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine();
        foreach (var (serviceType, implementationType) in registrations)
        {
            sb.AppendLine($"        global::NOF.Application.RequestHandlerRegistry.Register(typeof({serviceType}), typeof({implementationType}));");
        }
        sb.AppendLine($"        global::NOF.Annotation.AutoInjectRegistry.Register(typeof({serviceInterfaceFqn}), typeof({implementationTypeFqn}), global::NOF.Annotation.Lifetime.Transient, useFactory: false);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.AppendLine("}");
        }

        context.AddSource($"{classSymbol.ToDisplayString().Replace('.', '_')}.ServiceImplementation.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool TryGetServiceInterface(INamedTypeSymbol classSymbol, out INamedTypeSymbol? serviceInterface)
    {
        serviceInterface = null;
        var attr = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass is { IsGenericType: true } ac &&
                                 ac.OriginalDefinition.ToDisplayString() == ServiceImplementationAttributeFqn);
        if (attr?.AttributeClass?.TypeArguments.Length != 1)
        {
            return false;
        }

        serviceInterface = attr.AttributeClass.TypeArguments[0] as INamedTypeSymbol;
        return serviceInterface is not null;
    }

    private static string GetOperationName(string methodName)
        => methodName.EndsWith("Async", System.StringComparison.Ordinal)
            ? methodName.Substring(0, methodName.Length - 5)
            : methodName;

    private static string SanitizeIdentifier(string input)
    {
        var chars = input.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray();
        return new string(chars);
    }

    private static List<(string ServiceType, string ImplementationType)> DiscoverRequestHandlerRegistrations(
        Compilation compilation,
        INamedTypeSymbol serviceImplementationClass,
        IReadOnlyList<(string InterfaceName, string InterfaceFqn)> operationInterfaces)
    {
        var result = new List<(string ServiceType, string ImplementationType)>();
        var dedupe = new HashSet<string>(System.StringComparer.Ordinal);
        var serviceTypeMap = new Dictionary<string, string>(System.StringComparer.Ordinal);

        foreach (var (interfaceName, interfaceFqn) in operationInterfaces)
        {
            var canonicalFqn = TrimGlobal(interfaceFqn);
            serviceTypeMap[canonicalFqn] = interfaceFqn;
            serviceTypeMap[$"{serviceImplementationClass.Name}.{interfaceName}"] = interfaceFqn;
            serviceTypeMap[$"{serviceImplementationClass.ToDisplayString()}.{interfaceName}"] = interfaceFqn;
        }

        foreach (var tree in compilation.SyntaxTrees)
        {
            var semanticModel = compilation.GetSemanticModel(tree);
            var classDeclarations = tree.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>();

            foreach (var classDeclaration in classDeclarations)
            {
                if (classDeclaration.BaseList is null)
                {
                    continue;
                }

                if (semanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol implementationSymbol ||
                    implementationSymbol.IsAbstract)
                {
                    continue;
                }

                var implementationFqn = implementationSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                foreach (var baseType in classDeclaration.BaseList.Types)
                {
                    string? matchedServiceFqn = null;

                    var baseTypeSymbol = semanticModel.GetTypeInfo(baseType.Type).Type as INamedTypeSymbol;
                    if (baseTypeSymbol is not null &&
                        baseTypeSymbol.ContainingType is INamedTypeSymbol containingType &&
                        SymbolEqualityComparer.Default.Equals(containingType, serviceImplementationClass))
                    {
                        var semanticService = baseTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        matchedServiceFqn = semanticService;
                    }
                    else
                    {
                        var typeText = TrimGlobal(baseType.Type.ToString());
                        if (serviceTypeMap.TryGetValue(typeText, out var mapped))
                        {
                            matchedServiceFqn = mapped;
                        }
                    }

                    if (string.IsNullOrWhiteSpace(matchedServiceFqn))
                    {
                        continue;
                    }

                    var key = $"{matchedServiceFqn}|{implementationFqn}";
                    if (dedupe.Add(key))
                    {
                        result.Add((matchedServiceFqn!, implementationFqn));
                    }
                }
            }
        }

        return result;
    }

    private static string TrimGlobal(string typeName)
        => typeName.Replace("global::", string.Empty);
}

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class ServiceImplementationAnalyzer : DiagnosticAnalyzer
{
    private const string ServiceImplementationAttributeFqn = "NOF.Application.ServiceImplementationAttribute<TService>";

    public static readonly DiagnosticDescriptor ServiceImplementationMustBePartial = new(
        "NOF300",
        "Service implementation class must be partial",
        "Class '{0}' with [ServiceImplementation<TService>] must be declared partial",
        "ServiceImplementation",
        DiagnosticSeverity.Error,
        true);

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
    [
        ServiceImplementationMustBePartial
    ];

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();
        context.RegisterSymbolAction(AnalyzeNamedType, SymbolKind.NamedType);
    }

    private static void AnalyzeNamedType(SymbolAnalysisContext context)
    {
        var type = (INamedTypeSymbol)context.Symbol;
        if (type.TypeKind != TypeKind.Class || !TryGetServiceInterface(type, out _))
        {
            return;
        }

        var location = type.Locations.FirstOrDefault() ?? Location.None;
        var isPartial = type.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<ClassDeclarationSyntax>()
            .Any(c => c.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)));
        if (!isPartial)
        {
            context.ReportDiagnostic(Diagnostic.Create(ServiceImplementationMustBePartial, location, type.Name));
        }

    }

    private static bool TryGetServiceInterface(INamedTypeSymbol classSymbol, out INamedTypeSymbol? serviceInterface)
    {
        serviceInterface = null;
        var attr = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass is { IsGenericType: true } ac &&
                                 ac.OriginalDefinition.ToDisplayString() == ServiceImplementationAttributeFqn);
        if (attr?.AttributeClass?.TypeArguments.Length != 1)
        {
            return false;
        }

        serviceInterface = attr.AttributeClass.TypeArguments[0] as INamedTypeSymbol;
        return serviceInterface is not null;
    }
}
