using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Application.SourceGenerator;

[Generator]
public sealed class SplitInterfaceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) =>
                {
                    if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol classSymbol)
                    {
                        return null;
                    }

                    return SplitInterfaceSymbolHelper.TryGetServiceInterface(classSymbol, out var _) ? classSymbol : null;
                })
            .Where(static x => x is not null);

        context.RegisterSourceOutput(candidates, static (spc, symbol) =>
        {
            GenerateForClass(spc, symbol!);
        });
    }

    private static void GenerateForClass(SourceProductionContext context, INamedTypeSymbol classSymbol)
    {
        if (!SplitInterfaceSymbolHelper.TryGetServiceInterface(classSymbol, out var serviceInterface) || serviceInterface is null)
        {
            return;
        }

        var serviceMethods = serviceInterface.GetMembers().OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary && !m.IsImplicitlyDeclared)
            .ToList();

        if (serviceMethods.Count == 0)
        {
            return;
        }

        var ns = classSymbol.ContainingNamespace is { IsGlobalNamespace: false }
            ? classSymbol.ContainingNamespace.ToDisplayString()
            : null;

        var usedNames = new HashSet<string>(System.StringComparer.Ordinal);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"partial class {classSymbol.Name}");
        sb.AppendLine("{");

        foreach (var method in serviceMethods)
        {
            var opName = GetOperationName(method.Name);
            var interfaceName = opName;
            if (!usedNames.Add(interfaceName))
            {
                interfaceName = opName;
                var i = 2;
                while (!usedNames.Add($"{interfaceName}_{i}"))
                {
                    i++;
                }
                interfaceName = $"{interfaceName}_{i}";
            }

            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sb.AppendLine($"    public interface {interfaceName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        {returnType} {method.Name}({GetMethodParameters(method)});");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.AppendLine("}");
        }

        context.AddSource($"{classSymbol.ToDisplayString().Replace('.', '_')}.SplitInterface.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string GetMethodParameters(IMethodSymbol method)
    {
        var parameters = method.Parameters
            .Select(p => $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {p.Name}")
            .ToList();

        if (parameters.Count == 0)
        {
            return string.Empty;
        }

        return string.Join(", ", parameters);
    }

    private static string GetOperationName(string methodName)
        => methodName.EndsWith("Async", System.StringComparison.Ordinal)
            ? methodName.Substring(0, methodName.Length - 5)
            : methodName;
}

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class SplitInterfaceAnalyzer : DiagnosticAnalyzer
{
    public static readonly DiagnosticDescriptor SplitInterfaceMustBePartial = new(
        "NOF300",
        "Split interface class must be partial",
        "Class '{0}' implementing ISplitedInterface<TService> must be declared partial",
        "SplitInterface",
        DiagnosticSeverity.Error,
        true);

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
    [
        SplitInterfaceMustBePartial
    ];

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();
        context.RegisterSymbolAction(AnalyzeNamedType, SymbolKind.NamedType);
    }

    private static void AnalyzeNamedType(SymbolAnalysisContext context)
    {
        var type = (INamedTypeSymbol)context.Symbol;
        if (type.TypeKind != TypeKind.Class || !SplitInterfaceSymbolHelper.TryGetServiceInterface(type, out _))
        {
            return;
        }

        var location = type.Locations.FirstOrDefault() ?? Location.None;
        var isPartial = type.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<ClassDeclarationSyntax>()
            .Any(c => c.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)));
        if (!isPartial)
        {
            context.ReportDiagnostic(Diagnostic.Create(SplitInterfaceMustBePartial, location, type.Name));
        }
    }
}
