using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Contract.SourceGenerator;

[Generator]
public class ExposeToHttpEndpointServiceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) =>
                {
                    if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol classSymbol)
                    {
                        return null;
                    }

                    return TryGetServiceInterfaceFromHttpClientAttribute(classSymbol, out var _) ? classSymbol : null;
                })
            .Where(static m => m is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(classProvider.Collect());
        context.RegisterSourceOutput(compilationAndClasses, Generate);
    }

    private static void Generate(SourceProductionContext context, (Compilation Compilation, ImmutableArray<INamedTypeSymbol?> Classes) source)
    {
        if (source.Classes.IsDefaultOrEmpty)
        {
            return;
        }

        foreach (var targetClass in source.Classes.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            GenerateForTargetClass(context, targetClass);
        }
    }

    private static void GenerateForTargetClass(SourceProductionContext context, INamedTypeSymbol targetClass)
    {
        if (!TryGetServiceInterfaceFromHttpClientAttribute(targetClass, out var iface) || iface is null)
        {
            return;
        }

        if (!ExposeToHttpEndpointHelpers.IsRpcServiceInterface(iface))
        {
            return;
        }

        var methods = GetServiceMethods(iface);
        if (methods.Count == 0)
        {
            return;
        }

        var targetNamespace = ExposeToHttpEndpointHelpers.GetFullNamespace(targetClass.ContainingNamespace);
        var serviceInterfaceFqn = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var shouldImplementInterface = !targetClass.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, iface));

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using NOF.Contract;");
        sb.AppendLine();
        sb.AppendLine($"namespace {targetNamespace}");
        sb.AppendLine("{");

        var classDecl = $"    public partial class {targetClass.Name}";
        if (shouldImplementInterface)
        {
            classDecl += $" : {serviceInterfaceFqn}";
        }

        sb.AppendLine(classDecl);
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::System.Net.Http.HttpClient _httpClient;");
        sb.AppendLine("        private static readonly global::System.Text.Json.JsonSerializerOptions _jsonOptions = global::System.Text.Json.JsonSerializerOptions.NOF;");
        sb.AppendLine();
        sb.AppendLine($"        public {targetClass.Name}(global::System.Net.Http.HttpClient httpClient)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(httpClient);");
        sb.AppendLine("            _httpClient = httpClient;");
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach (var method in methods)
        {
            var endpointInfo = ExposeToHttpEndpointHelpers.ExtractEndpointInfo(method);
            EmitHttpMethodBody(sb, method, endpointInfo);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{targetClass.ToDisplayString().Replace('.', '_')}.HttpServiceClient.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool TryGetServiceInterfaceFromHttpClientAttribute(INamedTypeSymbol classSymbol, out INamedTypeSymbol? serviceInterface)
    {
        serviceInterface = null;
        var attr = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass is { IsGenericType: true } ac &&
                                 ac.OriginalDefinition.ToDisplayString() == ExposeToHttpEndpointHelpers.HttpServiceClientAttributeFqn);

        if (attr?.AttributeClass?.TypeArguments.Length != 1)
        {
            return false;
        }

        serviceInterface = attr.AttributeClass.TypeArguments[0] as INamedTypeSymbol;
        return serviceInterface is not null;
    }

    private static List<ServiceMethodInfo> GetServiceMethods(INamedTypeSymbol iface)
    {
        var methods = new List<ServiceMethodInfo>();

        foreach (var member in iface.GetMembers())
        {
            if (member is not IMethodSymbol { MethodKind: MethodKind.Ordinary } method || method.IsImplicitlyDeclared)
            {
                continue;
            }

            if (!ExposeToHttpEndpointHelpers.TryGetRequestParameter(method, out var requestParam))
            {
                continue;
            }

            if (requestParam.Type is not INamedTypeSymbol requestType)
            {
                continue;
            }

            if (!ExposeToHttpEndpointHelpers.TryGetServiceReturnInfo(method, out var returnInfo))
            {
                continue;
            }

            var operationName = ExposeToHttpEndpointHelpers.GetOperationName(method.Name);

            methods.Add(new ServiceMethodInfo
            {
                Method = method,
                RequestType = requestType,
                ReturnInfo = returnInfo,
                OperationName = operationName
            });
        }

        return methods;
    }

    private static void EmitHttpMethodBody(StringBuilder sb, ServiceMethodInfo method, EndpointInfo endpoint)
    {
        var requestType = endpoint.RequestType.ToDisplayString();
        var returnType = method.Method.ReturnType.ToDisplayString();
        var methodName = method.Method.Name;
        var returnKind = endpoint.ReturnInfo.Kind;
        var returnValueType = endpoint.ReturnInfo.ValueType?.ToDisplayString();
        var httpMethod = GetHttpMethod(endpoint.Method);
        var isBodyMethod = IsBodyMethod(endpoint.Method);
        var fqnHttpMethod = $"global::System.Net.Http.{httpMethod}";

        var allProperties = ExposeToHttpEndpointHelpers.GetAllPublicProperties(endpoint.RequestType);
        var routeParams = ExposeToHttpEndpointHelpers.ExtractRouteParameters(endpoint.Route);

        var routeParamProperties = new List<(string ParamName, IPropertySymbol Property)>();
        var nonRouteProperties = new List<IPropertySymbol>();

        foreach (var prop in allProperties)
        {
            var matchedParam = routeParams.FirstOrDefault(rp =>
                string.Equals(rp, prop.Name, StringComparison.OrdinalIgnoreCase));
            if (matchedParam != null)
            {
                routeParamProperties.Add((matchedParam, prop));
            }
            else
            {
                nonRouteProperties.Add(prop);
            }
        }

        var hasRouteParams = routeParamProperties.Count > 0;
        var hasCancellationToken = method.Method.Parameters.Any(p => ExposeToHttpEndpointHelpers.IsCancellationToken(p.Type));
        var cancellationTokenArgument = hasCancellationToken ? "cancellationToken" : "global::System.Threading.CancellationToken.None";

        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine($"        public virtual async {returnType} {methodName}({requestType} request{(hasCancellationToken ? ", global::System.Threading.CancellationToken cancellationToken" : string.Empty)})");
        sb.AppendLine("        {");

        if (hasRouteParams)
        {
            var routeExpression = BuildRouteInterpolation(sb, endpoint.Route, routeParamProperties);
            sb.AppendLine($"            var endpoint = {routeExpression};");
        }
        else
        {
            sb.AppendLine($"            var endpoint = \"{endpoint.Route}\";");
        }

        if (isBodyMethod)
        {
            if (hasRouteParams && nonRouteProperties.Count > 0)
            {
                sb.AppendLine($"            var body = new global::System.Collections.Generic.Dictionary<string, object?>({nonRouteProperties.Count});");
                foreach (var prop in nonRouteProperties)
                {
                    sb.AppendLine($"            body[\"{prop.Name}\"] = request.{prop.Name};");
                }
                sb.AppendLine("            using var httpRequest = new global::System.Net.Http.HttpRequestMessage(" + fqnHttpMethod + ", endpoint);");
                sb.AppendLine("            httpRequest.Content = global::System.Net.Http.Json.JsonContent.Create(body, options: _jsonOptions);");
            }
            else if (hasRouteParams && nonRouteProperties.Count == 0)
            {
                sb.AppendLine("            using var httpRequest = new global::System.Net.Http.HttpRequestMessage(" + fqnHttpMethod + ", endpoint);");
            }
            else
            {
                sb.AppendLine("            using var httpRequest = new global::System.Net.Http.HttpRequestMessage(" + fqnHttpMethod + ", endpoint);");
                sb.AppendLine($"            httpRequest.Content = global::System.Net.Http.Json.JsonContent.Create(request, typeof({requestType}), options: _jsonOptions);");
            }
        }
        else
        {
            if (nonRouteProperties.Count > 0)
            {
                sb.AppendLine("            var queryParts = new global::System.Collections.Generic.List<string>();");
                foreach (var prop in nonRouteProperties)
                {
                    EmitQueryParamAppend(sb, prop);
                }
                sb.AppendLine("            if (queryParts.Count > 0)");
                sb.AppendLine("            {");
                sb.AppendLine("                endpoint = endpoint + \"?\" + string.Join(\"&\", queryParts);");
                sb.AppendLine("            }");
            }

            sb.AppendLine("            using var httpRequest = new global::System.Net.Http.HttpRequestMessage(" + fqnHttpMethod + ", endpoint);");
        }

        sb.AppendLine($"            using var response = await _httpClient.SendAsync(httpRequest, {cancellationTokenArgument}).ConfigureAwait(false);");

        EmitResponseHandling(sb, returnKind, returnValueType, cancellationTokenArgument);
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitResponseHandling(StringBuilder sb, ServiceReturnKind returnKind, string? returnValueType, string cancellationTokenArgument)
    {
        sb.AppendLine("            response.EnsureSuccessStatusCode();");

        if (returnKind == ServiceReturnKind.Task)
        {
            sb.AppendLine("            return;");
        }
        else if (returnKind == ServiceReturnKind.TaskOfT)
        {
            sb.AppendLine($"            var apiResponse = await global::System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync<{returnValueType}>(response.Content, _jsonOptions, {cancellationTokenArgument});");
            sb.AppendLine("            return apiResponse!;");
        }
        else
        {
            sb.AppendLine("            throw new global::System.InvalidOperationException(\"Unsupported service return kind.\");");
        }
    }

    private static void EmitQueryParamAppend(StringBuilder sb, IPropertySymbol prop)
    {
        var propName = prop.Name;
        var isNullable = prop.Type.NullableAnnotation == NullableAnnotation.Annotated
                         || prop.Type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;

        if (isNullable)
        {
            sb.AppendLine($"            if (request.{propName} is not null)");
            sb.AppendLine("            {");
            sb.AppendLine($"                queryParts.Add(global::System.Uri.EscapeDataString(\"{propName}\") + \"=\" + global::System.Uri.EscapeDataString({FormatValueExpression($"request.{propName}", prop.Type, true)}));");
            sb.AppendLine("            }");
        }
        else
        {
            sb.AppendLine($"            queryParts.Add(global::System.Uri.EscapeDataString(\"{propName}\") + \"=\" + global::System.Uri.EscapeDataString({FormatValueExpression($"request.{propName}", prop.Type, false)}));");
        }
    }

    internal static string FormatValueExpression(string accessor, ITypeSymbol type, bool isNullable)
    {
        var underlying = type;
        var isNullableValueType = false;
        if (isNullable && type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } namedType)
        {
            underlying = namedType.TypeArguments[0];
            isNullableValueType = true;
        }

        var display = underlying.ToDisplayString();
        var valueAccessor = isNullableValueType ? $"{accessor}.Value" : accessor;

        return display switch
        {
            "System.DateTime" => $"{valueAccessor}.ToString(\"O\", global::System.Globalization.CultureInfo.InvariantCulture)",
            "System.DateTimeOffset" => $"{valueAccessor}.ToString(\"O\", global::System.Globalization.CultureInfo.InvariantCulture)",
            "System.DateOnly" => $"{valueAccessor}.ToString(\"yyyy-MM-dd\", global::System.Globalization.CultureInfo.InvariantCulture)",
            "System.TimeOnly" => $"{valueAccessor}.ToString(\"HH:mm:ss.FFFFFFF\", global::System.Globalization.CultureInfo.InvariantCulture)",
            "string" => isNullable ? $"{accessor}!" : accessor,
            _ => $"{accessor}.ToString()!"
        };
    }

    private static string BuildRouteInterpolation(StringBuilder sb, string route, List<(string ParamName, IPropertySymbol Property)> routeParamProperties)
    {
        var result = route;
        foreach (var (paramName, prop) in routeParamProperties)
        {
            var localVarName = $"__route_{paramName}__";
            var valueExpr = FormatValueExpression($"request.{prop.Name}", prop.Type, false);
            sb.AppendLine($"            var {localVarName} = global::System.Uri.EscapeDataString({valueExpr});");

            var pattern = "{" + paramName + "}";
            var replacement = $"{{{localVarName}}}";
            var idx = result.IndexOf(pattern, StringComparison.OrdinalIgnoreCase);
            if (idx >= 0)
            {
                result = result.Substring(0, idx) + replacement + result.Substring(idx + pattern.Length);
            }
        }

        return "$\"" + result + "\"";
    }

    private static string GetHttpMethod(HttpVerb verb) => verb switch
    {
        HttpVerb.Get => "HttpMethod.Get",
        HttpVerb.Post => "HttpMethod.Post",
        HttpVerb.Put => "HttpMethod.Put",
        HttpVerb.Delete => "HttpMethod.Delete",
        HttpVerb.Patch => "HttpMethod.Patch",
        _ => throw new ArgumentOutOfRangeException(nameof(verb), verb, null)
    };

    private static bool IsBodyMethod(HttpVerb verb)
        => verb == HttpVerb.Post || verb == HttpVerb.Put || verb == HttpVerb.Patch;
}
