using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Contract.SourceGenerator;

[Generator]
public sealed class HttpRpcClientGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var interfaceProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is InterfaceDeclarationSyntax,
                static (ctx, _) =>
                {
                    if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol interfaceSymbol
                        || !RpcServiceHelpers.IsRpcServiceInterface(interfaceSymbol)
                        || interfaceSymbol.ToDisplayString() == RpcServiceHelpers.RpcServiceInterfaceFqn
                        || !RpcServiceHelpers.TryGetHttpTransport(interfaceSymbol, out var _transport))
                    {
                        return null;
                    }

                    return interfaceSymbol;
                })
            .Where(static symbol => symbol is not null);

        context.RegisterSourceOutput(interfaceProvider.Collect(), Generate);
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> interfaces)
    {
        foreach (var serviceInterface in interfaces.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            GenerateForInterface(context, serviceInterface);
        }
    }

    private static void GenerateForInterface(SourceProductionContext context, INamedTypeSymbol serviceInterface)
    {
        if (!RpcServiceHelpers.TryGetHttpTransport(serviceInterface, out var transport))
        {
            return;
        }

        var methods = GetServiceMethods(serviceInterface);
        if (methods.Count == 0)
        {
            return;
        }

        var targetNamespace = RpcServiceHelpers.GetFullNamespace(serviceInterface.ContainingNamespace);
        var typeParameters = RpcServiceHelpers.GetTypeParameterList(serviceInterface.TypeParameters);
        var clientName = RpcServiceHelpers.GetHttpClientName(serviceInterface.Name) + typeParameters;
        var clientInterfaceName = RpcServiceHelpers.GetClientInterfaceName(serviceInterface.Name) + typeParameters;
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine();
        if (!string.IsNullOrWhiteSpace(targetNamespace))
        {
            sb.AppendLine($"namespace {targetNamespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    public partial class {clientName} : {clientInterfaceName}");
        RpcServiceHelpers.AppendTypeParameterConstraints(sb, serviceInterface, 1);
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::System.Net.Http.HttpClient _httpClient;");
        sb.AppendLine("        private readonly global::NOF.Contract.IRequestOutboundPipelineExecutor? _outboundPipeline;");
        sb.AppendLine("        private static readonly global::System.Text.Json.JsonSerializerOptions _jsonOptions = global::System.Text.Json.JsonSerializerOptions.NOF;");
        sb.AppendLine();
        for (var i = 0; i < methods.Count; i++)
        {
            EmitMethodInfoField(sb, methods[i], i);
        }

        sb.AppendLine();
        sb.AppendLine($"        public {RpcServiceHelpers.GetHttpClientName(serviceInterface.Name)}(global::System.Net.Http.HttpClient httpClient, global::NOF.Contract.IRequestOutboundPipelineExecutor? outboundPipeline = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(httpClient);");
        sb.AppendLine("            _httpClient = httpClient;");
        sb.AppendLine("            _outboundPipeline = outboundPipeline;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T> GetJsonTypeInfo<T>()");
        sb.AppendLine("            => _jsonOptions.GetRequiredTypeInfo<T>();");
        sb.AppendLine();

        for (var i = 0; i < methods.Count; i++)
        {
            EmitHttpMethodBody(sb, methods[i], transport, GetMethodInfoFieldName(methods[i], i));
        }

        sb.AppendLine("    }");
        if (!string.IsNullOrWhiteSpace(targetNamespace))
        {
            sb.AppendLine("}");
        }

        context.AddSource(GetHintName(serviceInterface, "HttpRpcClient"), SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static List<ServiceMethodInfo> GetServiceMethods(INamedTypeSymbol serviceInterface)
    {
        var methods = new List<ServiceMethodInfo>();
        foreach (var member in serviceInterface.GetMembers())
        {
            if (member is not IMethodSymbol { MethodKind: MethodKind.Ordinary } method
                || method.IsImplicitlyDeclared
                || !RpcServiceHelpers.TryGetRequestParameter(method, out var requestParameter)
                || requestParameter?.Type is not INamedTypeSymbol requestType
                || !RpcServiceHelpers.TryGetServiceReturnInfo(method, out var returnInfo))
            {
                continue;
            }

            methods.Add(new ServiceMethodInfo
            {
                Method = method,
                RequestType = requestType,
                ReturnInfo = returnInfo,
                OperationName = method.Name
            });
        }

        return methods;
    }

    private static void EmitMethodInfoField(StringBuilder sb, ServiceMethodInfo method, int index)
    {
        var serviceTypeName = method.Method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var parameterTypes = method.Method.Parameters
            .Select(static parameter => $"typeof({parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})")
            .ToArray();
        var parameterTypesExpression = parameterTypes.Length == 0
            ? "global::System.Type.EmptyTypes"
            : $"[{string.Join(", ", parameterTypes)}]";
        var fieldName = GetMethodInfoFieldName(method, index);

        sb.AppendLine($"        private static readonly global::System.Reflection.MethodInfo {fieldName} =");
        sb.AppendLine($"            typeof({serviceTypeName}).GetMethod(nameof({serviceTypeName}.{method.Method.Name}), {parameterTypesExpression})");
        sb.AppendLine($"            ?? throw new global::System.InvalidOperationException(\"Unable to resolve method '{serviceTypeName}.{method.Method.Name}'.\");");
    }

    private static void EmitHttpMethodBody(
        StringBuilder sb,
        ServiceMethodInfo method,
        HttpTransportInfo transport,
        string methodInfoFieldName)
    {
        var endpoint = RpcServiceHelpers.ExtractEndpointInfo(method);
        var requestType = endpoint.RequestType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var responseType = endpoint.ReturnInfo.ClientResponseTypeDisplay;
        var serviceType = method.Method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var isStreaming = endpoint.ReturnInfo.IsStream;
        var streamItemType = endpoint.ReturnInfo.StreamItemType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.AppendLine($"        public virtual async {endpoint.ReturnInfo.ClientTaskReturnTypeDisplay} {method.Method.Name}Async({requestType} request, global::NOF.Contract.Context context, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(request);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("            var outboundContext = new global::NOF.Contract.RequestOutboundContext(context)");
        sb.AppendLine("            {");
        sb.AppendLine($"                ServiceType = typeof({serviceType}),");
        sb.AppendLine($"                MethodInfo = {methodInfoFieldName}");
        sb.AppendLine("            };");
        sb.AppendLine($"            {responseType}? result = default;");
        sb.AppendLine("            global::NOF.Contract.RequestOutboundHandlerDelegate dispatch = async (currentContext, currentRequest, ct) =>");
        sb.AppendLine("            {");

        if (transport.Style == HttpRpcStyle.JsonRpc)
        {
            var jsonRpcRoute = NormalizeRoute(transport.RoutePrefix ?? "/");
            if (isStreaming)
            {
                sb.AppendLine($"                result = await global::NOF.Contract.JsonRpcHttpClient.SendStreamingAsync<{requestType}, {streamItemType}>(");
            }
            else
            {
                sb.AppendLine($"                result = await global::NOF.Contract.JsonRpcHttpClient.SendAsync<{requestType}, {responseType}>(");
            }

            sb.AppendLine("                    _httpClient,");
            sb.AppendLine($"                    {Literal(jsonRpcRoute)},");
            sb.AppendLine($"                    nameof({serviceType}.{method.Method.Name}),");
            sb.AppendLine($"                    ({requestType})currentRequest,");
            sb.AppendLine("                    currentContext.Headers,");
            sb.AppendLine($"                    GetJsonTypeInfo<{requestType}>(),");
            if (isStreaming)
            {
                sb.AppendLine($"                    GetJsonTypeInfo<{streamItemType}>(),");
                sb.AppendLine("                    GetJsonTypeInfo<global::NOF.Contract.Result>(),");
            }
            else
            {
                sb.AppendLine($"                    GetJsonTypeInfo<{responseType}>(),");
            }

            sb.AppendLine("                    ct).ConfigureAwait(false);");
        }
        else
        {
            EmitControllerRpcDispatch(sb, endpoint, transport.RoutePrefix, requestType, responseType, isStreaming, streamItemType);
        }

        sb.AppendLine("                currentContext.Response = result;");
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine("            if (_outboundPipeline is null)");
        sb.AppendLine("            {");
        sb.AppendLine("                await dispatch(outboundContext, request, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("            }");
        sb.AppendLine("            else");
        sb.AppendLine("            {");
        sb.AppendLine("                await _outboundPipeline.ExecuteAsync(outboundContext, request, dispatch, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine($"            return global::NOF.Contract.ResultProjection.RequireCompatible<{responseType}>(");
        sb.AppendLine("                outboundContext.Response ?? throw new global::System.InvalidOperationException(\"RPC call returned a null response.\"));");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitControllerRpcDispatch(
        StringBuilder sb,
        EndpointInfo endpoint,
        string? routePrefix,
        string requestType,
        string responseType,
        bool isStreaming,
        string? streamItemType)
    {
        var route = BuildRoute(routePrefix, endpoint.Route ?? endpoint.OperationName);
        var httpMethod = GetHttpMethod(endpoint.Method);
        sb.AppendLine($"                var endpoint = {Literal(route)};");
        if (IsBodyMethod(endpoint.Method))
        {
            sb.AppendLine($"                using var httpRequest = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.{httpMethod}, endpoint);");
            sb.AppendLine($"                httpRequest.Content = global::System.Net.Http.Json.JsonContent.Create(({requestType})currentRequest, GetJsonTypeInfo<{requestType}>());");
        }
        else
        {
            var properties = RpcServiceHelpers.GetAllPublicProperties(endpoint.RequestType!);
            if (properties.Count > 0)
            {
                sb.AppendLine("                var queryParts = new global::System.Collections.Generic.List<string>();");
                foreach (var property in properties)
                {
                    EmitQueryParamAppend(sb, property, requestType);
                }

                sb.AppendLine("                if (queryParts.Count > 0)");
                sb.AppendLine("                {");
                sb.AppendLine("                    endpoint = endpoint + \"?\" + string.Join(\"&\", queryParts);");
                sb.AppendLine("                }");
            }

            sb.AppendLine($"                using var httpRequest = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.{httpMethod}, endpoint);");
        }

        if (isStreaming)
        {
            sb.AppendLine("                httpRequest.Headers.Accept.Add(new global::System.Net.Http.Headers.MediaTypeWithQualityHeaderValue(\"text/event-stream\"));");
        }

        sb.AppendLine("                foreach (var (name, value) in currentContext.Headers)");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (value is not null)");
        sb.AppendLine("                    {");
        sb.AppendLine("                        httpRequest.Headers.Remove(name);");
        sb.AppendLine("                        httpRequest.Headers.TryAddWithoutValidation(name, value);");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");

        if (isStreaming)
        {
            sb.AppendLine("                var response = await _httpClient.SendAsync(httpRequest, global::System.Net.Http.HttpCompletionOption.ResponseHeadersRead, ct).ConfigureAwait(false);");
            sb.AppendLine("                if (!response.IsSuccessStatusCode)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    result = await global::NOF.Contract.HttpRpcTransportResultReader.ReadFailureAsync<global::NOF.Contract.StreamingResult<{streamItemType}>>(response, ct).ConfigureAwait(false);");
            sb.AppendLine("                }");
            sb.AppendLine("                else if (string.Equals(response.Content.Headers.ContentType?.MediaType, \"text/event-stream\", global::System.StringComparison.OrdinalIgnoreCase))");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var stream = global::NOF.Contract.SseResponseReader.ReadAsync<{streamItemType}>(response, GetJsonTypeInfo<{streamItemType}>(), ct);");
            sb.AppendLine($"                    result = global::NOF.Contract.Result.Stream<{streamItemType}>(stream);");
            sb.AppendLine("                }");
            sb.AppendLine("                else");
            sb.AppendLine("                {");
            sb.AppendLine("                    using (response)");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        result = await global::NOF.Contract.HttpRpcTransportResultReader.ReadStreamingFallbackAsync<{streamItemType}>(response, GetJsonTypeInfo<global::NOF.Contract.Result>(), ct).ConfigureAwait(false);");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
        }
        else
        {
            sb.AppendLine("                using var response = await _httpClient.SendAsync(httpRequest, ct).ConfigureAwait(false);");
            sb.AppendLine($"                result = await global::NOF.Contract.HttpRpcTransportResultReader.ReadAsync<{responseType}>(response, GetJsonTypeInfo<{responseType}>(), ct).ConfigureAwait(false);");
        }
    }

    private static void EmitQueryParamAppend(StringBuilder sb, IPropertySymbol property, string requestType)
    {
        var propertyName = property.Name;
        var accessor = $"(({requestType})currentRequest).{propertyName}";
        var isNullable = property.Type.NullableAnnotation == NullableAnnotation.Annotated
            || property.Type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
        if (isNullable)
        {
            sb.AppendLine($"                if ({accessor} is not null)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    queryParts.Add(global::System.Uri.EscapeDataString({Literal(propertyName)}) + \"=\" + global::System.Uri.EscapeDataString({FormatValueExpression(accessor, property.Type, true)}));");
            sb.AppendLine("                }");
        }
        else
        {
            sb.AppendLine($"                queryParts.Add(global::System.Uri.EscapeDataString({Literal(propertyName)}) + \"=\" + global::System.Uri.EscapeDataString({FormatValueExpression(accessor, property.Type, false)}));");
        }
    }

    internal static string FormatValueExpression(string accessor, ITypeSymbol type, bool isNullable)
    {
        var underlying = type;
        var isNullableValueType = false;
        if (isNullable && type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullable)
        {
            underlying = nullable.TypeArguments[0];
            isNullableValueType = true;
        }

        var valueAccessor = isNullableValueType ? $"{accessor}.Value" : accessor;
        return underlying.ToDisplayString() switch
        {
            "System.DateTime" => $"{valueAccessor}.ToString(\"O\", global::System.Globalization.CultureInfo.InvariantCulture)",
            "System.DateTimeOffset" => $"{valueAccessor}.ToString(\"O\", global::System.Globalization.CultureInfo.InvariantCulture)",
            "System.DateOnly" => $"{valueAccessor}.ToString(\"yyyy-MM-dd\", global::System.Globalization.CultureInfo.InvariantCulture)",
            "System.TimeOnly" => $"{valueAccessor}.ToString(\"HH:mm:ss.FFFFFFF\", global::System.Globalization.CultureInfo.InvariantCulture)",
            "string" => isNullable ? $"{accessor}!" : accessor,
            _ => $"{accessor}.ToString()!"
        };
    }

    private static string GetMethodInfoFieldName(ServiceMethodInfo method, int index)
        => $"__{method.Method.Name}MethodInfo_{index}";

    private static string GetHintName(INamedTypeSymbol symbol, string suffix)
    {
        var builder = new StringBuilder(symbol.ToDisplayString().Length + suffix.Length + 5);
        foreach (var character in symbol.ToDisplayString())
        {
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        return builder.Append('.').Append(suffix).Append(".g.cs").ToString();
    }

    private static string BuildRoute(string? prefix, string route)
    {
        if (string.IsNullOrEmpty(prefix))
        {
            return NormalizeRoute(route);
        }

        var normalizedPrefix = NormalizeRoute(prefix!).TrimEnd('/');
        var normalizedRoute = NormalizeRoute(route);
        return normalizedPrefix + normalizedRoute;
    }

    private static string NormalizeRoute(string route)
    {
        route = route.TrimEnd('/');
        if (string.IsNullOrEmpty(route))
        {
            return "/";
        }

        return route.StartsWith("/", StringComparison.Ordinal) ? route : "/" + route;
    }

    private static string Literal(string value)
        => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);

    private static string GetHttpMethod(HttpVerb verb) => verb switch
    {
        HttpVerb.Get => "HttpMethod.Get",
        HttpVerb.Post => "HttpMethod.Post",
        HttpVerb.Put => "HttpMethod.Put",
        HttpVerb.Delete => "HttpMethod.Delete",
        HttpVerb.Patch => "HttpMethod.Patch",
        _ => throw new ArgumentOutOfRangeException(nameof(verb), verb, null)
    };

    private static bool IsBodyMethod(HttpVerb verb)
        => verb is HttpVerb.Post or HttpVerb.Put or HttpVerb.Patch;
}
