using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Contract.SourceGenerator;

[Generator]
public sealed class RpcServiceClientGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var interfaceProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is InterfaceDeclarationSyntax,
                static (ctx, _) =>
                {
                    if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol interfaceSymbol)
                    {
                        return null;
                    }

                    return RpcServiceHelpers.IsRpcServiceInterface(interfaceSymbol)
                           && interfaceSymbol.ToDisplayString() != RpcServiceHelpers.RpcServiceInterfaceFqn
                        ? interfaceSymbol
                        : null;
                })
            .Where(static symbol => symbol is not null);

        context.RegisterSourceOutput(interfaceProvider.Collect(), Generate);
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> interfaces)
    {
        if (interfaces.IsDefaultOrEmpty)
        {
            return;
        }

        foreach (var serviceInterface in interfaces.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            GenerateForInterface(context, serviceInterface);
        }
    }

    private static void GenerateForInterface(SourceProductionContext context, INamedTypeSymbol serviceInterface)
    {
        var methods = serviceInterface.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary && !m.IsImplicitlyDeclared)
            .Select(m => new
            {
                Method = m,
                HasRequest = RpcServiceHelpers.TryGetRequestParameter(m, out var requestParameter),
                Request = requestParameter,
                HasReturn = RpcServiceHelpers.TryGetServiceReturnInfo(m, out var returnInfo),
                ReturnInfo = returnInfo
            })
            .Where(x => x.HasRequest && x.HasReturn && x.Request is not null)
            .ToList();

        if (methods.Count == 0)
        {
            return;
        }

        var ns = RpcServiceHelpers.GetFullNamespace(serviceInterface.ContainingNamespace);
        var clientName = RpcServiceHelpers.GetClientInterfaceName(serviceInterface.Name)
            + RpcServiceHelpers.GetTypeParameterList(serviceInterface.TypeParameters);
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    public interface {clientName} : global::NOF.Contract.IRpcClient");
        RpcServiceHelpers.AppendTypeParameterConstraints(sb, serviceInterface, 1);
        sb.AppendLine("    {");

        foreach (var method in methods)
        {
            var requestType = method.Request!.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"        {method.ReturnInfo.ClientTaskReturnTypeDisplay} {method.Method.Name}Async({requestType} request, global::NOF.Contract.Context context, global::System.Threading.CancellationToken cancellationToken = default);");
        }

        sb.AppendLine("    }");
        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.AppendLine("}");
        }

        context.AddSource(GetHintName(serviceInterface, "RpcClient"), SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string GetHintName(INamedTypeSymbol symbol, string suffix)
    {
        var builder = new StringBuilder(symbol.ToDisplayString().Length + suffix.Length + 5);
        foreach (var character in symbol.ToDisplayString())
        {
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        builder.Append('.');
        builder.Append(suffix);
        builder.Append(".g.cs");
        return builder.ToString();
    }
}
