using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Infrastructure.SourceGenerator;

[Generator]
public sealed class LocalRpcClientGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor _unsupportedClientReturnType = new(
        id: "NOF030",
        title: "Local RPC client method must use RPC transport return type",
        messageFormat: "Local RPC client method '{0}' must return '{1}' to match the RPC transport contract signature",
        category: "LocalRpcClientGenerator",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) =>
                {
                    if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol classSymbol)
                    {
                        return null;
                    }

                    return TryGetRpcClientInterfaceFromLocalRpcClientAttribute(classSymbol, out var _, out var _) ? classSymbol : null;
                })
            .Where(static symbol => symbol is not null);

        context.RegisterSourceOutput(classProvider.Collect(), Generate);
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> classes)
    {
        if (classes.IsDefaultOrEmpty)
        {
            return;
        }

        foreach (var targetClass in classes.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            GenerateForTargetClass(context, targetClass);
        }
    }

    private static void GenerateForTargetClass(SourceProductionContext context, INamedTypeSymbol targetClass)
    {
        if (!TryGetRpcClientInterfaceFromLocalRpcClientAttribute(targetClass, out var clientInterface, out var serviceInterface)
            || clientInterface is null
            || serviceInterface is null)
        {
            return;
        }

        var clientMethods = clientInterface.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary && !m.IsImplicitlyDeclared)
            .ToList();

        if (clientMethods.Count == 0)
        {
            return;
        }

        foreach (var method in clientMethods)
        {
            if (!IsSupportedClientMethod(method, serviceInterface, out var expectedReturnType))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    _unsupportedClientReturnType,
                    method.Locations.FirstOrDefault(),
                    method.ToDisplayString(),
                    expectedReturnType ?? "a normalized contract return type"));
                return;
            }
        }

        var targetNamespace = RpcClientHelpers.GetFullNamespace(targetClass.ContainingNamespace);
        var clientInterfaceNamespace = RpcClientHelpers.GetFullNamespace(clientInterface.ContainingNamespace);
        var fullyQualifiedClientInterfaceName = string.IsNullOrWhiteSpace(clientInterfaceNamespace)
            ? clientInterface.Name
            : $"{clientInterfaceNamespace}.{clientInterface.Name}";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {targetNamespace}");
        sb.AppendLine("{");
        // No accessibility modifier here; the user-authored partial declaration decides visibility.
        sb.AppendLine($"    partial class {targetClass.Name} : global::{fullyQualifiedClientInterfaceName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::System.IServiceProvider _serviceProvider;");
        sb.AppendLine();
        for (var i = 0; i < clientMethods.Count; i++)
        {
            EmitMethodInfoField(sb, clientMethods[i], serviceInterface, i);
        }

        sb.AppendLine();
        sb.AppendLine($"        public {targetClass.Name}(global::System.IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(serviceProvider);");
        sb.AppendLine("            _serviceProvider = serviceProvider;");
        sb.AppendLine("        }");
        sb.AppendLine();

        for (var i = 0; i < clientMethods.Count; i++)
        {
            EmitMethod(sb, clientMethods[i], serviceInterface, GetMethodInfoFieldName(clientMethods[i], i));
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{targetClass.ToDisplayString().Replace('.', '_')}.LocalRpcClient.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitMethodInfoField(StringBuilder sb, IMethodSymbol method, INamedTypeSymbol serviceInterface, int index)
    {
        var serviceType = serviceInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var operationName = method.Name.EndsWith("Async", System.StringComparison.Ordinal)
            ? method.Name.Substring(0, method.Name.Length - 5)
            : method.Name;
        var operationNameExpression = $"nameof({serviceType}.{operationName})";
        var fieldName = GetMethodInfoFieldName(method, index);
        var parameterTypes = method.Parameters
            .Take(1)
            .Select(static parameter => $"typeof({parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})")
            .ToArray();
        var parameterTypesExpression = parameterTypes.Length == 0
            ? "global::System.Type.EmptyTypes"
            : $"[{string.Join(", ", parameterTypes)}]";

        sb.AppendLine($"        private static readonly global::System.Reflection.MethodInfo {fieldName} =");
        sb.AppendLine($"            typeof({serviceType}).GetMethod({operationNameExpression}, {parameterTypesExpression})");
        sb.AppendLine($"            ?? throw new global::System.InvalidOperationException(\"Unable to resolve method '{serviceType}.{operationName}'.\");");
    }

    private static string GetMethodInfoFieldName(IMethodSymbol method, int index)
        => $"__{method.Name}MethodInfo_{index}";

    private static void EmitMethod(StringBuilder sb, IMethodSymbol method, INamedTypeSymbol serviceInterface, string methodInfoFieldName)
    {
        if (method.Parameters.Length == 0)
        {
            return;
        }

        var requestParameter = method.Parameters[0];
        var requestType = requestParameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var serviceType = serviceInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.RequiresDynamicCode(\"Local RPC response projection may require generic instantiation at runtime.\")]");
        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode(\"Local RPC response projection may require reflective access to generic result helpers.\")]");
        sb.AppendLine($"        public async {returnType} {method.Name}({requestType} {requestParameter.Name}, global::NOF.Contract.Context context, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine($"            var result = await global::NOF.Infrastructure.RpcServerInvoker.InvokeAsync<{serviceType}>(_serviceProvider, {methodInfoFieldName}, {requestParameter.Name}, context, cancellationToken).ConfigureAwait(false);");
        if (method.ReturnType is INamedTypeSymbol { Name: "Task", ContainingNamespace: { Name: "Tasks", ContainingNamespace: { Name: "Threading", ContainingNamespace: { Name: "System" } } } } taskType)
        {
            if (taskType.IsGenericType && taskType.TypeArguments.Length == 1)
            {
                sb.AppendLine($"            return {BuildResponseConversionExpression(taskType.TypeArguments[0], "result")};");
            }
            else
            {
                sb.AppendLine("            return;");
            }
        }
        else if (method.ReturnType is INamedTypeSymbol { Name: "ValueTask", ContainingNamespace: { Name: "Tasks", ContainingNamespace: { Name: "Threading", ContainingNamespace: { Name: "System" } } } } valueTaskType)
        {
            if (valueTaskType.IsGenericType && valueTaskType.TypeArguments.Length == 1)
            {
                sb.AppendLine($"            return {BuildResponseConversionExpression(valueTaskType.TypeArguments[0], "result")};");
            }
            else
            {
                sb.AppendLine("            return;");
            }
        }
        else
        {
            sb.AppendLine($"            return {BuildResponseConversionExpression(method.ReturnType, "result")};");
        }
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static string BuildResponseConversionExpression(ITypeSymbol returnType, string valueExpression)
    {
        var requiredResultExpression = BuildRequiredRpcResultExpression(valueExpression);

        if (returnType is INamedTypeSymbol namedType
            && namedType.ContainingNamespace.ToDisplayString() == "NOF.Contract")
        {
            if (namedType.Name == "RpcResult" && namedType.IsGenericType && namedType.TypeArguments.Length == 1)
            {
                var innerType = namedType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                return $"global::NOF.Contract.RpcResults.From<{innerType}>({requiredResultExpression})";
            }

            if (namedType.Name == "Result" && !namedType.IsGenericType)
            {
                return $"global::NOF.Contract.RpcResults.RequireBody<global::NOF.Contract.Result>({requiredResultExpression})";
            }

            if (namedType.Name == "Result" && namedType.IsGenericType && namedType.TypeArguments.Length == 1)
            {
                var innerType = namedType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                return $"global::NOF.Contract.RpcResults.RequireBody<global::NOF.Contract.Result<{innerType}>>({requiredResultExpression})";
            }

            if (namedType.Name == "StreamingResult" && namedType.IsGenericType && namedType.TypeArguments.Length == 1)
            {
                var itemType = namedType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                return $"global::NOF.Contract.RpcResults.RequireBody<global::NOF.Contract.StreamingResult<{itemType}>>({requiredResultExpression})";
            }
        }

        throw new global::System.InvalidOperationException($"Unsupported local RPC client return type '{returnType.ToDisplayString()}'.");
    }

    private static string BuildRequiredRpcResultExpression(string valueExpression)
    {
        return $"{valueExpression} ?? throw new global::System.InvalidOperationException(\"RPC call returned a null response.\")";
    }

    private static bool IsSupportedClientMethod(IMethodSymbol clientMethod, INamedTypeSymbol serviceInterface, out string? expectedReturnType)
    {
        expectedReturnType = null;

        var operationName = clientMethod.Name.EndsWith("Async", System.StringComparison.Ordinal)
            ? clientMethod.Name.Substring(0, clientMethod.Name.Length - 5)
            : clientMethod.Name;

        var serviceMethod = serviceInterface.GetMembers()
            .OfType<IMethodSymbol>()
            .FirstOrDefault(m => m.MethodKind == MethodKind.Ordinary
                && !m.IsImplicitlyDeclared
                && m.Name == operationName);
        if (serviceMethod is null)
        {
            return true;
        }

        expectedReturnType = BuildExpectedClientReturnTypeDisplay(serviceMethod);
        return clientMethod.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == expectedReturnType;
    }

    private static string BuildExpectedClientReturnTypeDisplay(IMethodSymbol serviceMethod)
    {
        var transportResponseType = BuildTransportClientResponseTypeDisplay(serviceMethod.ReturnType);
        return $"global::System.Threading.Tasks.Task<{transportResponseType}>";
    }

    private static string BuildTransportClientResponseTypeDisplay(ITypeSymbol returnType)
    {
        return $"global::NOF.Contract.RpcResult<{returnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>";
    }

    private static bool TryGetRpcClientInterfaceFromLocalRpcClientAttribute(
        INamedTypeSymbol classSymbol,
        out INamedTypeSymbol? clientInterface,
        out INamedTypeSymbol? serviceInterface)
    {
        serviceInterface = null;
        if (!RpcClientHelpers.TryGetRpcClientFromLocalRpcClientAttribute(classSymbol, out clientInterface)
            || clientInterface is null)
        {
            return false;
        }

        return RpcClientHelpers.TryGetRpcServiceFromClientInterface(clientInterface, out serviceInterface);
    }
}
