using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Infrastructure.SourceGenerator;

[Generator]
public sealed class LocalRpcClientGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) =>
                {
                    if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol classSymbol)
                    {
                        return null;
                    }

                    return TryGetRpcClientInterfaceFromLocalRpcClientAttribute(classSymbol, out var _, out var _) ? classSymbol : null;
                })
            .Where(static symbol => symbol is not null);

        context.RegisterSourceOutput(classProvider.Collect(), Generate);
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> classes)
    {
        if (classes.IsDefaultOrEmpty)
        {
            return;
        }

        foreach (var targetClass in classes.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            GenerateForTargetClass(context, targetClass);
        }
    }

    private static void GenerateForTargetClass(SourceProductionContext context, INamedTypeSymbol targetClass)
    {
        if (!TryGetRpcClientInterfaceFromLocalRpcClientAttribute(targetClass, out var clientInterface, out var serviceInterface)
            || clientInterface is null
            || serviceInterface is null)
        {
            return;
        }

        var clientMethods = clientInterface.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary && !m.IsImplicitlyDeclared)
            .ToList();

        if (clientMethods.Count == 0)
        {
            return;
        }

        var targetNamespace = RpcClientHelpers.GetFullNamespace(targetClass.ContainingNamespace);
        var clientInterfaceNamespace = RpcClientHelpers.GetFullNamespace(clientInterface.ContainingNamespace);
        var fullyQualifiedClientInterfaceName = string.IsNullOrWhiteSpace(clientInterfaceNamespace)
            ? clientInterface.Name
            : $"{clientInterfaceNamespace}.{clientInterface.Name}";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {targetNamespace}");
        sb.AppendLine("{");
        // No accessibility modifier here; the user-authored partial declaration decides visibility.
        sb.AppendLine($"    partial class {targetClass.Name} : global::{fullyQualifiedClientInterfaceName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::System.IServiceProvider _serviceProvider;");
        sb.AppendLine();
        sb.AppendLine($"        public {targetClass.Name}(global::System.IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(serviceProvider);");
        sb.AppendLine("            _serviceProvider = serviceProvider;");
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach (var method in clientMethods)
        {
            EmitMethod(sb, method, serviceInterface);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{targetClass.ToDisplayString().Replace('.', '_')}.LocalRpcClient.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitMethod(StringBuilder sb, IMethodSymbol method, INamedTypeSymbol serviceInterface)
    {
        if (method.Parameters.Length == 0)
        {
            return;
        }

        var requestParameter = method.Parameters[0];
        var requestType = requestParameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var serviceType = serviceInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var operationName = method.Name.EndsWith("Async", System.StringComparison.Ordinal)
            ? method.Name.Substring(0, method.Name.Length - 5)
            : method.Name;
        var operationNameExpression = $"nameof({serviceType}.{operationName})";

        sb.AppendLine($"        public async {returnType} {method.Name}({requestType} {requestParameter.Name}, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var result = await global::NOF.Infrastructure.RpcServerInvoker.InvokeAsync<{serviceType}>(_serviceProvider, {operationNameExpression}, {requestParameter.Name}, cancellationToken).ConfigureAwait(false);");
        // Most clients return Task<T>. In an async Task<T> method we must return T, not Task<T>.
        if (method.ReturnType is INamedTypeSymbol { Name: "Task", ContainingNamespace: { Name: "Tasks", ContainingNamespace: { Name: "Threading", ContainingNamespace: { Name: "System" } } } } taskType)
        {
            if (taskType.IsGenericType && taskType.TypeArguments.Length == 1)
            {
                sb.AppendLine($"            return {BuildResultConversionExpression(taskType.TypeArguments[0], "result!")} ;");
            }
            else
            {
                sb.AppendLine("            return;");
            }
        }
        else if (method.ReturnType is INamedTypeSymbol { Name: "ValueTask", ContainingNamespace: { Name: "Tasks", ContainingNamespace: { Name: "Threading", ContainingNamespace: { Name: "System" } } } } valueTaskType)
        {
            if (valueTaskType.IsGenericType && valueTaskType.TypeArguments.Length == 1)
            {
                sb.AppendLine($"            return {BuildResultConversionExpression(valueTaskType.TypeArguments[0], "result!")} ;");
            }
            else
            {
                sb.AppendLine("            return;");
            }
        }
        else
        {
            sb.AppendLine($"            return {BuildResultConversionExpression(method.ReturnType, "result!")} ;");
        }
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static string BuildResultConversionExpression(ITypeSymbol returnType, string valueExpression)
    {
        if (returnType is INamedTypeSymbol namedType
            && namedType.ContainingNamespace.ToDisplayString() == "NOF.Contract")
        {
            if (namedType.Name == "Result" && !namedType.IsGenericType)
            {
                return $"global::NOF.Contract.Result.From({valueExpression})";
            }

            if (namedType.Name == "Result" && namedType.IsGenericType && namedType.TypeArguments.Length == 1)
            {
                var innerType = namedType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                return $"global::NOF.Contract.Result.From<{innerType}>({valueExpression})";
            }
        }

        return $"({returnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}){valueExpression}";
    }

    private static bool TryGetRpcClientInterfaceFromLocalRpcClientAttribute(
        INamedTypeSymbol classSymbol,
        out INamedTypeSymbol? clientInterface,
        out INamedTypeSymbol? serviceInterface)
    {
        serviceInterface = null;
        if (!RpcClientHelpers.TryGetRpcClientFromLocalRpcClientAttribute(classSymbol, out clientInterface)
            || clientInterface is null)
        {
            return false;
        }

        return RpcClientHelpers.TryGetRpcServiceFromClientInterface(clientInterface, out serviceInterface);
    }
}
