using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace NOF.Infrastructure.SourceGenerator;

[Generator]
public sealed class LocalRpcClientGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var rpcServers = context.CompilationProvider.Select(
            static (compilation, cancellationToken) => DiscoverRpcServers(compilation, cancellationToken));

        context.RegisterSourceOutput(rpcServers, Generate);
    }

    private static ImmutableArray<INamedTypeSymbol> DiscoverRpcServers(
        Compilation compilation,
        CancellationToken cancellationToken)
    {
        var servers = ImmutableArray.CreateBuilder<INamedTypeSymbol>();
        CollectRpcServers(compilation.Assembly.GlobalNamespace, servers, cancellationToken);

        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (!ReferencesNofApplication(assembly))
            {
                continue;
            }

            CollectRpcServers(assembly.GlobalNamespace, servers, cancellationToken);
        }

        return servers
            .Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default)
            .ToImmutableArray();
    }

    private static bool ReferencesNofApplication(IAssemblySymbol assembly)
        => assembly.Name == "NOF.Application"
           || assembly.Modules.Any(static module =>
               module.ReferencedAssemblySymbols.Any(static reference => reference.Name == "NOF.Application"));

    private static void CollectRpcServers(
        INamespaceSymbol namespaceSymbol,
        ImmutableArray<INamedTypeSymbol>.Builder servers,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        foreach (var type in namespaceSymbol.GetTypeMembers())
        {
            CollectRpcServers(type, servers, cancellationToken);
        }

        foreach (var childNamespace in namespaceSymbol.GetNamespaceMembers())
        {
            CollectRpcServers(childNamespace, servers, cancellationToken);
        }
    }

    private static void CollectRpcServers(
        INamedTypeSymbol type,
        ImmutableArray<INamedTypeSymbol>.Builder servers,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        if (type.TypeKind == TypeKind.Class
            && RpcClientHelpers.TryGetRpcServiceFromRpcServer(type, out _))
        {
            servers.Add(type);
        }

        foreach (var nestedType in type.GetTypeMembers())
        {
            CollectRpcServers(nestedType, servers, cancellationToken);
        }
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> rpcServers)
    {
        foreach (var rpcServer in rpcServers)
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            GenerateForRpcServer(context, rpcServer);
        }
    }

    private static void GenerateForRpcServer(SourceProductionContext context, INamedTypeSymbol rpcServer)
    {
        if (!RpcClientHelpers.TryGetRpcServiceFromRpcServer(rpcServer, out var serviceInterface)
            || serviceInterface is null)
        {
            return;
        }

        // The local generator must not inspect the client interface emitted by the contract
        // generator. Both generators independently derive their output from the service source.
        var serviceMethods = serviceInterface.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(static method => method.MethodKind == MethodKind.Ordinary
                && !method.IsImplicitlyDeclared
                && method.Parameters.Length == 1
                && RpcClientHelpers.ImplementsResultContract(method.ReturnType))
            .ToList();

        if (serviceMethods.Count == 0)
        {
            return;
        }

        var targetNamespace = RpcClientHelpers.GetFullNamespace(rpcServer.ContainingNamespace);
        var fullyQualifiedClientInterfaceName = RpcClientHelpers.GetRpcClientInterfaceTypeName(serviceInterface);
        var localClientName = RpcClientHelpers.GetLocalClientName(rpcServer);
        var localClientDeclarationName = localClientName + RpcClientHelpers.GetTypeParameterList(rpcServer.TypeParameters);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrWhiteSpace(targetNamespace))
        {
            sb.AppendLine($"namespace {targetNamespace}");
            sb.AppendLine("{");
        }

        var indentLevel = string.IsNullOrWhiteSpace(targetNamespace) ? 0 : 1;
        var indent = new string(' ', indentLevel * 4);
        sb.AppendLine($"{indent}public sealed class {localClientDeclarationName} : {fullyQualifiedClientInterfaceName}");
        RpcClientHelpers.AppendTypeParameterConstraints(sb, rpcServer, indentLevel);
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    private readonly global::System.IServiceProvider _serviceProvider;");
        sb.AppendLine();
        for (var i = 0; i < serviceMethods.Count; i++)
        {
            EmitMethodInfoField(sb, serviceMethods[i], serviceInterface, i, indentLevel + 1);
        }

        sb.AppendLine();
        sb.AppendLine($"{indent}    public {localClientName}(global::System.IServiceProvider serviceProvider)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        global::System.ArgumentNullException.ThrowIfNull(serviceProvider);");
        sb.AppendLine($"{indent}        _serviceProvider = serviceProvider;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();

        for (var i = 0; i < serviceMethods.Count; i++)
        {
            EmitMethod(sb, serviceMethods[i], serviceInterface, GetMethodInfoFieldName(serviceMethods[i], i), indentLevel + 1);
        }

        sb.AppendLine($"{indent}}}");
        if (!string.IsNullOrWhiteSpace(targetNamespace))
        {
            sb.AppendLine("}");
        }

        context.AddSource(GetHintName(rpcServer, "LocalRpcClient"), SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitMethodInfoField(
        StringBuilder sb,
        IMethodSymbol method,
        INamedTypeSymbol serviceInterface,
        int index,
        int indentLevel)
    {
        var indent = new string(' ', indentLevel * 4);
        var serviceType = serviceInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var operationNameExpression = $"nameof({serviceType}.{method.Name})";
        var fieldName = GetMethodInfoFieldName(method, index);
        var parameterTypes = method.Parameters
            .Take(1)
            .Select(static parameter => $"typeof({parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})")
            .ToArray();
        var parameterTypesExpression = parameterTypes.Length == 0
            ? "global::System.Type.EmptyTypes"
            : $"[{string.Join(", ", parameterTypes)}]";

        sb.AppendLine($"{indent}private static readonly global::System.Reflection.MethodInfo {fieldName} =");
        sb.AppendLine($"{indent}    typeof({serviceType}).GetMethod({operationNameExpression}, {parameterTypesExpression})");
        sb.AppendLine($"{indent}    ?? throw new global::System.InvalidOperationException(\"Unable to resolve method '{serviceType}.{method.Name}'.\");");
    }

    private static string GetMethodInfoFieldName(IMethodSymbol method, int index)
        => $"__{method.Name}MethodInfo_{index}";

    private static string GetHintName(INamedTypeSymbol symbol, string suffix)
    {
        var builder = new StringBuilder(symbol.ToDisplayString().Length + suffix.Length + 5);
        foreach (var character in symbol.ToDisplayString())
        {
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        builder.Append('.');
        builder.Append(suffix);
        builder.Append(".g.cs");
        return builder.ToString();
    }

    private static void EmitMethod(
        StringBuilder sb,
        IMethodSymbol method,
        INamedTypeSymbol serviceInterface,
        string methodInfoFieldName,
        int indentLevel)
    {
        if (method.Parameters.Length == 0)
        {
            return;
        }

        var indent = new string(' ', indentLevel * 4);
        var requestType = method.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var serviceType = serviceInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.AppendLine($"{indent}[global::System.Diagnostics.CodeAnalysis.RequiresDynamicCode(\"Local RPC failure projection may require generic instantiation at runtime.\")]");
        sb.AppendLine($"{indent}[global::System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode(\"Local RPC failure projection may require reflective access to generic result helpers.\")]");
        sb.AppendLine($"{indent}public async global::System.Threading.Tasks.Task<{returnType}> {method.Name}Async({requestType} request, global::NOF.Contract.Context context, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine($"{indent}    var result = await global::NOF.Infrastructure.RpcServerInvoker.InvokeAsync<{serviceType}>(_serviceProvider, {methodInfoFieldName}, request, context, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine($"{indent}    return {BuildResponseConversionExpression(method.ReturnType, "result")};");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static string BuildResponseConversionExpression(ITypeSymbol returnType, string valueExpression)
    {
        var requiredResultExpression = BuildRequiredResultExpression(valueExpression);
        var returnTypeDisplay = returnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return $"global::NOF.Contract.ResultProjection.RequireCompatible<{returnTypeDisplay}>({requiredResultExpression})";
    }

    private static string BuildRequiredResultExpression(string valueExpression)
        => $"{valueExpression} ?? throw new global::System.InvalidOperationException(\"RPC call returned a null response.\")";
}
