using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NOF.Infrastructure.SourceGenerator;

[Generator]
public sealed class SplitInterfaceServiceGenerator : IIncrementalGenerator
{
    private const string SplitInterfaceServiceAttributeFqn = "NOF.Infrastructure.SplitInterfaceServiceAttribute<TService, TSplitedInterface>";
    private const string ISplitedInterfaceFqn = "NOF.Application.ISplitedInterface<TService>";
    private const string IRpcServiceFqn = "NOF.Contract.IRpcService";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var registrations = context.CompilationProvider
            .Select(static (compilation, _) => CollectRegistrations(compilation));

        context.RegisterSourceOutput(registrations, static (spc, data) => Generate(spc, data));
    }

    private static RegistrationCollection CollectRegistrations(Compilation compilation)
    {
        var registrations = new List<RegistrationInfo>();
        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach (var attribute in compilation.Assembly.GetAttributes())
        {
            if (attribute.AttributeClass is not INamedTypeSymbol { IsGenericType: true } attributeClass
                || attributeClass.OriginalDefinition.ToDisplayString() != SplitInterfaceServiceAttributeFqn
                || attributeClass.TypeArguments.Length != 2
                || attributeClass.TypeArguments[0] is not INamedTypeSymbol serviceType
                || attributeClass.TypeArguments[1] is not INamedTypeSymbol splitedType
                || !IsRpcServiceInterface(serviceType)
                || !ImplementsISplitedInterfaceOfService(splitedType, serviceType))
            {
                continue;
            }

            var key = serviceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (!seen.Add(key))
            {
                continue;
            }

            registrations.Add(new RegistrationInfo(serviceType, splitedType));
        }

        return new RegistrationCollection(compilation.AssemblyName ?? "GeneratedAssembly", registrations);
    }

    private static bool IsRpcServiceInterface(INamedTypeSymbol serviceType)
    {
        if (serviceType.TypeKind != TypeKind.Interface)
        {
            return false;
        }

        if (serviceType.ToDisplayString() == IRpcServiceFqn)
        {
            return true;
        }

        foreach (var i in serviceType.AllInterfaces)
        {
            if (i.ToDisplayString() == IRpcServiceFqn)
            {
                return true;
            }
        }

        return false;
    }

    private static bool ImplementsISplitedInterfaceOfService(INamedTypeSymbol splitedType, INamedTypeSymbol serviceType)
    {
        foreach (var i in splitedType.AllInterfaces)
        {
            if (i.IsGenericType
                && i.OriginalDefinition.ToDisplayString() == ISplitedInterfaceFqn
                && i.TypeArguments.Length == 1
                && SymbolEqualityComparer.Default.Equals(i.TypeArguments[0], serviceType))
            {
                return true;
            }
        }

        return false;
    }

    private static void Generate(SourceProductionContext context, RegistrationCollection data)
    {
        if (data.Registrations.Count == 0)
        {
            return;
        }

        var assemblyName = data.AssemblyName;
        var sanitizedAssemblyName = SanitizeIdentifier(assemblyName.Replace(".", ""));
        var initializerTypeName = $"__{sanitizedAssemblyName}SplitInterfaceServiceAssemblyInitializer";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"[assembly: global::NOF.Annotation.AssemblyInitializeAttribute<global::{assemblyName}.{initializerTypeName}>]");
        sb.AppendLine();
        sb.AppendLine($"namespace {assemblyName}");
        sb.AppendLine("{");

        foreach (var registration in data.Registrations)
        {
            EmitImplementationClass(sb, registration.SplitedType, registration.ServiceType);
        }

        sb.AppendLine($"    internal sealed class {initializerTypeName} : global::NOF.Annotation.IAssemblyInitializer");
        sb.AppendLine("    {");
        sb.AppendLine("        private static int _initialized;");
        sb.AppendLine();
        sb.AppendLine("        public static void Initialize()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (global::System.Threading.Interlocked.Exchange(ref _initialized, 1) == 1)");
        sb.AppendLine("            {");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine();

        foreach (var registration in data.Registrations)
        {
            var serviceFqn = registration.ServiceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var implName = GetImplementationTypeName(registration.SplitedType, registration.ServiceType);
            sb.AppendLine($"            global::NOF.Annotation.AutoInjectRegistry.Register(typeof({serviceFqn}), typeof({implName}), global::NOF.Annotation.Lifetime.Scoped, useFactory: false);");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("SplitInterfaceServiceAssemblyInitializer.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitImplementationClass(StringBuilder sb, INamedTypeSymbol splitedType, INamedTypeSymbol serviceType)
    {
        var serviceFqn = serviceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var splitedFqn = splitedType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var implName = GetImplementationTypeName(splitedType, serviceType);

        sb.AppendLine($"    internal sealed class {implName} : {serviceFqn}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::NOF.Hosting.IOutboundPipelineExecutor _outboundPipeline;");
        sb.AppendLine("        private readonly global::NOF.Hosting.IExecutionContext _executionContext;");
        sb.AppendLine("        private readonly global::System.IServiceProvider _serviceProvider;");
        sb.AppendLine();
        sb.AppendLine($"        public {implName}(global::NOF.Hosting.IOutboundPipelineExecutor outboundPipeline, global::NOF.Hosting.IExecutionContext executionContext, global::System.IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(outboundPipeline);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(executionContext);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(serviceProvider);");
        sb.AppendLine("            _outboundPipeline = outboundPipeline;");
        sb.AppendLine("            _executionContext = executionContext;");
        sb.AppendLine("            _serviceProvider = serviceProvider;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // helper set 1: request + Result
        sb.AppendLine("        private async global::System.Threading.Tasks.Task<global::NOF.Contract.Result> ExecuteRpcAsync_Request_Result<TRequest>(");
        sb.AppendLine("            TRequest request,");
        sb.AppendLine("            global::System.Reflection.MethodInfo methodInfo,");
        sb.AppendLine("            global::System.Type handlerType,");
        sb.AppendLine("            global::System.Func<global::System.IServiceProvider, TRequest, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<global::NOF.Contract.Result>> terminal,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            var outboundContext = new global::NOF.Hosting.OutboundContext { Message = request, Services = _serviceProvider };");
        sb.AppendLine("            await _outboundPipeline.ExecuteAsync(outboundContext, async ct =>");
        sb.AppendLine("            {");
        sb.AppendLine("                await global::NOF.Infrastructure.InboundHandlerInvoker.ExecuteRpcAsync(");
        sb.AppendLine("                    _serviceProvider, request, methodInfo, outboundContext.Headers,");
        sb.AppendLine("                    context => { context.Metadatas[\"HandlerType\"] = handlerType; },");
        sb.AppendLine("                    async (sp, ct2) => { outboundContext.Response = await terminal(sp, request, ct2).ConfigureAwait(false); },");
        sb.AppendLine("                    ct).ConfigureAwait(false);");
        sb.AppendLine("            }, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("            return global::NOF.Contract.Result.From((global::NOF.Contract.IResult)outboundContext.Response!);");
        sb.AppendLine("        }");
        sb.AppendLine();
        // helper set 2: request + Result<T>
        sb.AppendLine("        private async global::System.Threading.Tasks.Task<global::NOF.Contract.Result<TValue>> ExecuteRpcAsync_Request_ResultOfT<TRequest, TValue>(");
        sb.AppendLine("            TRequest request,");
        sb.AppendLine("            global::System.Reflection.MethodInfo methodInfo,");
        sb.AppendLine("            global::System.Type handlerType,");
        sb.AppendLine("            global::System.Func<global::System.IServiceProvider, TRequest, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<global::NOF.Contract.Result<TValue>>> terminal,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            var outboundContext = new global::NOF.Hosting.OutboundContext { Message = request, Services = _serviceProvider };");
        sb.AppendLine("            await _outboundPipeline.ExecuteAsync(outboundContext, async ct =>");
        sb.AppendLine("            {");
        sb.AppendLine("                await global::NOF.Infrastructure.InboundHandlerInvoker.ExecuteRpcAsync(");
        sb.AppendLine("                    _serviceProvider, request, methodInfo, outboundContext.Headers,");
        sb.AppendLine("                    context => { context.Metadatas[\"HandlerType\"] = handlerType; },");
        sb.AppendLine("                    async (sp, ct2) => { outboundContext.Response = await terminal(sp, request, ct2).ConfigureAwait(false); },");
        sb.AppendLine("                    ct).ConfigureAwait(false);");
        sb.AppendLine("            }, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("            return global::NOF.Contract.Result.From<TValue>((global::NOF.Contract.IResult)outboundContext.Response!);");
        sb.AppendLine("        }");
        sb.AppendLine();
        // helper set 3: no request + Result
        sb.AppendLine("        private async global::System.Threading.Tasks.Task<global::NOF.Contract.Result> ExecuteRpcAsync_Result(");
        sb.AppendLine("            global::System.Reflection.MethodInfo methodInfo,");
        sb.AppendLine("            global::System.Type handlerType,");
        sb.AppendLine("            global::System.Func<global::System.IServiceProvider, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<global::NOF.Contract.Result>> terminal,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            var outboundContext = new global::NOF.Hosting.OutboundContext { Message = null, Services = _serviceProvider };");
        sb.AppendLine("            await _outboundPipeline.ExecuteAsync(outboundContext, async ct =>");
        sb.AppendLine("            {");
        sb.AppendLine("                await global::NOF.Infrastructure.InboundHandlerInvoker.ExecuteRpcAsync(");
        sb.AppendLine("                    _serviceProvider, null, methodInfo, outboundContext.Headers,");
        sb.AppendLine("                    context => { context.Metadatas[\"HandlerType\"] = handlerType; },");
        sb.AppendLine("                    async (sp, ct2) => { outboundContext.Response = await terminal(sp, ct2).ConfigureAwait(false); },");
        sb.AppendLine("                    ct).ConfigureAwait(false);");
        sb.AppendLine("            }, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("            return global::NOF.Contract.Result.From((global::NOF.Contract.IResult)outboundContext.Response!);");
        sb.AppendLine("        }");
        sb.AppendLine();
        // helper set 4: no request + Result<T>
        sb.AppendLine("        private async global::System.Threading.Tasks.Task<global::NOF.Contract.Result<TValue>> ExecuteRpcAsync_ResultOfT<TValue>(");
        sb.AppendLine("            global::System.Reflection.MethodInfo methodInfo,");
        sb.AppendLine("            global::System.Type handlerType,");
        sb.AppendLine("            global::System.Func<global::System.IServiceProvider, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<global::NOF.Contract.Result<TValue>>> terminal,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            var outboundContext = new global::NOF.Hosting.OutboundContext { Message = null, Services = _serviceProvider };");
        sb.AppendLine("            await _outboundPipeline.ExecuteAsync(outboundContext, async ct =>");
        sb.AppendLine("            {");
        sb.AppendLine("                await global::NOF.Infrastructure.InboundHandlerInvoker.ExecuteRpcAsync(");
        sb.AppendLine("                    _serviceProvider, null, methodInfo, outboundContext.Headers,");
        sb.AppendLine("                    context => { context.Metadatas[\"HandlerType\"] = handlerType; },");
        sb.AppendLine("                    async (sp, ct2) => { outboundContext.Response = await terminal(sp, ct2).ConfigureAwait(false); },");
        sb.AppendLine("                    ct).ConfigureAwait(false);");
        sb.AppendLine("            }, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("            return global::NOF.Contract.Result.From<TValue>((global::NOF.Contract.IResult)outboundContext.Response!);");
        sb.AppendLine("        }");
        sb.AppendLine();

        var methods = GetServiceMethods(serviceType);
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var method in methods)
        {
            var opName = GetOperationName(method.Name);
            var nestedInterfaceName = opName;
            if (!usedNames.Add(nestedInterfaceName))
            {
                var i = 2;
                while (!usedNames.Add($"{nestedInterfaceName}_{i}"))
                {
                    i++;
                }
                nestedInterfaceName = $"{nestedInterfaceName}_{i}";
            }

            EmitServiceMethod(sb, splitedFqn, nestedInterfaceName, serviceType, method);
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static List<IMethodSymbol> GetServiceMethods(INamedTypeSymbol iface)
    {
        return iface.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary && !m.IsImplicitlyDeclared)
            .ToList();
    }

    private static void EmitServiceMethod(
        StringBuilder sb,
        string splitedFqn,
        string nestedInterfaceName,
        INamedTypeSymbol serviceType,
        IMethodSymbol method)
    {
        if (method.ReturnType is not INamedTypeSymbol { IsGenericType: true } taskType
            || taskType.Name != "Task"
            || taskType.TypeArguments.Length != 1
            || taskType.ContainingNamespace.ToDisplayString() != "System.Threading.Tasks")
        {
            return;
        }

        var resultType = taskType.TypeArguments[0];

        var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var resultTypeFqn = resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var methodName = method.Name;

        // Default values are not required for interface implementation; omit them to avoid mismatches.
        var parametersDecl = string.Join(", ", method.Parameters.Select(p =>
            $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {p.Name}"));

        var hasCancellationToken = method.Parameters.Any(p => p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Threading.CancellationToken");
        var cancellationTokenArg = hasCancellationToken
            ? method.Parameters.First(p => p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Threading.CancellationToken").Name
            : "global::System.Threading.CancellationToken.None";

        // Identify "request" parameter as the first non-ct parameter, if any.
        var requestParam = method.Parameters.FirstOrDefault(p =>
            p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) != "global::System.Threading.CancellationToken");

        var handlerTypeFqn = $"{splitedFqn}.{nestedInterfaceName}";

        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine($"        public {returnType} {methodName}({parametersDecl})");
        sb.AppendLine("        {");

        // Build MethodInfo lookup on the service interface (so attributes on the interface method are visible)
        var paramTypeArray = method.Parameters.Length == 0
            ? "global::System.Type.EmptyTypes"
            : "new global::System.Type[] { " + string.Join(", ", method.Parameters.Select(p => $"typeof({p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})")) + " }";
        var serviceFqn = serviceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        sb.AppendLine($"            var methodInfo = typeof({serviceFqn}).GetMethod(\"{EscapeString(methodName)}\", {paramTypeArray})!;");
        sb.AppendLine($"            var handlerType = typeof({handlerTypeFqn});");
        sb.AppendLine("            var isService = _serviceProvider.GetService<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>();");
        sb.AppendLine("            if (isService is null || !isService.IsService(handlerType))");
        sb.AppendLine("            {");
        sb.AppendLine("                throw new global::System.InvalidOperationException($\"RPC operation implementation is missing: {handlerType.FullName}.\");");
        sb.AppendLine("            }");
        sb.AppendLine();

        var isGenericResult = resultType is INamedTypeSymbol { IsGenericType: true } named && named.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::NOF.Contract.Result<T>";
        if (requestParam is not null)
        {
            var requestType = requestParam.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var requestName = requestParam.Name;

            if (isGenericResult)
            {
                var valueTypeFqn = ((INamedTypeSymbol)resultType).TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"            return ExecuteRpcAsync_Request_ResultOfT<{requestType}, {valueTypeFqn}>(");
                sb.AppendLine($"                {requestName},");
                sb.AppendLine("                methodInfo,");
                sb.AppendLine("                handlerType,");
                sb.AppendLine("                (sp, request, ct) =>");
                sb.AppendLine("                {");
                sb.AppendLine($"                    var handler = sp.GetRequiredService<{handlerTypeFqn}>();");

                var callArgs = new List<string>();
                foreach (var p in method.Parameters)
                {
                    if (p.Equals(requestParam, SymbolEqualityComparer.Default))
                    {
                        callArgs.Add("request");
                    }
                    else if (p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Threading.CancellationToken")
                    {
                        callArgs.Add("ct");
                    }
                    else
                    {
                        // Additional parameters are captured from the outer scope.
                        callArgs.Add(p.Name);
                    }
                }
                sb.AppendLine($"                    return handler.{methodName}({string.Join(", ", callArgs)});");
                sb.AppendLine("                },");
                sb.AppendLine($"                {cancellationTokenArg});");
            }
            else
            {
                sb.AppendLine($"            return ExecuteRpcAsync_Request_Result<{requestType}>(");
                sb.AppendLine($"                {requestName},");
                sb.AppendLine("                methodInfo,");
                sb.AppendLine("                handlerType,");
                sb.AppendLine("                (sp, request, ct) =>");
                sb.AppendLine("                {");
                sb.AppendLine($"                    var handler = sp.GetRequiredService<{handlerTypeFqn}>();");

                var callArgs = new List<string>();
                foreach (var p in method.Parameters)
                {
                    if (p.Equals(requestParam, SymbolEqualityComparer.Default))
                    {
                        callArgs.Add("request");
                    }
                    else if (p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Threading.CancellationToken")
                    {
                        callArgs.Add("ct");
                    }
                    else
                    {
                        callArgs.Add(p.Name);
                    }
                }
                sb.AppendLine($"                    return handler.{methodName}({string.Join(", ", callArgs)});");
                sb.AppendLine("                },");
                sb.AppendLine($"                {cancellationTokenArg});");
            }
        }
        else
        {
            if (isGenericResult)
            {
                var valueTypeFqn = ((INamedTypeSymbol)resultType).TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"            return ExecuteRpcAsync_ResultOfT<{valueTypeFqn}>(");
                sb.AppendLine("                methodInfo,");
                sb.AppendLine("                handlerType,");
                sb.AppendLine("                (sp, ct) =>");
                sb.AppendLine("                {");
                sb.AppendLine($"                    var handler = sp.GetRequiredService<{handlerTypeFqn}>();");

                var callArgs = new List<string>();
                foreach (var p in method.Parameters)
                {
                    if (p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Threading.CancellationToken")
                    {
                        callArgs.Add("ct");
                    }
                    else
                    {
                        callArgs.Add(p.Name);
                    }
                }
                sb.AppendLine($"                    return handler.{methodName}({string.Join(", ", callArgs)});");
                sb.AppendLine("                },");
                sb.AppendLine($"                {cancellationTokenArg});");
            }
            else
            {
                sb.AppendLine($"            return ExecuteRpcAsync_Result(");
                sb.AppendLine("                methodInfo,");
                sb.AppendLine("                handlerType,");
                sb.AppendLine("                (sp, ct) =>");
                sb.AppendLine("                {");
                sb.AppendLine($"                    var handler = sp.GetRequiredService<{handlerTypeFqn}>();");

                var callArgs = new List<string>();
                foreach (var p in method.Parameters)
                {
                    if (p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Threading.CancellationToken")
                    {
                        callArgs.Add("ct");
                    }
                    else
                    {
                        callArgs.Add(p.Name);
                    }
                }
                sb.AppendLine($"                    return handler.{methodName}({string.Join(", ", callArgs)});");
                sb.AppendLine("                },");
                sb.AppendLine($"                {cancellationTokenArg});");
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static string GetOperationName(string methodName)
        => methodName.EndsWith("Async", StringComparison.Ordinal)
            ? methodName.Substring(0, methodName.Length - 5)
            : methodName;

    private static string GetImplementationTypeName(INamedTypeSymbol splitedType, INamedTypeSymbol serviceType)
        => $"__{SanitizeIdentifier(serviceType.ToDisplayString())}_{SanitizeIdentifier(splitedType.ToDisplayString())}_SplitInterfaceService__";

    private static string SanitizeIdentifier(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return "_";
        }

        var sb = new StringBuilder(value.Length + 1);
        if (!char.IsLetter(value[0]) && value[0] != '_')
        {
            sb.Append('_');
        }

        foreach (var ch in value)
        {
            sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
        }

        return sb.ToString();
    }

    private static string EscapeString(string? value)
        => value is null ? string.Empty : value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed class RegistrationCollection
    {
        public RegistrationCollection(string assemblyName, List<RegistrationInfo> registrations)
        {
            AssemblyName = assemblyName;
            Registrations = registrations;
        }

        public string AssemblyName { get; }
        public List<RegistrationInfo> Registrations { get; }
    }

    private sealed class RegistrationInfo
    {
        public RegistrationInfo(INamedTypeSymbol serviceType, INamedTypeSymbol splitedType)
        {
            ServiceType = serviceType;
            SplitedType = splitedType;
        }

        public INamedTypeSymbol ServiceType { get; }
        public INamedTypeSymbol SplitedType { get; }
    }
}
