using NOF.Hosting;

namespace NOF.Infrastructure;

public interface IBaseSettingsServiceRegistrationStep : IServiceRegistrationStep;

public interface IDependentServiceRegistrationStep : IServiceRegistrationStep, IAfter<IBaseSettingsServiceRegistrationStep>;

public interface IDataSeedInitializationStep : IApplicationInitializationStep;

public interface IObservabilityInitializationStep : IApplicationInitializationStep, IAfter<IDataSeedInitializationStep>;

public interface ISecurityInitializationStep : IApplicationInitializationStep, IAfter<IObservabilityInitializationStep>;

public interface IResponseFormattingInitializationStep : IApplicationInitializationStep, IAfter<ISecurityInitializationStep>;

public interface IAuthenticationInitializationStep : IApplicationInitializationStep, IAfter<IResponseFormattingInitializationStep>;

public interface IBusinessLogicInitializationStep : IApplicationInitializationStep, IAfter<IAuthenticationInitializationStep>;

public interface IEndpointInitializationStep : IApplicationInitializationStep, IAfter<IBusinessLogicInitializationStep>;
