using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using NOF.SourceGenerator.Shared;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Hosting.AspNetCore.SourceGenerator;

[Generator]
public class ExposeToHttpEndpointMapperGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (ctx, compilation) => Generate(ctx, compilation));
    }

    private static void Generate(SourceProductionContext context, Compilation compilation)
    {
        var rpcServiceInterfaces = new List<INamedTypeSymbol>();

        CollectRpcServiceInterfaces(compilation.Assembly.GlobalNamespace, rpcServiceInterfaces);
        foreach (var refAsm in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            CollectRpcServiceInterfaces(refAsm.GlobalNamespace, rpcServiceInterfaces);
        }

        if (rpcServiceInterfaces.Count == 0)
        {
            return;
        }

        var endpointInfos = new List<EndpointInfo>();
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var iface in rpcServiceInterfaces)
        {
            foreach (var method in GetServiceMethods(iface))
            {
                var endpoint = GetEndpointInfo(method);
                var key = $"{endpoint.ServiceType.ToDisplayString()}:{endpoint.ServiceMethodName}:{endpoint.Method}:{endpoint.Route}:{endpoint.RequestType.ToDisplayString()}:{endpoint.OperationName}";
                if (seen.Add(key))
                {
                    endpointInfos.Add(endpoint);
                }
            }
        }

        if (endpointInfos.Count == 0)
        {
            return;
        }

        GenerateMapAllHttpEndpointsExtension(context, AssemblyPrefixHelper.GetAssemblyPrefix(compilation), [.. endpointInfos]);
    }

    private static List<ServiceMethodInfo> GetServiceMethods(INamedTypeSymbol iface)
    {
        var methods = new List<ServiceMethodInfo>();

        foreach (var member in iface.GetMembers())
        {
            if (member is not IMethodSymbol { MethodKind: MethodKind.Ordinary } method || method.IsImplicitlyDeclared)
            {
                continue;
            }

            if (!ExposeToHttpEndpointHelpers.TryGetRequestParameter(method, out var requestParam))
            {
                continue;
            }

            if (requestParam.Type is not INamedTypeSymbol requestType)
            {
                continue;
            }

            if (!ExposeToHttpEndpointHelpers.TryGetServiceReturnInfo(method, out var returnInfo))
            {
                continue;
            }

            var operationName = method.Name.EndsWith("Async", StringComparison.Ordinal)
                ? method.Name.Substring(0, method.Name.Length - 5)
                : method.Name;

            methods.Add(new ServiceMethodInfo
            {
                Method = method,
                RequestType = requestType,
                ReturnInfo = returnInfo,
                OperationName = operationName
            });
        }

        return methods;
    }

    private static void CollectRpcServiceInterfaces(INamespaceSymbol ns, List<INamedTypeSymbol> results)
    {
        foreach (var member in ns.GetMembers())
        {
            switch (member)
            {
                case INamedTypeSymbol { TypeKind: TypeKind.Interface } type
                    when ExposeToHttpEndpointHelpers.IsRpcServiceInterface(type):
                    results.Add(type);
                    break;
                case INamespaceSymbol nestedNs:
                    CollectRpcServiceInterfaces(nestedNs, results);
                    break;
            }
        }
    }

    private static EndpointInfo GetEndpointInfo(ServiceMethodInfo method)
    {
        return ExposeToHttpEndpointHelpers.ExtractEndpointInfo(method);
    }

    private static void GenerateMapAllHttpEndpointsExtension(SourceProductionContext context, string assemblyName, ImmutableArray<EndpointInfo> endpoints)
    {
        if (endpoints.IsEmpty)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine($"namespace {assemblyName}");
        sb.AppendLine("{");

        foreach (var ep in endpoints)
        {
            EmitBodyDtoIfNeeded(sb, ep);
        }

        var sanitizedAssemblyName = assemblyName.Replace(".", "");
        sb.AppendLine($"    public static partial class {sanitizedAssemblyName}Extensions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static global::Microsoft.AspNetCore.Builder.WebApplication MapAllHttpEndpoints(this global::Microsoft.AspNetCore.Builder.WebApplication app)");
        sb.AppendLine("        {");

        foreach (var ep in endpoints)
        {
            EmitEndpointMapping(sb, ep);
        }

        sb.AppendLine("            return app;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("WebApplicationExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitEndpointMapping(StringBuilder sb, EndpointInfo ep)
    {
        var mapMethod = ep.Method switch
        {
            HttpVerb.Get => "MapGet",
            HttpVerb.Post => "MapPost",
            HttpVerb.Put => "MapPut",
            HttpVerb.Delete => "MapDelete",
            HttpVerb.Patch => "MapPatch",
            _ => throw new InvalidOperationException($"Unsupported verb: {ep.Method}")
        };

        var requestType = ep.RequestType.ToDisplayString();
        var serviceType = ep.ServiceType.ToDisplayString();
        var serviceCall = ep.ServiceHasCancellationToken
            ? $"service.{ep.ServiceMethodName}(request, cancellationToken)"
            : $"service.{ep.ServiceMethodName}(request)";
        var serviceInvocation = ep.ReturnInfo.Kind switch
        {
            ServiceReturnKind.Task => $"await {serviceCall}",
            ServiceReturnKind.TaskOfT => $"await {serviceCall}",
            _ => throw new InvalidOperationException("Unsupported service return kind.")
        };

        var isGet = ep.Method == HttpVerb.Get;
        var routeParams = ExposeToHttpEndpointHelpers.ExtractRouteParameters(ep.Route);
        var hasRouteParams = routeParams.Count > 0;

        if (isGet || !hasRouteParams)
        {
            var fromAttr = isGet ? "[global::Microsoft.AspNetCore.Http.AsParametersAttribute]" : "[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute]";
            sb.Append($"            app.{mapMethod}(\"{ep.Route}\",");
            sb.AppendLine();
            sb.AppendLine($"                async ({fromAttr} {requestType} request, [global::Microsoft.AspNetCore.Mvc.FromServicesAttribute] {serviceType} service{(ep.ServiceHasCancellationToken ? ", global::System.Threading.CancellationToken cancellationToken" : string.Empty)}) =>");
            sb.AppendLine("                {");
            EmitEndpointResponse(sb, ep.ReturnInfo.Kind, serviceInvocation);
            sb.Append("                })");
        }
        else
        {
            var allProperties = ExposeToHttpEndpointHelpers.GetAllPublicProperties(ep.RequestType);
            var (routeParamProps, bodyProps) = SplitRouteAndBodyProps(allProperties, routeParams);
            var hasBody = bodyProps.Count > 0;
            var bodyDtoName = GetBodyDtoName(ep.RequestType);

            var lambdaParams = new List<string>();
            foreach (var (_, prop) in routeParamProps)
            {
                lambdaParams.Add($"{prop.Type.ToDisplayString()} {ToCamelCase(prop.Name)}");
            }

            if (hasBody)
            {
                lambdaParams.Add($"[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute] {bodyDtoName} __body__");
            }

            lambdaParams.Add($"[global::Microsoft.AspNetCore.Mvc.FromServicesAttribute] {serviceType} service");
            if (ep.ServiceHasCancellationToken)
            {
                lambdaParams.Add("global::System.Threading.CancellationToken cancellationToken");
            }
            var lambdaParamStr = string.Join(", ", lambdaParams);

            sb.Append($"            app.{mapMethod}(\"{ep.Route}\",");
            sb.AppendLine();
            sb.AppendLine($"                async ({lambdaParamStr}) =>");
            sb.AppendLine("                {");

            var bestCtor = FindBestConstructor(ep.RequestType, allProperties);
            var ctorParamNames = bestCtor != null
                ? new HashSet<string>(bestCtor.Parameters.Select(p => p.Name), StringComparer.OrdinalIgnoreCase)
                : new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            var ctorArgStr = "";
            if (bestCtor != null)
            {
                var ctorArgs = new List<string>();
                foreach (var ctorParam in bestCtor.Parameters)
                {
                    var routeMatch = routeParamProps.FirstOrDefault(rp =>
                        string.Equals(rp.Property.Name, ctorParam.Name, StringComparison.OrdinalIgnoreCase));
                    if (routeMatch.Property != null)
                    {
                        ctorArgs.Add(ToCamelCase(routeMatch.Property.Name));
                    }
                    else
                    {
                        var bodyMatch = bodyProps.FirstOrDefault(bp =>
                            string.Equals(bp.Name, ctorParam.Name, StringComparison.OrdinalIgnoreCase));
                        ctorArgs.Add(bodyMatch != null ? $"__body__.{bodyMatch.Name}" : "default");
                    }
                }

                ctorArgStr = string.Join(", ", ctorArgs);
            }

            var initLines = new List<string>();
            foreach (var (_, prop) in routeParamProps)
            {
                if (!ctorParamNames.Contains(prop.Name))
                {
                    initLines.Add($"                        {prop.Name} = {ToCamelCase(prop.Name)}");
                }
            }

            foreach (var prop in bodyProps)
            {
                if (!ctorParamNames.Contains(prop.Name))
                {
                    initLines.Add($"                        {prop.Name} = __body__.{prop.Name}");
                }
            }

            if (initLines.Count > 0)
            {
                sb.AppendLine($"                    var request = new {requestType}({ctorArgStr})");
                sb.AppendLine("                    {");
                for (var i = 0; i < initLines.Count; i++)
                {
                    sb.Append(initLines[i]);
                    sb.AppendLine(i < initLines.Count - 1 ? "," : "");
                }

                sb.AppendLine("                    };");
            }
            else
            {
                sb.AppendLine($"                    var request = new {requestType}({ctorArgStr});");
            }

            var serviceCallForConstructed = ep.ServiceHasCancellationToken
                ? $"service.{ep.ServiceMethodName}(request, cancellationToken)"
                : $"service.{ep.ServiceMethodName}(request)";
            var serviceInvocationForConstructed = ep.ReturnInfo.Kind switch
            {
                ServiceReturnKind.Task => $"await {serviceCallForConstructed}",
                ServiceReturnKind.TaskOfT => $"await {serviceCallForConstructed}",
                _ => throw new InvalidOperationException("Unsupported service return kind.")
            };

            EmitEndpointResponse(sb, ep.ReturnInfo.Kind, serviceInvocationForConstructed);
            sb.Append("                })");
        }

        if (!string.IsNullOrEmpty(ep.DisplayName))
        {
            sb.Append($".WithName(\"{EscapeString(ep.DisplayName)}\")");
        }

        if (!string.IsNullOrEmpty(ep.Summary))
        {
            sb.Append($".WithSummary(\"{EscapeString(ep.Summary)}\")");
        }

        if (!string.IsNullOrEmpty(ep.Description))
        {
            sb.Append($".WithDescription(\"{EscapeString(ep.Description)}\")");
        }

        if (ep.Tags.Length > 0)
        {
            var tagArgs = string.Join(", ", ep.Tags.Select(t => $"\"{EscapeString(t)}\""));
            sb.Append($".WithTags({tagArgs})");
        }

        sb.AppendLine(";");
        sb.AppendLine();
    }

    private static void EmitBodyDtoIfNeeded(StringBuilder sb, EndpointInfo ep)
    {
        if (ep.Method == HttpVerb.Get)
        {
            return;
        }

        var routeParams = ExposeToHttpEndpointHelpers.ExtractRouteParameters(ep.Route);
        if (routeParams.Count == 0)
        {
            return;
        }

        var allProperties = ExposeToHttpEndpointHelpers.GetAllPublicProperties(ep.RequestType);
        var (_, bodyProps) = SplitRouteAndBodyProps(allProperties, routeParams);
        if (bodyProps.Count == 0)
        {
            return;
        }

        var dtoName = GetBodyDtoName(ep.RequestType);
        sb.AppendLine($"    public class {dtoName}");
        sb.AppendLine("    {");
        foreach (var prop in bodyProps)
        {
            var propType = prop.Type.ToDisplayString();
            var defaultValue = prop.Type.IsValueType ? "" : " = default!;";
            if (prop.Type.NullableAnnotation == NullableAnnotation.Annotated)
            {
                defaultValue = "";
            }

            sb.AppendLine($"        public {propType} {prop.Name} {{ get; set; }}{defaultValue}");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitEndpointResponse(StringBuilder sb, ServiceReturnKind returnKind, string invocation)
    {
        if (returnKind == ServiceReturnKind.Task)
        {
            sb.AppendLine($"                    {invocation};");
            sb.AppendLine("                    return global::Microsoft.AspNetCore.Http.TypedResults.Ok();");
            return;
        }

        sb.AppendLine($"                    var response = {invocation};");
        sb.AppendLine("                    return global::Microsoft.AspNetCore.Http.TypedResults.Ok(response);");
    }

    private static IMethodSymbol? FindBestConstructor(INamedTypeSymbol typeSymbol, List<IPropertySymbol> allProperties)
    {
        var propNames = new HashSet<string>(allProperties.Select(p => p.Name), StringComparer.OrdinalIgnoreCase);

        return typeSymbol.Constructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public
                        && !c.IsStatic
                        && c.Parameters.Length > 0
                        && c.Parameters.All(p => propNames.Contains(p.Name)))
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault();
    }

    private static (List<(string RouteParamName, IPropertySymbol Property)> RouteProps, List<IPropertySymbol> BodyProps)
        SplitRouteAndBodyProps(List<IPropertySymbol> allProperties, List<string> routeParams)
    {
        var routeParamProps = new List<(string RouteParamName, IPropertySymbol Property)>();
        var bodyProps = new List<IPropertySymbol>();

        foreach (var prop in allProperties)
        {
            var matchedParam = routeParams.FirstOrDefault(rp =>
                string.Equals(rp, prop.Name, StringComparison.OrdinalIgnoreCase));
            if (matchedParam != null)
            {
                routeParamProps.Add((matchedParam, prop));
            }
            else
            {
                bodyProps.Add(prop);
            }
        }

        return (routeParamProps, bodyProps);
    }

    private static string GetBodyDtoName(INamedTypeSymbol requestType)
        => $"__{requestType.Name}_Body__";

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static string EscapeString(string? value)
    {
        if (value is null)
        {
            return string.Empty;
        }

        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
