using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Hosting.AspNetCore.SourceGenerator;

[Generator]
public sealed class RpcHttpEndpointRegistryGenerator : IIncrementalGenerator
{
    private const string RpcServerGenericFqn = "NOF.Application.RpcServer<TRpcService>";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var serverTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is InvocationExpressionSyntax,
                transform: static (ctx, _) => GetRpcServerTypeFromMapHttpEndpointCall(ctx))
            .Where(static t => t is not null)
            .Collect();

        var data = context.CompilationProvider.Combine(serverTypes);
        context.RegisterSourceOutput(data, static (spc, pair) =>
        {
            var (compilation, servers) = pair;
            Generate(spc, compilation, servers);
        });
    }

    private static INamedTypeSymbol? GetRpcServerTypeFromMapHttpEndpointCall(GeneratorSyntaxContext context)
    {
        if (context.Node is not InvocationExpressionSyntax invocation)
        {
            return null;
        }

        // Matches: app.MapHttpEndpoint<TRpcServer>(...)
        var genericName = invocation.Expression switch
        {
            MemberAccessExpressionSyntax { Name: GenericNameSyntax g } => g,
            GenericNameSyntax g => g,
            _ => null
        };
        if (genericName is null
            || genericName.Identifier.ValueText != "MapHttpEndpoint"
            || genericName.TypeArgumentList.Arguments.Count != 1)
        {
            return null;
        }

        var symbolInfo = context.SemanticModel.GetSymbolInfo(invocation);
        var methodSymbol = symbolInfo.Symbol as IMethodSymbol
            ?? symbolInfo.CandidateSymbols.OfType<IMethodSymbol>().FirstOrDefault();
        if (methodSymbol is null || methodSymbol.Name != "MapHttpEndpoint" || !methodSymbol.IsGenericMethod)
        {
            return null;
        }

        if (methodSymbol.TypeArguments.Length != 1)
        {
            return null;
        }

        var serverType = methodSymbol.TypeArguments[0] as INamedTypeSymbol;
        if (serverType is null)
        {
            return null;
        }

        // Best-effort check: must derive from RpcServer<TRpcService>.
        return TryGetRpcServiceType(serverType, out _) ? serverType : null;
    }

    private static bool TryGetRpcServiceType(INamedTypeSymbol rpcServerType, out INamedTypeSymbol? serviceType)
    {
        serviceType = null;
        for (var current = rpcServerType; current is not null; current = current.BaseType)
        {
            if (current is { IsGenericType: true }
                && current.OriginalDefinition.ToDisplayString() == RpcServerGenericFqn
                && current.TypeArguments.Length == 1
                && current.TypeArguments[0] is INamedTypeSymbol st)
            {
                serviceType = st;
                return true;
            }
        }

        return false;
    }

    private static void Generate(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol?> servers)
    {
        if (servers.IsDefaultOrEmpty)
        {
            return;
        }

        var serverTypes = servers
            .Distinct(SymbolEqualityComparer.Default)
            .OfType<INamedTypeSymbol>()
            .ToArray();
        if (serverTypes.Length == 0)
        {
            return;
        }

        var assemblyName = compilation.AssemblyName ?? "GeneratedAssembly";
        var sanitizedAssemblyName = SanitizeIdentifier(assemblyName.Replace(".", ""));
        var initializerTypeName = $"__{sanitizedAssemblyName}RpcHttpEndpointAssemblyInitializer";
        var handlersTypeName = $"__{sanitizedAssemblyName}RpcHttpEndpointHandlers";

        var typeFormat = SymbolDisplayFormat.FullyQualifiedFormat;
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using NOF.Abstraction;");
        sb.AppendLine();
        sb.AppendLine($"[assembly: global::NOF.Annotation.AssemblyInitializeAttribute<global::{assemblyName}.{initializerTypeName}>]");
        sb.AppendLine();
        sb.AppendLine($"namespace {assemblyName}");
        sb.AppendLine("{");

        sb.AppendLine($"    internal static class {handlersTypeName}");
        sb.AppendLine("    {");

        var registrationLines = new List<string>();

        foreach (var serverType in serverTypes)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            if (!TryGetRpcServiceType(serverType, out var serviceType) || serviceType is null)
            {
                continue;
            }

            var serviceTypeName = serviceType.ToDisplayString(typeFormat);
            foreach (var method in serviceType.GetMembers().OfType<IMethodSymbol>())
            {
                if (method.MethodKind != MethodKind.Ordinary || method.IsImplicitlyDeclared)
                {
                    continue;
                }

                if (!TryGetRequestParameter(method, out var requestParam) || requestParam is null)
                {
                    continue;
                }

                var requestTypeName = requestParam.Type.ToDisplayString(typeFormat);
                var returnTypeName = method.ReturnType.ToDisplayString(typeFormat);
                var operationName = method.Name;

                var handlerMethodName = $"Handle_{SanitizeIdentifier(serviceType.Name)}_{SanitizeIdentifier(operationName)}";
                sb.AppendLine($"        public static async global::System.Threading.Tasks.Task<{returnTypeName}> {handlerMethodName}(");
                sb.AppendLine($"            [FromBody] {requestTypeName} request,");
                sb.AppendLine($"            [FromServices] global::System.IServiceProvider services,");
                sb.AppendLine($"            global::System.Threading.CancellationToken cancellationToken)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var result = await global::NOF.Infrastructure.RpcServerInvoker.InvokeAsync<{serviceTypeName}>(services, \"{EscapeString(operationName)}\", request, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine($"            return ({returnTypeName})result!;");
                sb.AppendLine("        }");
                sb.AppendLine();

                var register =
                    "            global::NOF.Abstraction.Registry.RpcHttpEndpointHandlerRegistrations.Add(" +
                    $"new global::NOF.Hosting.AspNetCore.RpcHttpEndpointHandlerRegistration(" +
                    $"typeof({serviceTypeName}), " +
                    $"\"{EscapeString(operationName)}\", " +
                    $"(global::System.Delegate)(global::System.Func<{requestTypeName}, global::System.IServiceProvider, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<{returnTypeName}>>){handlersTypeName}.{handlerMethodName}, " +
                    $"typeof({returnTypeName}))" +
                    ");";
                registrationLines.Add(register);
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    internal sealed class {initializerTypeName} : global::NOF.Annotation.IAssemblyInitializer");
        sb.AppendLine("    {");
        sb.AppendLine("        private static int _initialized;");
        sb.AppendLine();
        sb.AppendLine("        public static void Initialize()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (global::System.Threading.Interlocked.Exchange(ref _initialized, 1) == 1)");
        sb.AppendLine("            {");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine();
        foreach (var line in registrationLines.Distinct(StringComparer.Ordinal))
        {
            sb.AppendLine(line);
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        context.AddSource("RpcHttpEndpointAssemblyInitializer.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool TryGetRequestParameter(IMethodSymbol method, out IParameterSymbol? requestParam)
    {
        requestParam = null;
        foreach (var p in method.Parameters)
        {
            if (p.Type.ToDisplayString() == "System.Threading.CancellationToken")
            {
                continue;
            }

            requestParam = p;
            return true;
        }

        return false;
    }

    private static string EscapeString(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string SanitizeIdentifier(string raw)
    {
        if (string.IsNullOrEmpty(raw))
        {
            return "_";
        }

        var sb = new StringBuilder(raw.Length);
        for (var i = 0; i < raw.Length; i++)
        {
            var ch = raw[i];
            sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
        }

        if (char.IsDigit(sb[0]))
        {
            sb.Insert(0, '_');
        }

        return sb.ToString();
    }
}
