using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NOF.Hosting.AspNetCore.SourceGenerator;

[Generator]
public class RpcServiceEndpointMapperGenerator : IIncrementalGenerator
{
    private const string MapServiceToHttpEndpointsAttributeFqn = "NOF.Hosting.AspNetCore.MapServiceToHttpEndpointsAttribute<TService>";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var registrations = context.CompilationProvider
            .Select(static (compilation, _) => CollectRegistrations(compilation));

        context.RegisterSourceOutput(registrations, static (ctx, data) => GenerateAssemblyInitializer(ctx, data));
    }

    private static RegistrationCollection CollectRegistrations(Compilation compilation)
    {
        var results = new List<ServiceRegistrationInfo>();
        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach (var attr in compilation.Assembly.GetAttributes())
        {
            if (attr.AttributeClass is not INamedTypeSymbol { IsGenericType: true } attributeClass
                || attributeClass.OriginalDefinition.ToDisplayString() != MapServiceToHttpEndpointsAttributeFqn)
            {
                continue;
            }

            if (attributeClass.TypeArguments.Length != 1
                || attributeClass.TypeArguments[0] is not INamedTypeSymbol serviceType
                || !RpcServiceHelpers.IsRpcServiceInterface(serviceType))
            {
                continue;
            }

            var prefix = attr.NamedArguments.FirstOrDefault(x => x.Key == "Prefix").Value.Value as string ?? string.Empty;
            var key = serviceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + "|" + prefix;
            if (!seen.Add(key))
            {
                continue;
            }

            results.Add(new ServiceRegistrationInfo(serviceType, prefix));
        }

        return new RegistrationCollection(compilation.AssemblyName ?? "GeneratedAssembly", results);
    }

    private static void GenerateAssemblyInitializer(SourceProductionContext context, RegistrationCollection data)
    {
        if (data.Registrations.Count == 0)
        {
            return;
        }

        var assemblyName = data.AssemblyName;
        var sanitizedAssemblyName = SanitizeIdentifier(assemblyName.Replace(".", ""));
        var initializerTypeName = $"__{sanitizedAssemblyName}RpcServiceEndpointAssemblyInitializer";
        var mappingsTypeName = $"__{sanitizedAssemblyName}RpcServiceEndpointMappings";
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine();
        sb.AppendLine($"[assembly: global::NOF.Annotation.AssemblyInitializeAttribute<global::{assemblyName}.{initializerTypeName}>]");
        sb.AppendLine();
        sb.AppendLine($"namespace {assemblyName}");
        sb.AppendLine("{");
        sb.AppendLine($"    internal static class {mappingsTypeName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private static string BuildRoute(string prefix, string route)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (string.IsNullOrEmpty(prefix))");
        sb.AppendLine("            {");
        sb.AppendLine("                return route;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (string.IsNullOrEmpty(route))");
        sb.AppendLine("            {");
        sb.AppendLine("                return prefix;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var normalizedPrefix = prefix.EndsWith(\"/\", global::System.StringComparison.Ordinal)");
        sb.AppendLine("                ? prefix.TrimEnd('/')");
        sb.AppendLine("                : prefix;");
        sb.AppendLine("            var normalizedRoute = route.StartsWith(\"/\", global::System.StringComparison.Ordinal)");
        sb.AppendLine("                ? route");
        sb.AppendLine("                : \"/\" + route;");
        sb.AppendLine("            return normalizedPrefix + normalizedRoute;");
        sb.AppendLine("        }");
        sb.AppendLine();

        for (var i = 0; i < data.Registrations.Count; i++)
        {
            var registration = data.Registrations[i];
            var endpoints = GetDistinctEndpointInfos(registration.ServiceType);
            foreach (var endpoint in endpoints)
            {
                EmitBodyDtoIfNeeded(sb, endpoint, GetBodyDtoName(registration.ServiceType, endpoint.RequestType));
            }

            EmitMapServiceRegistration(sb, registration, i);
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    internal sealed class {initializerTypeName} : global::NOF.Annotation.IAssemblyInitializer");
        sb.AppendLine("    {");
        sb.AppendLine("        private static int _initialized;");
        sb.AppendLine();
        sb.AppendLine("        public static void Initialize()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (global::System.Threading.Interlocked.Exchange(ref _initialized, 1) == 1)");
        sb.AppendLine("            {");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine();
        for (var i = 0; i < data.Registrations.Count; i++)
        {
            sb.AppendLine($"            global::NOF.Hosting.AspNetCore.RpcServiceEndpointRegistry.Register({mappingsTypeName}.Map_{i});");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("RpcServiceEndpointAssemblyInitializer.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitMapServiceRegistration(StringBuilder sb, ServiceRegistrationInfo registration, int index)
    {
        var endpoints = GetDistinctEndpointInfos(registration.ServiceType);
        if (endpoints.Count == 0)
        {
            return;
        }

        sb.AppendLine($"        internal static void Map_{index}(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)");
        sb.AppendLine("        {");

        foreach (var endpoint in endpoints)
        {
            var routeExpression = $"BuildRoute(\"{EscapeString(registration.Prefix)}\", \"{EscapeString(endpoint.Route)}\")";
            var bodyDtoName = GetBodyDtoName(registration.ServiceType, endpoint.RequestType);
            EmitEndpointMapping(sb, endpoint, routeExpression, bodyDtoName);
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static List<ServiceMethodInfo> GetServiceMethods(INamedTypeSymbol iface)
    {
        var methods = new List<ServiceMethodInfo>();

        foreach (var member in iface.GetMembers())
        {
            if (member is not IMethodSymbol { MethodKind: MethodKind.Ordinary } method || method.IsImplicitlyDeclared)
            {
                continue;
            }

            if (!RpcServiceHelpers.TryGetRequestParameter(method, out var requestParam))
            {
                continue;
            }

            INamedTypeSymbol? requestType = null;
            if (requestParam != null && requestParam.Type is INamedTypeSymbol namedType)
            {
                requestType = namedType;
            }

            if (!RpcServiceHelpers.TryGetServiceReturnInfo(method, out var returnInfo))
            {
                continue;
            }

            var operationName = method.Name.EndsWith("Async", StringComparison.Ordinal)
                ? method.Name.Substring(0, method.Name.Length - 5)
                : method.Name;

            methods.Add(new ServiceMethodInfo
            {
                Method = method,
                RequestType = requestType,
                ReturnInfo = returnInfo,
                OperationName = operationName
            });
        }

        return methods;
    }

    private static List<EndpointInfo> GetDistinctEndpointInfos(INamedTypeSymbol iface)
    {
        var endpoints = new List<EndpointInfo>();
        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach (var method in GetServiceMethods(iface))
        {
            var endpoint = GetEndpointInfo(method);
            if (seen.Add(BuildEndpointKey(endpoint)))
            {
                endpoints.Add(endpoint);
            }
        }

        return endpoints;
    }

    private static EndpointInfo GetEndpointInfo(ServiceMethodInfo method)
    {
        return RpcServiceHelpers.ExtractEndpointInfo(method);
    }

    private static string BuildEndpointKey(EndpointInfo endpoint)
        => $"{endpoint.ServiceType.ToDisplayString()}:{endpoint.ServiceMethodName}:{endpoint.Method}:{endpoint.Route}:{(endpoint.RequestType != null ? endpoint.RequestType.ToDisplayString() : "null")}:{endpoint.OperationName}";

    private static void EmitEndpointMapping(StringBuilder sb, EndpointInfo ep, string routeExpression, string bodyDtoName)
    {
        var mapMethod = ep.Method switch
        {
            HttpVerb.Get => "MapGet",
            HttpVerb.Post => "MapPost",
            HttpVerb.Put => "MapPut",
            HttpVerb.Delete => "MapDelete",
            HttpVerb.Patch => "MapPatch",
            _ => throw new InvalidOperationException($"Unsupported verb: {ep.Method}")
        };

        var serviceType = ep.ServiceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var requestType = ep.RequestType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var routeParams = RpcServiceHelpers.ExtractRouteParameters(ep.Route);
        var hasRouteParams = routeParams.Count > 0;
        var isGet = ep.Method == HttpVerb.Get;

        var lambdaParams = new List<string>();

        if (requestType != null)
        {
            if (isGet || !hasRouteParams)
            {
                var fromAttr = isGet ? "[global::Microsoft.AspNetCore.Http.AsParametersAttribute]" : "[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute]";
                lambdaParams.Add($"{fromAttr} {requestType} request");
            }
            else
            {
                var allProperties = RpcServiceHelpers.GetAllPublicProperties(ep.RequestType!);
                var (routeParamProps, bodyProps) = SplitRouteAndBodyProps(allProperties, routeParams);
                var hasBody = bodyProps.Count > 0;

                foreach (var (_, prop) in routeParamProps)
                {
                    lambdaParams.Add($"{prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {ToCamelCase(prop.Name)}");
                }

                if (hasBody)
                {
                    lambdaParams.Add($"[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute] {bodyDtoName} __body__");
                }
            }
        }
        else
        {
            foreach (var param in routeParams)
            {
                lambdaParams.Add($"string {param}");
            }
        }

        lambdaParams.Add($"[global::Microsoft.AspNetCore.Mvc.FromServicesAttribute] {serviceType} service");
        if (ep.ServiceHasCancellationToken)
        {
            lambdaParams.Add("global::System.Threading.CancellationToken cancellationToken");
        }
        var lambdaParamStr = string.Join(", ", lambdaParams);

        sb.Append($"            app.{mapMethod}({routeExpression},");
        sb.AppendLine();
        sb.AppendLine($"                async ({lambdaParamStr}) =>");
        sb.AppendLine("                {");

        if (requestType != null && hasRouteParams && !isGet)
        {
            var allProperties = RpcServiceHelpers.GetAllPublicProperties(ep.RequestType!);
            var (routeParamProps, bodyProps) = SplitRouteAndBodyProps(allProperties, routeParams);
            var bestCtor = FindBestConstructor(ep.RequestType!, allProperties);
            var ctorParamNames = bestCtor != null
                ? new HashSet<string>(bestCtor.Parameters.Select(p => p.Name), StringComparer.OrdinalIgnoreCase)
                : new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            var ctorArgStr = "";
            if (bestCtor != null)
            {
                var ctorArgs = new List<string>();
                foreach (var ctorParam in bestCtor.Parameters)
                {
                    var routeMatch = routeParamProps.FirstOrDefault(rp =>
                        string.Equals(rp.Property.Name, ctorParam.Name, StringComparison.OrdinalIgnoreCase));
                    if (routeMatch.Property != null)
                    {
                        ctorArgs.Add(ToCamelCase(routeMatch.Property.Name));
                    }
                    else
                    {
                        var bodyMatch = bodyProps.FirstOrDefault(bp =>
                            string.Equals(bp.Name, ctorParam.Name, StringComparison.OrdinalIgnoreCase));
                        ctorArgs.Add(bodyMatch != null ? $"__body__.{bodyMatch.Name}" : "default");
                    }
                }

                ctorArgStr = string.Join(", ", ctorArgs);
            }

            var initLines = new List<string>();
            foreach (var (_, prop) in routeParamProps)
            {
                if (!ctorParamNames.Contains(prop.Name))
                {
                    initLines.Add($"                        {prop.Name} = {ToCamelCase(prop.Name)}");
                }
            }

            foreach (var prop in bodyProps)
            {
                if (!ctorParamNames.Contains(prop.Name))
                {
                    initLines.Add($"                        {prop.Name} = __body__.{prop.Name}");
                }
            }

            if (initLines.Count > 0)
            {
                sb.AppendLine($"                    var request = new {requestType}({ctorArgStr})");
                sb.AppendLine("                    {");
                for (var i = 0; i < initLines.Count; i++)
                {
                    sb.Append(initLines[i]);
                    sb.AppendLine(i < initLines.Count - 1 ? "," : "");
                }

                sb.AppendLine("                    };");
            }
            else
            {
                sb.AppendLine($"                    var request = new {requestType}({ctorArgStr});");
            }
        }



        var serviceCall = "";
        if (requestType != null)
        {
            serviceCall = ep.ServiceHasCancellationToken
                ? $"service.{ep.ServiceMethodName}(request, cancellationToken)"
                : $"service.{ep.ServiceMethodName}(request)";
        }
        else
        {
            serviceCall = ep.ServiceHasCancellationToken
                ? $"service.{ep.ServiceMethodName}(cancellationToken)"
                : $"service.{ep.ServiceMethodName}()";
        }

        var serviceInvocation = ep.ReturnInfo.Kind switch
        {
            ServiceReturnKind.TaskOfResult => $"await {serviceCall}",
            ServiceReturnKind.TaskOfResultOfT => $"await {serviceCall}",
            _ => throw new InvalidOperationException("Unsupported service return kind.")
        };

        sb.AppendLine($"                    var result = {serviceInvocation};");

        EmitEndpointResponse(sb, ep.ReturnInfo.Kind, "result!", "                    ");

        sb.Append("                })");

        if (!string.IsNullOrEmpty(ep.DisplayName))
        {
            sb.Append($".WithName(\"{EscapeString(ep.DisplayName)}\")");
        }

        if (!string.IsNullOrEmpty(ep.Summary))
        {
            sb.Append($".WithSummary(\"{EscapeString(ep.Summary)}\")");
        }

        if (!string.IsNullOrEmpty(ep.Description))
        {
            sb.Append($".WithDescription(\"{EscapeString(ep.Description)}\")");
        }

        if (ep.Tags.Length > 0)
        {
            var tagArgs = string.Join(", ", ep.Tags.Select(t => $"\"{EscapeString(t)}\""));
            sb.Append($".WithTags({tagArgs})");
        }

        sb.AppendLine(";");
        sb.AppendLine();
    }

    private static void EmitBodyDtoIfNeeded(StringBuilder sb, EndpointInfo ep, string dtoName)
    {
        if (ep.Method == HttpVerb.Get)
        {
            return;
        }

        if (ep.RequestType == null)
        {
            return;
        }

        var routeParams = RpcServiceHelpers.ExtractRouteParameters(ep.Route);
        if (routeParams.Count == 0)
        {
            return;
        }

        var allProperties = RpcServiceHelpers.GetAllPublicProperties(ep.RequestType);
        var (_, bodyProps) = SplitRouteAndBodyProps(allProperties, routeParams);
        if (bodyProps.Count == 0)
        {
            return;
        }

        sb.AppendLine($"    public class {dtoName}");
        sb.AppendLine("    {");
        foreach (var prop in bodyProps)
        {
            var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var defaultValue = prop.Type.IsValueType ? "" : " = default!;";
            if (prop.Type.NullableAnnotation == NullableAnnotation.Annotated)
            {
                defaultValue = "";
            }

            sb.AppendLine($"        public {propType} {prop.Name} {{ get; set; }}{defaultValue}");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitEndpointResponse(StringBuilder sb, ServiceReturnKind returnKind, string invocation, string indent = "                    ")
    {
        sb.AppendLine($"{indent}return global::Microsoft.AspNetCore.Http.TypedResults.Ok({invocation});");
    }

    private static IMethodSymbol? FindBestConstructor(INamedTypeSymbol typeSymbol, List<IPropertySymbol> allProperties)
    {
        var propNames = new HashSet<string>(allProperties.Select(p => p.Name), StringComparer.OrdinalIgnoreCase);

        return typeSymbol.Constructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public
                        && !c.IsStatic
                        && c.Parameters.Length > 0
                        && c.Parameters.All(p => propNames.Contains(p.Name)))
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault();
    }

    private static (List<(string RouteParamName, IPropertySymbol Property)> RouteProps, List<IPropertySymbol> BodyProps)
        SplitRouteAndBodyProps(List<IPropertySymbol> allProperties, List<string> routeParams)
    {
        var routeParamProps = new List<(string RouteParamName, IPropertySymbol Property)>();
        var bodyProps = new List<IPropertySymbol>();

        foreach (var prop in allProperties)
        {
            var matchedParam = routeParams.FirstOrDefault(rp =>
                string.Equals(rp, prop.Name, StringComparison.OrdinalIgnoreCase));
            if (matchedParam != null)
            {
                routeParamProps.Add((matchedParam, prop));
            }
            else
            {
                bodyProps.Add(prop);
            }
        }

        return (routeParamProps, bodyProps);
    }

    private static string GetBodyDtoName(INamedTypeSymbol serviceType, INamedTypeSymbol? requestType)
        => requestType != null
            ? $"__{SanitizeIdentifier(serviceType.ToDisplayString())}_{requestType.Name}_Body__"
            : $"__{SanitizeIdentifier(serviceType.ToDisplayString())}_NoRequest_Body__";

    private static string SanitizeIdentifier(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return "_";
        }

        var sb = new StringBuilder(value.Length + 1);
        if (!char.IsLetter(value[0]) && value[0] != '_')
        {
            sb.Append('_');
        }

        foreach (var ch in value)
        {
            sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
        }

        return sb.ToString();
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static string EscapeString(string? value)
    {
        if (value is null)
        {
            return string.Empty;
        }

        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private sealed class RegistrationCollection
    {
        public RegistrationCollection(string assemblyName, List<ServiceRegistrationInfo> registrations)
        {
            AssemblyName = assemblyName;
            Registrations = registrations;
        }

        public string AssemblyName { get; }
        public List<ServiceRegistrationInfo> Registrations { get; }
    }

    private sealed class ServiceRegistrationInfo
    {
        public ServiceRegistrationInfo(INamedTypeSymbol serviceType, string prefix)
        {
            ServiceType = serviceType;
            Prefix = prefix;
        }

        public INamedTypeSymbol ServiceType { get; }
        public string Prefix { get; }
    }
}
