using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace NOF.Hosting.AspNetCore.SourceGenerator;

[Generator]
public class RpcServiceEndpointMapperGenerator : IIncrementalGenerator
{
    private const string MapServiceToHttpEndpointsMethodName = "MapServiceToHttpEndpoints";
    private const string GeneratedInterceptorNamespace = "NOF.Hosting.AspNetCore.Generated";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var mapServiceInvocations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => IsPotentialMapServiceInvocation(node),
                static (ctx, ct) => GetMapServiceInvocation(ctx, ct))
            .Where(static invocation => invocation is not null)
            .Select(static (invocation, _) => invocation!);

        context.RegisterSourceOutput(mapServiceInvocations.Collect(), static (ctx, invocations) => GenerateMapServiceInterceptors(ctx, invocations));
    }

    private static void GenerateMapServiceInterceptors(
        SourceProductionContext context,
        ImmutableArray<MapServiceInvocationInfo> invocations)
    {
        if (invocations.IsDefaultOrEmpty)
        {
            return;
        }

        var groupedInvocations = invocations
            .GroupBy(static invocation => invocation.ServiceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
            .Select(static group => new
            {
                ServiceType = group.First().ServiceType,
                Locations = group
                    .GroupBy(static invocation => invocation.Location.Data, StringComparer.Ordinal)
                    .Select(static locationGroup => locationGroup.First().Location)
                    .ToImmutableArray()
            })
            .ToList();

        if (groupedInvocations.Count == 0)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Diagnostics.Conditional(\"DEBUG\")]");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute : global::System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data)");
        sb.AppendLine("        {");
        sb.AppendLine("            _ = version;");
        sb.AppendLine("            _ = data;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"namespace {GeneratedInterceptorNamespace}");
        sb.AppendLine("{");

        foreach (var group in groupedInvocations)
        {
            foreach (var endpoint in GetDistinctEndpointInfos(group.ServiceType))
            {
                EmitBodyDtoIfNeeded(sb, endpoint, GetInterceptorBodyDtoName(group.ServiceType, endpoint.RequestType));
            }
        }

        sb.AppendLine("    internal static class HttpEndpointInterceptors");
        sb.AppendLine("    {");
        sb.AppendLine("        private static string BuildRoute(string prefix, string route)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (string.IsNullOrEmpty(prefix))");
        sb.AppendLine("            {");
        sb.AppendLine("                return route;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (string.IsNullOrEmpty(route))");
        sb.AppendLine("            {");
        sb.AppendLine("                return prefix;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var normalizedPrefix = prefix.EndsWith(\"/\", global::System.StringComparison.Ordinal)");
        sb.AppendLine("                ? prefix.TrimEnd('/')");
        sb.AppendLine("                : prefix;");
        sb.AppendLine("            var normalizedRoute = route.StartsWith(\"/\", global::System.StringComparison.Ordinal)");
        sb.AppendLine("                ? route");
        sb.AppendLine("                : \"/\" + route;");
        sb.AppendLine("            return normalizedPrefix + normalizedRoute;");
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach (var group in groupedInvocations)
        {
            EmitMapServiceInterceptor(sb, group.ServiceType, group.Locations);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("MapServiceToHttpEndpointsInterceptors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool IsPotentialMapServiceInvocation(SyntaxNode node)
        => node is InvocationExpressionSyntax
        {
            Expression: MemberAccessExpressionSyntax
            {
                Name.Identifier.ValueText: MapServiceToHttpEndpointsMethodName
            }
        };

    private static MapServiceInvocationInfo? GetMapServiceInvocation(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.Node is not InvocationExpressionSyntax
            {
                Expression: MemberAccessExpressionSyntax
                {
                    Name: GenericNameSyntax genericName
                }
            } invocation)
        {
            return null;
        }

        if (context.SemanticModel.GetOperation(invocation, cancellationToken) is not IInvocationOperation operation)
        {
            return null;
        }

        var targetMethod = operation.TargetMethod.ReducedFrom ?? operation.TargetMethod;
        if (!IsMapServiceToHttpEndpointsMethod(targetMethod))
        {
            return null;
        }

        if (genericName.TypeArgumentList.Arguments.Count != 1
            || context.SemanticModel.GetTypeInfo(genericName.TypeArgumentList.Arguments[0], cancellationToken).Type is not INamedTypeSymbol serviceType)
        {
            return null;
        }

        if (!RpcServiceHelpers.IsRpcServiceInterface(serviceType))
        {
            return null;
        }

#pragma warning disable RSEXPERIMENTAL002
        var interceptableLocation = context.SemanticModel.GetInterceptableLocation(invocation);
#pragma warning restore RSEXPERIMENTAL002
        if (interceptableLocation is null)
        {
            return null;
        }

        return new MapServiceInvocationInfo(interceptableLocation, serviceType);
    }

    private static bool IsMapServiceToHttpEndpointsMethod(IMethodSymbol method)
    {
        var reducedMethod = method.ReducedFrom ?? method;
        var parameter = reducedMethod.Parameters.LastOrDefault();

        return reducedMethod.Name == MapServiceToHttpEndpointsMethodName
               && reducedMethod.TypeParameters.Length == 1
               && method.ReturnType.ToDisplayString() == "Microsoft.AspNetCore.Builder.WebApplication"
               && parameter?.Type.SpecialType == SpecialType.System_String;
    }

    private static void EmitMapServiceInterceptor(
        StringBuilder sb,
        INamedTypeSymbol serviceType,
        ImmutableArray<InterceptableLocation> locations)
    {
        var endpoints = GetDistinctEndpointInfos(serviceType);
        if (endpoints.Count == 0)
        {
            return;
        }

        foreach (var location in locations)
        {
            sb.AppendLine($"        [global::System.Runtime.CompilerServices.InterceptsLocation({location.Version}, \"{EscapeString(location.Data)}\")]");
        }

        var interceptorMethodName = $"MapServiceToHttpEndpoints_{SanitizeIdentifier(serviceType.ToDisplayString())}";
        sb.AppendLine($"        public static global::Microsoft.AspNetCore.Builder.WebApplication {interceptorMethodName}(this global::Microsoft.AspNetCore.Builder.WebApplication app, string prefix = \"\")");
        sb.AppendLine("        {");

        foreach (var endpoint in endpoints)
        {
            var routeExpression = $"BuildRoute(prefix, \"{EscapeString(endpoint.Route)}\")";
            var bodyDtoName = GetInterceptorBodyDtoName(serviceType, endpoint.RequestType);
            EmitEndpointMapping(sb, endpoint, routeExpression, bodyDtoName);
        }

        sb.AppendLine("            return app;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static List<ServiceMethodInfo> GetServiceMethods(INamedTypeSymbol iface)
    {
        var methods = new List<ServiceMethodInfo>();

        foreach (var member in iface.GetMembers())
        {
            if (member is not IMethodSymbol { MethodKind: MethodKind.Ordinary } method || method.IsImplicitlyDeclared)
            {
                continue;
            }

            if (!RpcServiceHelpers.TryGetRequestParameter(method, out var requestParam))
            {
                continue;
            }

            INamedTypeSymbol? requestType = null;
            if (requestParam != null && requestParam.Type is INamedTypeSymbol namedType)
            {
                requestType = namedType;
            }

            if (!RpcServiceHelpers.TryGetServiceReturnInfo(method, out var returnInfo))
            {
                continue;
            }

            var operationName = method.Name.EndsWith("Async", StringComparison.Ordinal)
                ? method.Name.Substring(0, method.Name.Length - 5)
                : method.Name;

            methods.Add(new ServiceMethodInfo
            {
                Method = method,
                RequestType = requestType,
                ReturnInfo = returnInfo,
                OperationName = operationName
            });
        }

        return methods;
    }

    private static List<EndpointInfo> GetDistinctEndpointInfos(INamedTypeSymbol iface)
    {
        var endpoints = new List<EndpointInfo>();
        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach (var method in GetServiceMethods(iface))
        {
            var endpoint = GetEndpointInfo(method);
            if (seen.Add(BuildEndpointKey(endpoint)))
            {
                endpoints.Add(endpoint);
            }
        }

        return endpoints;
    }

    private static EndpointInfo GetEndpointInfo(ServiceMethodInfo method)
    {
        return RpcServiceHelpers.ExtractEndpointInfo(method);
    }

    private static string BuildEndpointKey(EndpointInfo endpoint)
        => $"{endpoint.ServiceType.ToDisplayString()}:{endpoint.ServiceMethodName}:{endpoint.Method}:{endpoint.Route}:{(endpoint.RequestType != null ? endpoint.RequestType.ToDisplayString() : "null")}:{endpoint.OperationName}";

    private static void EmitEndpointMapping(StringBuilder sb, EndpointInfo ep, string routeExpression, string bodyDtoName)
    {
        var mapMethod = ep.Method switch
        {
            HttpVerb.Get => "MapGet",
            HttpVerb.Post => "MapPost",
            HttpVerb.Put => "MapPut",
            HttpVerb.Delete => "MapDelete",
            HttpVerb.Patch => "MapPatch",
            _ => throw new InvalidOperationException($"Unsupported verb: {ep.Method}")
        };

        var serviceType = ep.ServiceType.ToDisplayString();
        var routeParams = RpcServiceHelpers.ExtractRouteParameters(ep.Route);
        var hasRouteParams = routeParams.Count > 0;

        if (ep.RequestType == null)
        {
            var lambdaParams = new List<string>();
            foreach (var param in routeParams)
            {
                lambdaParams.Add($"string {param}");
            }
            lambdaParams.Add($"[global::Microsoft.AspNetCore.Mvc.FromServicesAttribute] {serviceType} service");
            if (ep.ServiceHasCancellationToken)
            {
                lambdaParams.Add("global::System.Threading.CancellationToken cancellationToken");
            }
            var lambdaParamStr = string.Join(", ", lambdaParams);

            var serviceCall = ep.ServiceHasCancellationToken
                ? $"service.{ep.ServiceMethodName}(cancellationToken)"
                : $"service.{ep.ServiceMethodName}()";
            var serviceInvocation = ep.ReturnInfo.Kind switch
            {
                ServiceReturnKind.TaskOfResult => $"await {serviceCall}",
                ServiceReturnKind.TaskOfResultOfT => $"await {serviceCall}",
                _ => throw new InvalidOperationException("Unsupported service return kind.")
            };

            sb.Append($"            app.{mapMethod}({routeExpression},");
            sb.AppendLine();
            sb.AppendLine($"                async ({lambdaParamStr}) =>");
            sb.AppendLine("                {");
            EmitEndpointResponse(sb, ep.ReturnInfo.Kind, serviceInvocation);
            sb.Append("                })");
        }
        else
        {
            var requestType = ep.RequestType.ToDisplayString();
            var serviceCall = ep.ServiceHasCancellationToken
                ? $"service.{ep.ServiceMethodName}(request, cancellationToken)"
                : $"service.{ep.ServiceMethodName}(request)";
            var serviceInvocation = ep.ReturnInfo.Kind switch
            {
                ServiceReturnKind.TaskOfResult => $"await {serviceCall}",
                ServiceReturnKind.TaskOfResultOfT => $"await {serviceCall}",
                _ => throw new InvalidOperationException("Unsupported service return kind.")
            };

            var isGet = ep.Method == HttpVerb.Get;
            if (isGet || !hasRouteParams)
            {
                var fromAttr = isGet ? "[global::Microsoft.AspNetCore.Http.AsParametersAttribute]" : "[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute]";
                sb.Append($"            app.{mapMethod}({routeExpression},");
                sb.AppendLine();
                sb.AppendLine($"                async ({fromAttr} {requestType} request, [global::Microsoft.AspNetCore.Mvc.FromServicesAttribute] {serviceType} service{(ep.ServiceHasCancellationToken ? ", global::System.Threading.CancellationToken cancellationToken" : string.Empty)}) =>");
                sb.AppendLine("                {");
                EmitEndpointResponse(sb, ep.ReturnInfo.Kind, serviceInvocation);
                sb.Append("                })");
            }
            else
            {
                var allProperties = RpcServiceHelpers.GetAllPublicProperties(ep.RequestType);
                var (routeParamProps, bodyProps) = SplitRouteAndBodyProps(allProperties, routeParams);
                var hasBody = bodyProps.Count > 0;

                var lambdaParams = new List<string>();
                foreach (var (_, prop) in routeParamProps)
                {
                    lambdaParams.Add($"{prop.Type.ToDisplayString()} {ToCamelCase(prop.Name)}");
                }

                if (hasBody)
                {
                    lambdaParams.Add($"[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute] {bodyDtoName} __body__");
                }

                lambdaParams.Add($"[global::Microsoft.AspNetCore.Mvc.FromServicesAttribute] {serviceType} service");
                if (ep.ServiceHasCancellationToken)
                {
                    lambdaParams.Add("global::System.Threading.CancellationToken cancellationToken");
                }
                var lambdaParamStr = string.Join(", ", lambdaParams);

                sb.Append($"            app.{mapMethod}({routeExpression},");
                sb.AppendLine();
                sb.AppendLine($"                async ({lambdaParamStr}) =>");
                sb.AppendLine("                {");

                var bestCtor = FindBestConstructor(ep.RequestType, allProperties);
                var ctorParamNames = bestCtor != null
                    ? new HashSet<string>(bestCtor.Parameters.Select(p => p.Name), StringComparer.OrdinalIgnoreCase)
                    : new HashSet<string>(StringComparer.OrdinalIgnoreCase);

                var ctorArgStr = "";
                if (bestCtor != null)
                {
                    var ctorArgs = new List<string>();
                    foreach (var ctorParam in bestCtor.Parameters)
                    {
                        var routeMatch = routeParamProps.FirstOrDefault(rp =>
                            string.Equals(rp.Property.Name, ctorParam.Name, StringComparison.OrdinalIgnoreCase));
                        if (routeMatch.Property != null)
                        {
                            ctorArgs.Add(ToCamelCase(routeMatch.Property.Name));
                        }
                        else
                        {
                            var bodyMatch = bodyProps.FirstOrDefault(bp =>
                                string.Equals(bp.Name, ctorParam.Name, StringComparison.OrdinalIgnoreCase));
                            ctorArgs.Add(bodyMatch != null ? $"__body__.{bodyMatch.Name}" : "default");
                        }
                    }

                    ctorArgStr = string.Join(", ", ctorArgs);
                }

                var initLines = new List<string>();
                foreach (var (_, prop) in routeParamProps)
                {
                    if (!ctorParamNames.Contains(prop.Name))
                    {
                        initLines.Add($"                        {prop.Name} = {ToCamelCase(prop.Name)}");
                    }
                }

                foreach (var prop in bodyProps)
                {
                    if (!ctorParamNames.Contains(prop.Name))
                    {
                        initLines.Add($"                        {prop.Name} = __body__.{prop.Name}");
                    }
                }

                if (initLines.Count > 0)
                {
                    sb.AppendLine($"                    var request = new {requestType}({ctorArgStr})");
                    sb.AppendLine("                    {");
                    for (var i = 0; i < initLines.Count; i++)
                    {
                        sb.Append(initLines[i]);
                        sb.AppendLine(i < initLines.Count - 1 ? "," : "");
                    }

                    sb.AppendLine("                    };");
                }
                else
                {
                    sb.AppendLine($"                    var request = new {requestType}({ctorArgStr});");
                }

                var serviceCallForConstructed = ep.ServiceHasCancellationToken
                    ? $"service.{ep.ServiceMethodName}(request, cancellationToken)"
                    : $"service.{ep.ServiceMethodName}(request)";
                var serviceInvocationForConstructed = ep.ReturnInfo.Kind switch
                {
                    ServiceReturnKind.TaskOfResult => $"await {serviceCallForConstructed}",
                    ServiceReturnKind.TaskOfResultOfT => $"await {serviceCallForConstructed}",
                    _ => throw new InvalidOperationException("Unsupported service return kind.")
                };

                EmitEndpointResponse(sb, ep.ReturnInfo.Kind, serviceInvocationForConstructed);
                sb.Append("                })");
            }
        }

        if (!string.IsNullOrEmpty(ep.DisplayName))
        {
            sb.Append($".WithName(\"{EscapeString(ep.DisplayName)}\")");
        }

        if (!string.IsNullOrEmpty(ep.Summary))
        {
            sb.Append($".WithSummary(\"{EscapeString(ep.Summary)}\")");
        }

        if (!string.IsNullOrEmpty(ep.Description))
        {
            sb.Append($".WithDescription(\"{EscapeString(ep.Description)}\")");
        }

        if (ep.Tags.Length > 0)
        {
            var tagArgs = string.Join(", ", ep.Tags.Select(t => $"\"{EscapeString(t)}\""));
            sb.Append($".WithTags({tagArgs})");
        }

        sb.AppendLine(";");
        sb.AppendLine();
    }

    private static void EmitBodyDtoIfNeeded(StringBuilder sb, EndpointInfo ep, string dtoName)
    {
        if (ep.Method == HttpVerb.Get)
        {
            return;
        }

        if (ep.RequestType == null)
        {
            return;
        }

        var routeParams = RpcServiceHelpers.ExtractRouteParameters(ep.Route);
        if (routeParams.Count == 0)
        {
            return;
        }

        var allProperties = RpcServiceHelpers.GetAllPublicProperties(ep.RequestType);
        var (_, bodyProps) = SplitRouteAndBodyProps(allProperties, routeParams);
        if (bodyProps.Count == 0)
        {
            return;
        }

        sb.AppendLine($"    public class {dtoName}");
        sb.AppendLine("    {");
        foreach (var prop in bodyProps)
        {
            var propType = prop.Type.ToDisplayString();
            var defaultValue = prop.Type.IsValueType ? "" : " = default!;";
            if (prop.Type.NullableAnnotation == NullableAnnotation.Annotated)
            {
                defaultValue = "";
            }

            sb.AppendLine($"        public {propType} {prop.Name} {{ get; set; }}{defaultValue}");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitEndpointResponse(StringBuilder sb, ServiceReturnKind returnKind, string invocation)
    {
        sb.AppendLine($"                    var response = {invocation};");
        sb.AppendLine("                    return global::Microsoft.AspNetCore.Http.TypedResults.Ok(response);");
    }

    private static IMethodSymbol? FindBestConstructor(INamedTypeSymbol typeSymbol, List<IPropertySymbol> allProperties)
    {
        var propNames = new HashSet<string>(allProperties.Select(p => p.Name), StringComparer.OrdinalIgnoreCase);

        return typeSymbol.Constructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public
                        && !c.IsStatic
                        && c.Parameters.Length > 0
                        && c.Parameters.All(p => propNames.Contains(p.Name)))
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault();
    }

    private static (List<(string RouteParamName, IPropertySymbol Property)> RouteProps, List<IPropertySymbol> BodyProps)
        SplitRouteAndBodyProps(List<IPropertySymbol> allProperties, List<string> routeParams)
    {
        var routeParamProps = new List<(string RouteParamName, IPropertySymbol Property)>();
        var bodyProps = new List<IPropertySymbol>();

        foreach (var prop in allProperties)
        {
            var matchedParam = routeParams.FirstOrDefault(rp =>
                string.Equals(rp, prop.Name, StringComparison.OrdinalIgnoreCase));
            if (matchedParam != null)
            {
                routeParamProps.Add((matchedParam, prop));
            }
            else
            {
                bodyProps.Add(prop);
            }
        }

        return (routeParamProps, bodyProps);
    }

    private static string GetInterceptorBodyDtoName(INamedTypeSymbol serviceType, INamedTypeSymbol? requestType)
        => requestType != null
            ? $"__{SanitizeIdentifier(serviceType.ToDisplayString())}_{requestType.Name}_Body__"
            : $"__{SanitizeIdentifier(serviceType.ToDisplayString())}_NoRequest_Body__";

    private static string SanitizeIdentifier(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return "_";
        }

        var sb = new StringBuilder(value.Length + 1);
        if (!char.IsLetter(value[0]) && value[0] != '_')
        {
            sb.Append('_');
        }

        foreach (var ch in value)
        {
            sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
        }

        return sb.ToString();
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static string EscapeString(string? value)
    {
        if (value is null)
        {
            return string.Empty;
        }

        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private sealed class MapServiceInvocationInfo
    {
        public MapServiceInvocationInfo(InterceptableLocation location, INamedTypeSymbol serviceType)
        {
            Location = location;
            ServiceType = serviceType;
        }

        public InterceptableLocation Location { get; }

        public INamedTypeSymbol ServiceType { get; }
    }
}
