using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NOF.Infrastructure.SourceGenerator;

/// <summary>
/// 源生成器：检测标记了 AutoInjectAttribute 的服务类（包括引用项目），并生成 DI 注册代码
/// </summary>
[Generator]
public class AutoInjectGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. 从当前项目的源代码中提取带 AutoInject 的类（语法 + 语义）
        var sourceClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) =>
                {
                    if (ctx.Node is not ClassDeclarationSyntax cds)
                    {
                        return null;
                    }
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(cds);
                    if (symbol is { IsAbstract: false, DeclaredAccessibility: Accessibility.Public } &&
                        HasAutoInjectAttribute(symbol))
                    {
                        return symbol;
                    }
                    return null;
                })
            .Where(static s => s is not null);

        // 2. 从所有引用程序集（metadata）中提取带 AutoInject 的 public 非抽象类
        var referencedTypes = context.CompilationProvider
            .Select(static (compilation, _) =>
            {
                var builder = ImmutableArray.CreateBuilder<INamedTypeSymbol>();
                foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
                {
                    CollectAutoInjectTypes(assembly.GlobalNamespace, builder);
                }
                return builder.ToImmutable();
            });

        // 3. 合并两部分结果
        var allTypes = referencedTypes.Combine(sourceClasses.Collect())
            .Select(static (pair, _) =>
            {
                var (fromRefs, fromSource) = pair;
                var set = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
                foreach (var t in fromRefs)
                {
                    set.Add(t);
                }
                foreach (var t in Enumerable.OfType<INamedTypeSymbol>(fromSource))
                {
                    set.Add(t);
                }
                return set.ToImmutableArray();
            });

        // 4. 生成代码
        context.RegisterSourceOutput(allTypes, static (spc, types) =>
        {
            if (types.IsEmpty)
            {
                return;
            }

            var source = GenerateServiceRegistrationExtension(types);
            spc.AddSource("ServiceCollectionExtensions.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static void CollectAutoInjectTypes(INamespaceSymbol ns, ImmutableArray<INamedTypeSymbol>.Builder builder)
    {
        foreach (var member in ns.GetMembers())
        {
            switch (member)
            {
                case INamespaceSymbol childNs:
                    CollectAutoInjectTypes(childNs, builder);
                    break;
                case INamedTypeSymbol { IsAbstract: false, DeclaredAccessibility: Accessibility.Public } type when HasAutoInjectAttribute(type):
                    builder.Add(type);
                    break;
            }
        }
    }

    private static bool HasAutoInjectAttribute(ISymbol symbol)
        => symbol.GetAttributes().Any(attr => attr.AttributeClass?.ToDisplayString() == "NOF.AutoInjectAttribute");

    private static string GenerateServiceRegistrationExtension(ImmutableArray<INamedTypeSymbol> serviceClasses)
    {
        const string targetNamespace = "NOF.Generated";
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using System;");
        sb.AppendLine();

        sb.AppendLine($"namespace {targetNamespace}");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 自动生成的服务注册扩展方法");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class __ServiceCollectionExtensions__");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 自动注册所有标记了 AutoInjectAttribute 的服务");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"services\">服务集合</param>");
        sb.AppendLine("        /// <returns>用于链式调用的服务集合</returns>");

        sb.AppendLine("        public static IServiceCollection AddAutoInjectServices(this IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var serviceClass in serviceClasses)
        {
            GenerateServiceRegistration(sb, serviceClass);
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateServiceRegistration(StringBuilder sb, INamedTypeSymbol serviceClass)
    {
        var attribute = serviceClass.GetAttributes()
            .FirstOrDefault(attr =>
                attr.AttributeClass?.Name == "AutoInjectAttribute" ||
                (attr.AttributeClass != null ? attr.AttributeClass.ToDisplayString().EndsWith("AutoInjectAttribute") : false));

        if (attribute == null)
            return;

        // 解析生命周期
        var lifetime = "ServiceLifetime.Transient";
        if (attribute.ConstructorArguments.Length > 0 && attribute.ConstructorArguments[0].Value is int intValue)
        {
            lifetime = intValue switch
            {
                0 => "ServiceLifetime.Singleton",
                1 => "ServiceLifetime.Scoped",
                _ => "ServiceLifetime.Transient"
            };
        }

        // 获取完全限定但无 global:: 的类型名
        var typeFormat = SymbolDisplayFormat.FullyQualifiedFormat
            .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted)
            .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

        var serviceTypeName = serviceClass.ToDisplayString(typeFormat);

        // 检查是否有显式 RegisterTypes
        var registerTypesArg = attribute.NamedArguments.FirstOrDefault(kvp => kvp.Key == "RegisterTypes").Value;
        var hasExplicitRegisterTypes = !registerTypesArg.IsNull;

        var typesToRegister = new List<string>();

        if (hasExplicitRegisterTypes)
        {
            // RegisterTypes 是 Type[]，每个值是 ITypeSymbol
            foreach (var typedConstant in registerTypesArg.Values)
            {
                if (typedConstant.Value is ITypeSymbol regType && regType.ToDisplayString() != serviceTypeName)
                {
                    typesToRegister.Add(regType.ToDisplayString(typeFormat));
                }
            }
        }
        else
        {
            // 默认：注册所有实现的接口
            typesToRegister.AddRange(serviceClass.AllInterfaces.Select(i => i.ToDisplayString(typeFormat)));
        }

        // 处理 Singleton / Scoped（需要共享实例）
        if (lifetime is "ServiceLifetime.Singleton" or "ServiceLifetime.Scoped")
        {
            if (typesToRegister.Count == 1)
            {
                sb.AppendLine($"            services.Add(new ServiceDescriptor(typeof({typesToRegister[0]}), typeof({serviceTypeName}), {lifetime}));");
            }
            else
            {
                // 先注册自身
                sb.AppendLine($"            services.Add(new ServiceDescriptor(typeof({serviceTypeName}), typeof({serviceTypeName}), {lifetime}));");
                // 再注册接口（工厂委托指向自身）
                foreach (var typeName in typesToRegister)
                {
                    sb.AppendLine($"            services.Add(new ServiceDescriptor(typeof({typeName}), sp => sp.GetRequiredService<{serviceTypeName}>(), {lifetime}));");
                }
            }
        }
        else // Transient
        {
            if (hasExplicitRegisterTypes)
            {
                foreach (var typeName in registerTypesArg.Values
                             .Select(v => v.Value as ITypeSymbol)
                             .Where(t => t != null)
                             .Select(t => t!.ToDisplayString(typeFormat)))
                {
                    sb.AppendLine($"            services.Add(new ServiceDescriptor(typeof({typeName}), typeof({serviceTypeName}), {lifetime}));");
                }
            }
            else
            {
                if (typesToRegister.Count > 0)
                {
                    foreach (var typeName in typesToRegister)
                    {
                        sb.AppendLine($"            services.Add(new ServiceDescriptor(typeof({typeName}), typeof({serviceTypeName}), {lifetime}));");
                    }
                }
                else
                {
                    // 没有接口，注册自身
                    sb.AppendLine($"            services.Add(new ServiceDescriptor(typeof({serviceTypeName}), typeof({serviceTypeName}), {lifetime}));");
                }
            }
        }

        sb.AppendLine();
    }
}